In [1]:
import networkx as nx
import numpy as np
from scipy.io import mmread
import pandas as pd


from sklearn import metrics

import copy
import scipy.sparse as sp
import os
import anndata as ad
# os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
import scanpy as sc
import scirpy as ir
import pandas as pd
import awkward as ak

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

/home/phile/miniconda3/envs/mvTCR/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
from mvtcr.utils_preprocessing import Preprocessing

/home/phile/miniconda3/envs/mvTCR/lib/python3.10/site-packages/comet_ml/env_logging.py:31: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

In [3]:
# train, val = Preprocessing.stratified_group_shuffle_split(gene_TCR, stratify_col='donor', group_col='clonotype', test_size=0.2, random_seed=42)

# gene_TCR.obs['set'] = 'train'
# gene_TCR.obs.loc[val, 'set'] = 'val'

# gene_TCR.obs["set"].value_counts()

In [4]:
gene_TCR = sc.read_h5ad('./data/gene_TCR_mvTCR_ready_for_running_integration.h5ad')

In [5]:
gene_TCR.obs = gene_TCR.obs.reset_index(drop=False)
gene_TCR.obs

,index,v_gene_TRA,v_gene_TRB,d_gene_TRA,d_gene_TRB,j_gene_TRA,j_gene_TRB,c_gene_TRA,c_gene_TRB,cdr3_TRA,...,n_genes,mt_fraction,receptor_type,receptor_subtype,chain_pairing,clonotype,clonotype_size,alpha_len,beta_len,set
0,AGGGTGAGTATTACCG-18_0,TRAV19,TRBV20-1,None,TRBD2,TRAJ40,TRBJ2-3,TRAC,TRBC2,CALSEASGTYKYIF,...,1830,0.058050,TCR,TRA+TRB,single pair,0,3166,11,13,val
1,CTTGGCTTCGTTGCCT-25_1,TRAV23DV6,TRBV7-2,None,TRBD1,TRAJ48,TRBJ2-5,TRAC,TRBC2,CAAILFGNEKLTF,...,1382,0.063250,TCR,TRA+TRB,single pair,1,5666,13,14,train
2,ACGATACTCGCAGGCT-40_2,TRAV9-2,TRBV7-6,None,TRBD2,TRAJ49,TRBJ2-3,TRAC,TRBC2,CALSADTGNQFYF,...,1279,0.067611,TCR,TRA+TRB,single pair,2,125,15,14,train
3,ACGCCAGTCATGTCTT-8_3,TRAV12-3,TRBV20-1,None,TRBD1,TRAJ32,TRBJ2-7,TRAC,TRBC2,CAMNPAWGGATNKLIF,...,1669,0.054716,TCR,TRA+TRB,single pair,3,230,11,16,train
4,TTCTTAGCAAAGAATC-4_4,TRAV13-2,TRBV4-1,None,TRBD2,TRAJ37,TRBJ2-1,TRAC,TRBC2,CAETALGNTGKLIF,...,2683,0.044035,TCR,TRA+TRB,single pair,4,1,15,13,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145474,GAAGCAGAGCAGGCTA-3_145474,TRAV22,TRBV24-1,None,TRBD2,TRAJ47,TRBJ2-2,TRAC,TRBC2,CAVEPLYGNKLVF,...,789,0.135747,TCR,TRA+TRB,single pair,58159,1,14,13,train
145475,CAGTCCTTCATCACCC-8_145475,TRAV29DV5,TRBV7-6,None,TRBD2,TRAJ50,TRBJ2-3,TRAC,TRBC2,CAATHASGYDKVIF,...,1468,0.041688,TCR,TRA+TRB,single pair,1286,14,15,16,train
145476,GACTACACACGGTAAG-3_145476,TRAV21,TRBV6-6,None,TRBD2,TRAJ50,TRBJ2-3,TRAC,TRBC2,CAVDLMKTSYDKVIF,...,1646,0.047574,TCR,TRA+TRB,single pair,58160,1,16,15,train
145477,ATCGAGTAGTTTCCTT-4_145477,TRAV3,TRBV5-1,None,TRBD2,TRAJ34,TRBJ2-2,TRAC,TRBC2,CAVREGRGTDKLIF,...,782,0.137519,TCR,TRA+TRB,single pair,4623,22,14,14,train
145478,ACCCACTTCTTGGGTA-3_145478,TRAV12-2,TRBV27,None,TRBD2,TRAJ6,TRBJ2-1,TRAC,TRBC2,CAVNWEEQGGSYIPTF,...,1804,0.040118,TCR,TRA+TRB,single pair,205,229,15,15,train

In [6]:
ls_index = os.listdir('./5 to 1 Indices')
ls_index

['smart_aligned_v2_train_indices_random_split_2.npy',
 'smart_aligned_v2_train_indices_random_split_4.npy',
 'smart_aligned_v2_train_indices_tcr_split_4.npy',
 'smart_aligned_v2_test_indices_tcr_ab_split_1.npy',
 'smart_aligned_v2_test_indices_random_split_2.npy',
 'smart_aligned_v2_train_indices_tcr_split_3.npy',
 'smart_aligned_v2_train_indices_tcr_ab_split_5.npy',
 'smart_aligned_v2_val_indices_tcr_split_4.npy',
 'smart_aligned_v2_train_indices_tcr_split_1.npy',
 'smart_aligned_v2_test_indices_random_split_3.npy',
 'smart_aligned_v2_test_indices_tcr_ab_split_3.npy',
 'smart_aligned_v2_val_indices_tcr_split_5.npy',
 'smart_aligned_v2_val_indices_tcr_ab_split_1.npy',
 'smart_aligned_v2_train_indices_random_split_1.npy',
 'smart_aligned_v2_val_indices_random_split_1.npy',
 'smart_aligned_v2_val_indices_random_split_3.npy',
 'smart_aligned_v2_test_indices_tcr_split_3.npy',
 'smart_aligned_v2_val_indices_tcr_ab_split_4.npy',
 'smart_aligned_v2_val_indices_tcr_ab_split_5.npy',
 'smart_aligned_v2_train_indices_random_split_3.npy',
 'smart_aligned_v2_val_indices_random_split_4.npy',
 'smart_aligned_v2_train_indices_tcr_ab_split_1.npy',
 'smart_aligned_v2_test_indices_tcr_split_1.npy',
 'smart_aligned_v2_train_indices_tcr_split_2.npy',
 'smart_aligned_v2_train_indices_tcr_ab_split_4.npy',
 'smart_aligned_v2_val_indices_tcr_ab_split_2.npy',
 'smart_aligned_v2_test_indices_random_split_4.npy',
 'smart_aligned_v2_train_indices_tcr_ab_split_3.npy',
 'smart_aligned_v2_val_indices_random_split_5.npy',
 'smart_aligned_v2_test_indices_tcr_split_2.npy',
 'smart_aligned_v2_val_indices_random_split_2.npy',
 'smart_aligned_v2_train_indices_random_split_5.npy',
 'smart_aligned_v2_test_indices_tcr_ab_split_2.npy',
 'smart_aligned_v2_train_indices_tcr_split_5.npy',
 'smart_aligned_v2_test_indices_tcr_split_4.npy',
 'smart_aligned_v2_test_indices_random_split_1.npy',
 'smart_aligned_v2_val_indices_tcr_ab_split_3.npy',
 'smart_aligned_v2_test_indices_random_split_5.npy',
 'smart_aligned_v2_test_indices_tcr_ab_split_4.npy',
 'smart_aligned_v2_train_indices_tcr_ab_split_2.npy',
 'smart_aligned_v2_val_indices_tcr_split_1.npy',
 'smart_aligned_v2_val_indices_tcr_split_3.npy',
 'smart_aligned_v2_test_indices_tcr_split_5.npy',
 'smart_aligned_v2_val_indices_tcr_split_2.npy',
 'smart_aligned_v2_test_indices_tcr_ab_split_5.npy']

In [7]:
ref_dat = pd.read_csv('./data/smart_aligned_v2_dataset_reference_5_to_1.csv')
ref_dat

,tcr,peptide,label,tcr_source_dataset,tcr_source_index,peptide_source_dataset,peptide_source_index,donor,binding_tcr
0,CASSLYEQYF,GILGFVFTL,1,10X,0,10X,0,donor1,Y
1,CAWTGTGKIGWDSPLHF,KLGGALQAK,1,10X,2,10X,2,donor1,Y
2,CASSWGGGSHYGYTF,IVTDFSVIK,1,10X,3,10X,3,donor1,Y
3,CASSLYSATGELFF,AVFDRKSDAK,1,10X,5,10X,5,donor1,Y
4,CASSLYSATGELFF,AVFDRKSDAK,1,10X,6,10X,6,donor1,Y
...,...,...,...,...,...,...,...,...,...
431041,CASSFGRGEGEQYF,ELAGIGILTV,0,10X,39940,10X,258,NaN,N
431042,CASSPHFQVDTGELFF,IVTDFSVIK,0,10X,85427,10X,3,NaN,Y
431043,CASSLMRGGTYNSPLHF,FLYALALLL,0,10X,72515,10X,134,NaN,N
431044,CASSVSSTDTQYF,GILGFVFTL,0,10X,133931,10X,0,NaN,Y
431045,CASSFRDSRYEQYF,RAKFKQLL,0,10X,34178,10X,44,NaN,N

In [11]:
from mvtcr.models.model_selection import run_model_selection
timeout = (400*60)
n_samples = 3
n_gpus = 1
seed = 42

In [9]:
import io
from contextlib import redirect_stdout

In [15]:
for i in ls_index[1:]:
    if i.endswith('.npy'):
        data_ix = np.load(os.path.join('./5 to 1 Indices', i), allow_pickle=True)
        ref_dat_index = ref_dat.iloc[data_ix]
        gene_TCR_integration = gene_TCR[ref_dat_index['tcr_source_index'].values].copy()
        params_experiment = {
            'study_name': '10X_mvTCR_embedding_cluster',
            'comet_workspace': None, 
            'model_name': 'moe',
            'balanced_sampling': 'clonotype',
            'metadata': [],
            'save_path': f'./mvTCR_integration_res_5_to_1/saved_models/{i.split(".")[0]}/10X_mvTCR_embedding_cluster',
            'conditional': 'donor_ohe',
            'n_epochs': 6,
        }
        params_optimization = {
            'name': 'knn_prediction',
            'prediction_column': 'antigen',
        }
        f = io.StringIO()
        with redirect_stdout(f):
            run_model_selection(gene_TCR_integration, params_experiment, params_optimization, n_samples, timeout, n_gpus, sampler_seed=seed)


            captured_output = f.getvalue()
            best_model = captured_output.splitlines()[5].strip(" ")

            import mvtcr.utils_training as utils


            path_model = f'./mvTCR_integration_res_5_to_1/saved_models/{i.split(".")[0]}/10X_mvTCR_embedding_cluster/{best_model}/best_model_by_reconstruction.pt'
            model = utils.load_model(gene_TCR_integration, path_model)


            mvTCR_integration_latent = model.get_latent(gene_TCR_integration, metadata=[], return_mean=False).X
            mvTCR_integration_latent.shape
            pd.DataFrame(mvTCR_integration_latent).to_csv(f"./mvTCR_integration_res_5_to_1/10X_mvTCR_embedding_integration_latent_best_reconstruction_metric_{i.split('.')[0]}.csv", index=False)

[I 2026-04-03 14:26:14,219] A new study created in RDB with name: 10X_mvTCR_embedding_cluster
100%|██████████| 6/6 [10:14<00:00, 102.48s/it]
[I 2026-04-03 14:36:35,102] Trial 0 finished with value: 0.5688531618389147 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1500, 'hdim': 200, 'shared_hidden': 100, 'rna_num_layers': 1, 'tfmr_encoding_layers': 4, 'loss_weights_kl': 4.0428727350273357e-07, 'loss_weights_tcr': 0.034702669886504146, 'lr': 1.0994335574766187e-05, 'zdim': 50, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.15000000000000002}. Best is trial 0 with value: 0.5688531618389147.
100%|██████████| 6/6 [04:45<00:00, 47.59s/it]
[I 2026-04-03 14:41:27,283] Trial 1 finished with value: 0.5519191632756539 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1000, 'hdim': 300, 'shared_hidden': 300, 'rna_num_layers': 3, 'tfmr_encoding_layers': 1, 'loss_weights_kl': 1.2173252504194046e-07, 'loss_weights_tcr': 0.009163741808778781, 'lr': 1.2385137298860926e-05, 'zdim': 35, 'tfmr_embedding_size': 64, 'tfmr_num_heads': 2, 'tfmr_dropout': 0.0}. Best is trial 0 with value: 0.5688531618389147.
100%|██████████| 6/6 [07:41<00:00, 76.94s/it]
[I 2026-04-03 14:49:15,101] Trial 2 finished with value: 0.5773389231425209 and parameters: {'dropout': 0.2, 'activation': 'linear', 'rna_hidden': 1250, 'hdim': 100, 'shared_hidden': 200, 'rna_num_layers': 1, 'tfmr_encoding_layers': 3, 'loss_weights_kl': 7.41765203487182e-09, 'loss_weights_tcr': 0.003984190594434687, 'lr': 0.00012399967836846095, 'zdim': 10, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.0}. Best is trial 2 with value: 0.5773389231425209.
[I 2026-04-03 14:49:48,582] A new study created in RDB with name: 10X_mvTCR_embedding_cluster
100%|██████████| 6/6 [09:15<00:00, 92.50s/it]
[I 2026-04-03 14:59:08,641] Trial 0 finished with value: 0.5707225830974446 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1500, 'hdim': 200, 'shared_hidden': 100, 'rna_num_layers': 1, 'tfmr_encoding_layers': 4, 'loss_weights_kl': 4.0428727350273357e-07, 'loss_weights_tcr': 0.034702669886504146, 'lr': 1.0994335574766187e-05, 'zdim': 50, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.15000000000000002}. Best is trial 0 with value: 0.5707225830974446.
100%|██████████| 6/6 [04:21<00:00, 43.66s/it]
[I 2026-04-03 15:03:35,773] Trial 1 finished with value: 0.5434362633730687 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1000, 'hdim': 300, 'shared_hidden': 300, 'rna_num_layers': 3, 'tfmr_encoding_layers': 1, 'loss_weights_kl': 1.2173252504194046e-07, 'loss_weights_tcr': 0.009163741808778781, 'lr': 1.2385137298860926e-05, 'zdim': 35, 'tfmr_embedding_size': 64, 'tfmr_num_heads': 2, 'tfmr_dropout': 0.0}. Best is trial 0 with value: 0.5707225830974446.
100%|██████████| 6/6 [07:07<00:00, 71.31s/it]
[I 2026-04-03 15:10:49,181] Trial 2 finished with value: 0.5796333952120191 and parameters: {'dropout': 0.2, 'activation': 'linear', 'rna_hidden': 1250, 'hdim': 100, 'shared_hidden': 200, 'rna_num_layers': 1, 'tfmr_encoding_layers': 3, 'loss_weights_kl': 7.41765203487182e-09, 'loss_weights_tcr': 0.003984190594434687, 'lr': 0.00012399967836846095, 'zdim': 10, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.0}. Best is trial 2 with value: 0.5796333952120191.
[I 2026-04-03 15:11:19,336] A new study created in RDB with name: 10X_mvTCR_embedding_cluster
100%|██████████| 6/6 [02:26<00:00, 24.37s/it]
[I 2026-04-03 15:13:47,839] Trial 0 finished with value: 0.5574712893856015 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1500, 'hdim': 200, 'shared_hidden': 100, 'rna_num_layers': 1, 'tfmr_encoding_layers': 4, 'loss_weights_kl': 4.0428727350273357e-07, 'loss_weights_tcr': 0.034702669886504146, 'lr': 1.0994335574766187e-05, 'zdim': 50, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.15000000000000002}. Best is trial 0 with value: 0.5574712893856015.
100%|██████████| 6/6 [01:04<00:00, 10.75s/it]
[I 2026-04-03 15:14:54,652] Trial 1 finished with value: 0.5229196131960224 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1000, 'hdim': 300, 'shared_hidden': 300, 'rna_num_layers': 3, 'tfmr_encoding_layers': 1, 'loss_weights_kl': 1.2173252504194046e-07, 'loss_weights_tcr': 0.009163741808778781, 'lr': 1.2385137298860926e-05, 'zdim': 35, 'tfmr_embedding_size': 64, 'tfmr_num_heads': 2, 'tfmr_dropout': 0.0}. Best is trial 0 with value: 0.5574712893856015.
100%|██████████| 6/6 [01:56<00:00, 19.47s/it]
[I 2026-04-03 15:16:53,737] Trial 2 finished with value: 0.5556235353340161 and parameters: {'dropout': 0.2, 'activation': 'linear', 'rna_hidden': 1250, 'hdim': 100, 'shared_hidden': 200, 'rna_num_layers': 1, 'tfmr_encoding_layers': 3, 'loss_weights_kl': 7.41765203487182e-09, 'loss_weights_tcr': 0.003984190594434687, 'lr': 0.00012399967836846095, 'zdim': 10, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.0}. Best is trial 0 with value: 0.5574712893856015.
[I 2026-04-03 15:17:06,703] A new study created in RDB with name: 10X_mvTCR_embedding_cluster
100%|██████████| 6/6 [01:59<00:00, 19.90s/it]
[I 2026-04-03 15:19:08,149] Trial 0 finished with value: 0.5857518048096433 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1500, 'hdim': 200, 'shared_hidden': 100, 'rna_num_layers': 1, 'tfmr_encoding_layers': 4, 'loss_weights_kl': 4.0428727350273357e-07, 'loss_weights_tcr': 0.034702669886504146, 'lr': 1.0994335574766187e-05, 'zdim': 50, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.15000000000000002}. Best is trial 0 with value: 0.5857518048096433.
100%|██████████| 6/6 [00:51<00:00,  8.63s/it]
[I 2026-04-03 15:20:02,002] Trial 1 finished with value: 0.5549345594803736 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1000, 'hdim': 300, 'shared_hidden': 300, 'rna_num_layers': 3, 'tfmr_encoding_layers': 1, 'loss_weights_kl': 1.2173252504194046e-07, 'loss_weights_tcr': 0.009163741808778781, 'lr': 1.2385137298860926e-05, 'zdim': 35, 'tfmr_embedding_size': 64, 'tfmr_num_heads': 2, 'tfmr_dropout': 0.0}. Best is trial 0 with value: 0.5857518048096433.
100%|██████████| 6/6 [01:36<00:00, 16.04s/it]
[I 2026-04-03 15:21:40,260] Trial 2 finished with value: 0.593027371500402 and parameters: {'dropout': 0.2, 'activation': 'linear', 'rna_hidden': 1250, 'hdim': 100, 'shared_hidden': 200, 'rna_num_layers': 1, 'tfmr_encoding_layers': 3, 'loss_weights_kl': 7.41765203487182e-09, 'loss_weights_tcr': 0.003984190594434687, 'lr': 0.00012399967836846095, 'zdim': 10, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.0}. Best is trial 2 with value: 0.593027371500402.
[I 2026-04-03 15:21:49,726] A new study created in RDB with name: 10X_mvTCR_embedding_cluster
100%|██████████| 6/6 [08:57<00:00, 89.51s/it]
[I 2026-04-03 15:30:52,197] Trial 0 finished with value: 0.568950068373808 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1500, 'hdim': 200, 'shared_hidden': 100, 'rna_num_layers': 1, 'tfmr_encoding_layers': 4, 'loss_weights_kl': 4.0428727350273357e-07, 'loss_weights_tcr': 0.034702669886504146, 'lr': 1.0994335574766187e-05, 'zdim': 50, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.15000000000000002}. Best is trial 0 with value: 0.568950068373808.
100%|██████████| 6/6 [04:27<00:00, 44.59s/it]
[I 2026-04-03 15:35:25,142] Trial 1 finished with value: 0.5539776859613896 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1000, 'hdim': 300, 'shared_hidden': 300, 'rna_num_layers': 3, 'tfmr_encoding_layers': 1, 'loss_weights_kl': 1.2173252504194046e-07, 'loss_weights_tcr': 0.009163741808778781, 'lr': 1.2385137298860926e-05, 'zdim': 35, 'tfmr_embedding_size': 64, 'tfmr_num_heads': 2, 'tfmr_dropout': 0.0}. Best is trial 0 with value: 0.568950068373808.
100%|██████████| 6/6 [07:07<00:00, 71.25s/it]
[I 2026-04-03 15:42:38,269] Trial 2 finished with value: 0.5628496079125187 and parameters: {'dropout': 0.2, 'activation': 'linear', 'rna_hidden': 1250, 'hdim': 100, 'shared_hidden': 200, 'rna_num_layers': 1, 'tfmr_encoding_layers': 3, 'loss_weights_kl': 7.41765203487182e-09, 'loss_weights_tcr': 0.003984190594434687, 'lr': 0.00012399967836846095, 'zdim': 10, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.0}. Best is trial 0 with value: 0.568950068373808.
[I 2026-04-03 15:43:21,396] A new study created in RDB with name: 10X_mvTCR_embedding_cluster
100%|██████████| 6/6 [09:18<00:00, 93.01s/it]
[I 2026-04-03 15:52:44,687] Trial 0 finished with value: 0.5708772283165692 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1500, 'hdim': 200, 'shared_hidden': 100, 'rna_num_layers': 1, 'tfmr_encoding_layers': 4, 'loss_weights_kl': 4.0428727350273357e-07, 'loss_weights_tcr': 0.034702669886504146, 'lr': 1.0994335574766187e-05, 'zdim': 50, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.15000000000000002}. Best is trial 0 with value: 0.5708772283165692.
100%|██████████| 6/6 [04:26<00:00, 44.49s/it]
[I 2026-04-03 15:57:16,957] Trial 1 finished with value: 0.5504816471995648 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1000, 'hdim': 300, 'shared_hidden': 300, 'rna_num_layers': 3, 'tfmr_encoding_layers': 1, 'loss_weights_kl': 1.2173252504194046e-07, 'loss_weights_tcr': 0.009163741808778781, 'lr': 1.2385137298860926e-05, 'zdim': 35, 'tfmr_embedding_size': 64, 'tfmr_num_heads': 2, 'tfmr_dropout': 0.0}. Best is trial 0 with value: 0.5708772283165692.
100%|██████████| 6/6 [06:55<00:00, 69.26s/it]
[I 2026-04-03 16:04:17,892] Trial 2 finished with value: 0.5652409605932659 and parameters: {'dropout': 0.2, 'activation': 'linear', 'rna_hidden': 1250, 'hdim': 100, 'shared_hidden': 200, 'rna_num_layers': 1, 'tfmr_encoding_layers': 3, 'loss_weights_kl': 7.41765203487182e-09, 'loss_weights_tcr': 0.003984190594434687, 'lr': 0.00012399967836846095, 'zdim': 10, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.0}. Best is trial 0 with value: 0.5708772283165692.
[I 2026-04-03 16:04:57,382] A new study created in RDB with name: 10X_mvTCR_embedding_cluster
100%|██████████| 6/6 [02:07<00:00, 21.31s/it]
[I 2026-04-03 16:07:07,419] Trial 0 finished with value: 0.5847770036024053 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1500, 'hdim': 200, 'shared_hidden': 100, 'rna_num_layers': 1, 'tfmr_encoding_layers': 4, 'loss_weights_kl': 4.0428727350273357e-07, 'loss_weights_tcr': 0.034702669886504146, 'lr': 1.0994335574766187e-05, 'zdim': 50, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.15000000000000002}. Best is trial 0 with value: 0.5847770036024053.
100%|██████████| 6/6 [00:55<00:00,  9.24s/it]
[I 2026-04-03 16:08:04,993] Trial 1 finished with value: 0.5528957782635803 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1000, 'hdim': 300, 'shared_hidden': 300, 'rna_num_layers': 3, 'tfmr_encoding_layers': 1, 'loss_weights_kl': 1.2173252504194046e-07, 'loss_weights_tcr': 0.009163741808778781, 'lr': 1.2385137298860926e-05, 'zdim': 35, 'tfmr_embedding_size': 64, 'tfmr_num_heads': 2, 'tfmr_dropout': 0.0}. Best is trial 0 with value: 0.5847770036024053.
100%|██████████| 6/6 [01:42<00:00, 17.07s/it]
[I 2026-04-03 16:09:49,552] Trial 2 finished with value: 0.5783090031320653 and parameters: {'dropout': 0.2, 'activation': 'linear', 'rna_hidden': 1250, 'hdim': 100, 'shared_hidden': 200, 'rna_num_layers': 1, 'tfmr_encoding_layers': 3, 'loss_weights_kl': 7.41765203487182e-09, 'loss_weights_tcr': 0.003984190594434687, 'lr': 0.00012399967836846095, 'zdim': 10, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.0}. Best is trial 0 with value: 0.5847770036024053.
[I 2026-04-03 16:10:02,295] A new study created in RDB with name: 10X_mvTCR_embedding_cluster
100%|██████████| 6/6 [08:56<00:00, 89.45s/it]
[I 2026-04-03 16:19:04,452] Trial 0 finished with value: 0.5802532073792102 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1500, 'hdim': 200, 'shared_hidden': 100, 'rna_num_layers': 1, 'tfmr_encoding_layers': 4, 'loss_weights_kl': 4.0428727350273357e-07, 'loss_weights_tcr': 0.034702669886504146, 'lr': 1.0994335574766187e-05, 'zdim': 50, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.15000000000000002}. Best is trial 0 with value: 0.5802532073792102.
100%|██████████| 6/6 [04:10<00:00, 41.70s/it]
[I 2026-04-03 16:23:19,858] Trial 1 finished with value: 0.5409096612872402 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1000, 'hdim': 300, 'shared_hidden': 300, 'rna_num_layers': 3, 'tfmr_encoding_layers': 1, 'loss_weights_kl': 1.2173252504194046e-07, 'loss_weights_tcr': 0.009163741808778781, 'lr': 1.2385137298860926e-05, 'zdim': 35, 'tfmr_embedding_size': 64, 'tfmr_num_heads': 2, 'tfmr_dropout': 0.0}. Best is trial 0 with value: 0.5802532073792102.
100%|██████████| 6/6 [06:53<00:00, 68.96s/it]
[I 2026-04-03 16:30:18,867] Trial 2 finished with value: 0.5843590526511467 and parameters: {'dropout': 0.2, 'activation': 'linear', 'rna_hidden': 1250, 'hdim': 100, 'shared_hidden': 200, 'rna_num_layers': 1, 'tfmr_encoding_layers': 3, 'loss_weights_kl': 7.41765203487182e-09, 'loss_weights_tcr': 0.003984190594434687, 'lr': 0.00012399967836846095, 'zdim': 10, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.0}. Best is trial 2 with value: 0.5843590526511467.
[I 2026-04-03 16:30:48,238] A new study created in RDB with name: 10X_mvTCR_embedding_cluster
100%|██████████| 6/6 [01:56<00:00, 19.48s/it]
[I 2026-04-03 16:32:47,182] Trial 0 finished with value: 0.5960745330338454 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1500, 'hdim': 200, 'shared_hidden': 100, 'rna_num_layers': 1, 'tfmr_encoding_layers': 4, 'loss_weights_kl': 4.0428727350273357e-07, 'loss_weights_tcr': 0.034702669886504146, 'lr': 1.0994335574766187e-05, 'zdim': 50, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.15000000000000002}. Best is trial 0 with value: 0.5960745330338454.
100%|██████████| 6/6 [00:50<00:00,  8.37s/it]
[I 2026-04-03 16:33:39,437] Trial 1 finished with value: 0.5666274519312918 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1000, 'hdim': 300, 'shared_hidden': 300, 'rna_num_layers': 3, 'tfmr_encoding_layers': 1, 'loss_weights_kl': 1.2173252504194046e-07, 'loss_weights_tcr': 0.009163741808778781, 'lr': 1.2385137298860926e-05, 'zdim': 35, 'tfmr_embedding_size': 64, 'tfmr_num_heads': 2, 'tfmr_dropout': 0.0}. Best is trial 0 with value: 0.5960745330338454.
100%|██████████| 6/6 [01:33<00:00, 15.57s/it]
[I 2026-04-03 16:35:14,541] Trial 2 finished with value: 0.5978392581414596 and parameters: {'dropout': 0.2, 'activation': 'linear', 'rna_hidden': 1250, 'hdim': 100, 'shared_hidden': 200, 'rna_num_layers': 1, 'tfmr_encoding_layers': 3, 'loss_weights_kl': 7.41765203487182e-09, 'loss_weights_tcr': 0.003984190594434687, 'lr': 0.00012399967836846095, 'zdim': 10, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.0}. Best is trial 2 with value: 0.5978392581414596.
[I 2026-04-03 16:35:23,379] A new study created in RDB with name: 10X_mvTCR_embedding_cluster
100%|██████████| 6/6 [02:39<00:00, 26.63s/it]
[I 2026-04-03 16:38:05,393] Trial 0 finished with value: 0.5436745028307072 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1500, 'hdim': 200, 'shared_hidden': 100, 'rna_num_layers': 1, 'tfmr_encoding_layers': 4, 'loss_weights_kl': 4.0428727350273357e-07, 'loss_weights_tcr': 0.034702669886504146, 'lr': 1.0994335574766187e-05, 'zdim': 50, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.15000000000000002}. Best is trial 0 with value: 0.5436745028307072.
100%|██████████| 6/6 [01:09<00:00, 11.58s/it]
[I 2026-04-03 16:39:17,273] Trial 1 finished with value: 0.5125028789214373 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1000, 'hdim': 300, 'shared_hidden': 300, 'rna_num_layers': 3, 'tfmr_encoding_layers': 1, 'loss_weights_kl': 1.2173252504194046e-07, 'loss_weights_tcr': 0.009163741808778781, 'lr': 1.2385137298860926e-05, 'zdim': 35, 'tfmr_embedding_size': 64, 'tfmr_num_heads': 2, 'tfmr_dropout': 0.0}. Best is trial 0 with value: 0.5436745028307072.
100%|██████████| 6/6 [02:07<00:00, 21.22s/it]
[I 2026-04-03 16:41:26,917] Trial 2 finished with value: 0.5371478018409255 and parameters: {'dropout': 0.2, 'activation': 'linear', 'rna_hidden': 1250, 'hdim': 100, 'shared_hidden': 200, 'rna_num_layers': 1, 'tfmr_encoding_layers': 3, 'loss_weights_kl': 7.41765203487182e-09, 'loss_weights_tcr': 0.003984190594434687, 'lr': 0.00012399967836846095, 'zdim': 10, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.0}. Best is trial 0 with value: 0.5436745028307072.
[I 2026-04-03 16:41:40,502] A new study created in RDB with name: 10X_mvTCR_embedding_cluster
100%|██████████| 6/6 [02:08<00:00, 21.38s/it]
[I 2026-04-03 16:43:50,885] Trial 0 finished with value: 0.5920170997510459 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1500, 'hdim': 200, 'shared_hidden': 100, 'rna_num_layers': 1, 'tfmr_encoding_layers': 4, 'loss_weights_kl': 4.0428727350273357e-07, 'loss_weights_tcr': 0.034702669886504146, 'lr': 1.0994335574766187e-05, 'zdim': 50, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.15000000000000002}. Best is trial 0 with value: 0.5920170997510459.
100%|██████████| 6/6 [00:55<00:00,  9.23s/it]
[I 2026-04-03 16:44:48,090] Trial 1 finished with value: 0.5594846730905436 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1000, 'hdim': 300, 'shared_hidden': 300, 'rna_num_layers': 3, 'tfmr_encoding_layers': 1, 'loss_weights_kl': 1.2173252504194046e-07, 'loss_weights_tcr': 0.009163741808778781, 'lr': 1.2385137298860926e-05, 'zdim': 35, 'tfmr_embedding_size': 64, 'tfmr_num_heads': 2, 'tfmr_dropout': 0.0}. Best is trial 0 with value: 0.5920170997510459.
100%|██████████| 6/6 [01:42<00:00, 17.05s/it]
[I 2026-04-03 16:46:32,446] Trial 2 finished with value: 0.5799045457377107 and parameters: {'dropout': 0.2, 'activation': 'linear', 'rna_hidden': 1250, 'hdim': 100, 'shared_hidden': 200, 'rna_num_layers': 1, 'tfmr_encoding_layers': 3, 'loss_weights_kl': 7.41765203487182e-09, 'loss_weights_tcr': 0.003984190594434687, 'lr': 0.00012399967836846095, 'zdim': 10, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.0}. Best is trial 0 with value: 0.5920170997510459.
[I 2026-04-03 16:46:43,747] A new study created in RDB with name: 10X_mvTCR_embedding_cluster
100%|██████████| 6/6 [02:07<00:00, 21.18s/it]
[I 2026-04-03 16:48:52,953] Trial 0 finished with value: 0.582659882029385 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1500, 'hdim': 200, 'shared_hidden': 100, 'rna_num_layers': 1, 'tfmr_encoding_layers': 4, 'loss_weights_kl': 4.0428727350273357e-07, 'loss_weights_tcr': 0.034702669886504146, 'lr': 1.0994335574766187e-05, 'zdim': 50, 'tfmr_embedding_size': 16, 'tfmr_num_heads': 8, 'tfmr_dropout': 0.15000000000000002}. Best is trial 0 with value: 0.582659882029385.
100%|██████████| 6/6 [00:55<00:00,  9.28s/it]
[I 2026-04-03 16:49:50,613] Trial 1 finished with value: 0.5626679302919075 and parameters: {'dropout': 0.1, 'activation': 'linear', 'rna_hidden': 1000, 'hdim': 300, 'shared_hidden': 300, 'rna_num_layers': 3, 'tfmr_encoding_layers': 1, 'loss_weights_kl': 1.2173252504194046e-07, 'loss_weights_tcr': 0.009163741808778781, 'lr': 1.2385137298860926e-05, 'zdim': 35, 'tfmr_embedding_size': 64, 'tfmr_num_heads': 2, 'tfmr_dropout': 0.0}. Best is trial 0 with value: 0.582659882029385.
100%|██████████| 6/6 [01:41<00:00, 16.95s/it]

In [ ]:
# path_model = f'./mvTCR_integration_res_5_to_1/saved_models/{i.split(".")[0]}/10X_mvTCR_embedding_cluster/{best_model}/best_model_by_reconstruction.pt'
# model = utils.load_model(gene_TCR_integration, path_model)
# mvTCR_integration_latent = model.get_latent(gene_TCR[ref_dat_index['tcr_source_index'].values], metadata=[], return_mean=False).X
# mvTCR_integration_latent.shape
# pd.DataFrame(mvTCR_integration_latent).to_csv(f"./mvTCR_integration_res_5_to_1/10X_mvTCR_embedding_integration_latent_best_reconstruction_metric_{i.split('.')[0]}.csv", index=False)

In [ ]:
import io
from contextlib import redirect_stdout

In [16]:
for i in ls_index:
    if i.endswith('.npy'):

        mvTCR_integration_latent = pd.read_csv(f"./mvTCR_integration_res_5_to_1/10X_mvTCR_embedding_integration_latent_best_reconstruction_metric_{i.split('.')[0]}.csv")
        print(i.split('.')[0])
        print(mvTCR_integration_latent.shape)

smart_aligned_v2_train_indices_random_split_2
(301732, 10)
smart_aligned_v2_train_indices_random_split_4
(301732, 10)
smart_aligned_v2_train_indices_tcr_split_4
(283032, 10)
smart_aligned_v2_test_indices_tcr_ab_split_1
(79602, 50)
smart_aligned_v2_test_indices_random_split_2
(64657, 10)
smart_aligned_v2_train_indices_tcr_split_3
(275780, 50)
smart_aligned_v2_train_indices_tcr_ab_split_5
(277048, 50)
smart_aligned_v2_val_indices_tcr_split_4
(70758, 50)
smart_aligned_v2_train_indices_tcr_split_1
(278515, 10)
smart_aligned_v2_test_indices_random_split_3
(64657, 10)
smart_aligned_v2_test_indices_tcr_ab_split_3
(87232, 50)
smart_aligned_v2_val_indices_tcr_split_5
(70433, 50)
smart_aligned_v2_val_indices_tcr_ab_split_1
(70289, 10)
smart_aligned_v2_train_indices_random_split_1
(301732, 50)
smart_aligned_v2_val_indices_random_split_1
(64657, 50)
smart_aligned_v2_val_indices_random_split_3
(64657, 50)
smart_aligned_v2_test_indices_tcr_split_3
(86321, 50)
smart_aligned_v2_val_indices_tcr_ab_split_4
(67257, 50)
smart_aligned_v2_val_indices_tcr_ab_split_5
(69263, 50)
smart_aligned_v2_train_indices_random_split_3
(301732, 10)
smart_aligned_v2_val_indices_random_split_4
(64657, 10)
smart_aligned_v2_train_indices_tcr_ab_split_1
(281155, 10)
smart_aligned_v2_test_indices_tcr_split_1
(82902, 10)
smart_aligned_v2_train_indices_tcr_split_2
(283400, 10)
smart_aligned_v2_train_indices_tcr_ab_split_4
(269025, 10)
smart_aligned_v2_val_indices_tcr_ab_split_2
(70409, 50)
smart_aligned_v2_test_indices_random_split_4
(64657, 10)
smart_aligned_v2_train_indices_tcr_ab_split_3
(275051, 10)
smart_aligned_v2_val_indices_random_split_5
(64657, 50)
smart_aligned_v2_test_indices_tcr_split_2
(76795, 50)
smart_aligned_v2_val_indices_random_split_2
(64657, 10)
smart_aligned_v2_train_indices_random_split_5
(301732, 50)
smart_aligned_v2_test_indices_tcr_ab_split_2
(79001, 10)
smart_aligned_v2_train_indices_tcr_split_5
(281730, 50)
smart_aligned_v2_test_indices_tcr_split_4
(77256, 10)
smart_aligned_v2_test_indices_random_split_1
(64657, 10)
smart_aligned_v2_val_indices_tcr_ab_split_3
(68763, 50)
smart_aligned_v2_test_indices_random_split_5
(64657, 50)
smart_aligned_v2_test_indices_tcr_ab_split_4
(94764, 10)
smart_aligned_v2_train_indices_tcr_ab_split_2
(281636, 10)
smart_aligned_v2_val_indices_tcr_split_1
(69629, 10)
smart_aligned_v2_val_indices_tcr_split_3
(68945, 50)
smart_aligned_v2_test_indices_tcr_split_5
(78883, 50)
smart_aligned_v2_val_indices_tcr_split_2
(70851, 10)
smart_aligned_v2_test_indices_tcr_ab_split_5
(84735, 50)

In [ ]:
import mvtcr.utils_training as utils

In [ ]:
utils.load_model(gene_TCR_integration, path_model)

In [ ]:
for i in ls_index[1:2]:
    if i.endswith('.npy'): 
        data_ix = np.load(os.path.join('./5 to 1 Indices', i), allow_pickle=True)
        ref_dat_index = ref_dat.iloc[data_ix]
        gene_TCR_integration = gene_TCR[ref_dat_index['tcr_source_index'].values].copy()
        for best_model in ['trial_0']:           
            path_model = f'./mvTCR_integration_res_5_to_1/saved_models/{i.split(".")[0]}/10X_mvTCR_embedding_cluster/{best_model}/best_model_by_reconstruction.pt'
            model = utils.load_model(gene_TCR_integration, path_model)
            print(best_model)
            print(i)
            mvTCR_integration_latent = model.get_latent(gene_TCR_integration, metadata=[], return_mean=False).X
            print(mvTCR_integration_latent.shape)

In [ ]:
# for i in ls_index[3:4]:
#     if i.endswith('.npy'): 
#         data_ix = np.load(os.path.join('./5 to 1 Indices', i), allow_pickle=True)
#         ref_dat_index = ref_dat.iloc[data_ix]
#         gene_TCR_integration = gene_TCR[ref_dat_index['tcr_source_index'].values].copy()
#         for best_model in ['trial_0', 'trial_1','trial_2', 'trial_3','trial_4']:           
#             path_model = f'./mvTCR_integration_res_5_to_1/saved_models/{i.split(".")[0]}/10X_mvTCR_embedding_cluster/{best_model}/best_model_by_reconstruction.pt'
#             model = utils.load_model(gene_TCR_integration, path_model)
#             print(best_model)
#             print(i)
#             mvTCR_integration_latent = model.get_latent(gene_TCR_integration, metadata=[], return_mean=False).X
#             print(mvTCR_integration_latent.shape)

In [18]:
for i in ls_index:
    if i.endswith('.npy'): 
        data_ix = np.load(os.path.join('./5 to 1 Indices', i), allow_pickle=True)
        ref_dat_index = ref_dat.iloc[data_ix]
        gene_TCR_integration = gene_TCR[ref_dat_index['tcr_source_index'].values].copy()
        for best_model in ['trial_0']:           
            path_model = f'./mvTCR_integration_res/saved_models/{i.split(".")[0]}/10X_mvTCR_embedding_cluster/{best_model}/best_model_by_reconstruction.pt'
            model = utils.load_model(gene_TCR_integration, path_model)
            print(best_model)
            print(i)
            mvTCR_integration_latent = model.get_latent(gene_TCR_integration, metadata=[], return_mean=False).X
            print(mvTCR_integration_latent.shape)
            pd.DataFrame(mvTCR_integration_latent).to_csv(f"./mvTCR_integration_res_5_to_1_new/10X_mvTCR_embedding_integration_latent_best_reconstruction_metric_{i.split('.')[0]}.csv", index=False)

trial_0
smart_aligned_v2_train_indices_random_split_2.npy
(301732, 50)
trial_0
smart_aligned_v2_train_indices_random_split_4.npy
(301732, 50)
trial_0
smart_aligned_v2_train_indices_tcr_split_4.npy
(283032, 50)
trial_0
smart_aligned_v2_test_indices_tcr_ab_split_1.npy
(79602, 50)
trial_0
smart_aligned_v2_test_indices_random_split_2.npy
(64657, 50)
trial_0
smart_aligned_v2_train_indices_tcr_split_3.npy
(275780, 50)
trial_0
smart_aligned_v2_train_indices_tcr_ab_split_5.npy
(277048, 50)
trial_0
smart_aligned_v2_val_indices_tcr_split_4.npy
(70758, 50)
trial_0
smart_aligned_v2_train_indices_tcr_split_1.npy
(278515, 50)
trial_0
smart_aligned_v2_test_indices_random_split_3.npy
(64657, 50)
trial_0
smart_aligned_v2_test_indices_tcr_ab_split_3.npy
(87232, 50)
trial_0
smart_aligned_v2_val_indices_tcr_split_5.npy
(70433, 50)
trial_0
smart_aligned_v2_val_indices_tcr_ab_split_1.npy
(70289, 50)
trial_0
smart_aligned_v2_train_indices_random_split_1.npy
(301732, 50)
trial_0
smart_aligned_v2_val_indices_random_split_1.npy
(64657, 50)
trial_0
smart_aligned_v2_val_indices_random_split_3.npy
(64657, 50)
trial_0
smart_aligned_v2_test_indices_tcr_split_3.npy
(86321, 50)
trial_0
smart_aligned_v2_val_indices_tcr_ab_split_4.npy
(67257, 50)
trial_0
smart_aligned_v2_val_indices_tcr_ab_split_5.npy
(69263, 50)
trial_0
smart_aligned_v2_train_indices_random_split_3.npy
(301732, 50)
trial_0
smart_aligned_v2_val_indices_random_split_4.npy
(64657, 50)
trial_0
smart_aligned_v2_train_indices_tcr_ab_split_1.npy
(281155, 50)
trial_0
smart_aligned_v2_test_indices_tcr_split_1.npy
(82902, 50)
trial_0
smart_aligned_v2_train_indices_tcr_split_2.npy
(283400, 50)
trial_0
smart_aligned_v2_train_indices_tcr_ab_split_4.npy
(269025, 50)
trial_0
smart_aligned_v2_val_indices_tcr_ab_split_2.npy
(70409, 50)
trial_0
smart_aligned_v2_test_indices_random_split_4.npy
(64657, 50)
trial_0
smart_aligned_v2_train_indices_tcr_ab_split_3.npy
(275051, 50)
trial_0
smart_aligned_v2_val_indices_random_split_5.npy
(64657, 50)
trial_0
smart_aligned_v2_test_indices_tcr_split_2.npy
(76795, 50)
trial_0
smart_aligned_v2_val_indices_random_split_2.npy
(64657, 50)
trial_0
smart_aligned_v2_train_indices_random_split_5.npy
(301732, 50)
trial_0
smart_aligned_v2_test_indices_tcr_ab_split_2.npy
(79001, 50)
trial_0
smart_aligned_v2_train_indices_tcr_split_5.npy
(281730, 50)
trial_0
smart_aligned_v2_test_indices_tcr_split_4.npy
(77256, 50)
trial_0
smart_aligned_v2_test_indices_random_split_1.npy
(64657, 50)
trial_0
smart_aligned_v2_val_indices_tcr_ab_split_3.npy
(68763, 50)
trial_0
smart_aligned_v2_test_indices_random_split_5.npy
(64657, 50)
trial_0
smart_aligned_v2_test_indices_tcr_ab_split_4.npy
(94764, 50)
trial_0
smart_aligned_v2_train_indices_tcr_ab_split_2.npy
(281636, 50)
trial_0
smart_aligned_v2_val_indices_tcr_split_1.npy
(69629, 50)
trial_0
smart_aligned_v2_val_indices_tcr_split_3.npy
(68945, 50)
trial_0
smart_aligned_v2_test_indices_tcr_split_5.npy
(78883, 50)
trial_0
smart_aligned_v2_val_indices_tcr_split_2.npy
(70851, 50)
trial_0
smart_aligned_v2_test_indices_tcr_ab_split_5.npy
(84735, 50)

In [ ]:
for i in ls_index:
    if i.endswith('.npy') and ("indices_tcr_split_5" in i): 
        data_ix = np.load(os.path.join('./3 to 1 Indices', i), allow_pickle=True)
        ref_dat_index = ref_dat.iloc[data_ix]
        gene_TCR_integration = gene_TCR[ref_dat_index['tcr_source_index'].values].copy()
        for best_model in ['trial_4']:           
            path_model = f'./mvTCR_integration_res/saved_models/{i.split(".")[0]}/10X_mvTCR_embedding_cluster/{best_model}/best_model_by_reconstruction.pt'
            model = utils.load_model(gene_TCR_integration, path_model)
            print(best_model)
            print(i)
            mvTCR_integration_latent = model.get_latent(gene_TCR_integration, metadata=[], return_mean=False).X
            print(mvTCR_integration_latent.shape)
            print(data_ix.shape)

In [20]:
ls_index = os.listdir('./5 to 1 Indices')
ls_index
for i in ls_index:
    if i.endswith('.npy'): 
        data_ix = np.load(os.path.join('./5 to 1 Indices', i), allow_pickle=True)
        ref_dat_index = ref_dat.iloc[data_ix]
        # gene_TCR_integration = gene_TCR[ref_dat_index['tcr_source_index'].values].copy()
        check = pd.read_csv(f"./mvTCR_integration_res_5_to_1_new/10X_mvTCR_embedding_integration_latent_best_reconstruction_metric_{i.split('.')[0]}.csv")
        print(check.shape[0] == data_ix.shape[0])
        print(i)
        # print()

True
smart_aligned_v2_train_indices_random_split_2.npy
True
smart_aligned_v2_train_indices_random_split_4.npy
True
smart_aligned_v2_train_indices_tcr_split_4.npy
True
smart_aligned_v2_test_indices_tcr_ab_split_1.npy
True
smart_aligned_v2_test_indices_random_split_2.npy
True
smart_aligned_v2_train_indices_tcr_split_3.npy
True
smart_aligned_v2_train_indices_tcr_ab_split_5.npy
True
smart_aligned_v2_val_indices_tcr_split_4.npy
True
smart_aligned_v2_train_indices_tcr_split_1.npy
True
smart_aligned_v2_test_indices_random_split_3.npy
True
smart_aligned_v2_test_indices_tcr_ab_split_3.npy
True
smart_aligned_v2_val_indices_tcr_split_5.npy
True
smart_aligned_v2_val_indices_tcr_ab_split_1.npy
True
smart_aligned_v2_train_indices_random_split_1.npy
True
smart_aligned_v2_val_indices_random_split_1.npy
True
smart_aligned_v2_val_indices_random_split_3.npy
True
smart_aligned_v2_test_indices_tcr_split_3.npy
True
smart_aligned_v2_val_indices_tcr_ab_split_4.npy
True
smart_aligned_v2_val_indices_tcr_ab_split_5.npy
True
smart_aligned_v2_train_indices_random_split_3.npy
True
smart_aligned_v2_val_indices_random_split_4.npy
True
smart_aligned_v2_train_indices_tcr_ab_split_1.npy
True
smart_aligned_v2_test_indices_tcr_split_1.npy
True
smart_aligned_v2_train_indices_tcr_split_2.npy
True
smart_aligned_v2_train_indices_tcr_ab_split_4.npy
True
smart_aligned_v2_val_indices_tcr_ab_split_2.npy
True
smart_aligned_v2_test_indices_random_split_4.npy
True
smart_aligned_v2_train_indices_tcr_ab_split_3.npy
True
smart_aligned_v2_val_indices_random_split_5.npy
True
smart_aligned_v2_test_indices_tcr_split_2.npy
True
smart_aligned_v2_val_indices_random_split_2.npy
True
smart_aligned_v2_train_indices_random_split_5.npy
True
smart_aligned_v2_test_indices_tcr_ab_split_2.npy
True
smart_aligned_v2_train_indices_tcr_split_5.npy
True
smart_aligned_v2_test_indices_tcr_split_4.npy
True
smart_aligned_v2_test_indices_random_split_1.npy
True
smart_aligned_v2_val_indices_tcr_ab_split_3.npy
True
smart_aligned_v2_test_indices_random_split_5.npy
True
smart_aligned_v2_test_indices_tcr_ab_split_4.npy
True
smart_aligned_v2_train_indices_tcr_ab_split_2.npy
True
smart_aligned_v2_val_indices_tcr_split_1.npy
True
smart_aligned_v2_val_indices_tcr_split_3.npy
True
smart_aligned_v2_test_indices_tcr_split_5.npy
True
smart_aligned_v2_val_indices_tcr_split_2.npy
True
smart_aligned_v2_test_indices_tcr_ab_split_5.npy

10X_mvTCR_embedding_integration_latent_best_reconstruction_metric_smart_aligned_v2_train_indices_tcr_split_5
Should be (191806, 45)

In [ ]:
gene_TCR[ref_dat_index['tcr_source_index'].values]