In [1]:
import scanpy.external as sce
import scanpy as sc

In [2]:
Apexigen = sc.read_h5ad('./Apexigen_data/Apexigen_gene_TCR_annotated_for_integration_real_case.h5ad')
Apexigen

AnnData object with n_obs × n_vars = 16286 × 15827
    obs: 'batch', 'n_counts', 'n_genes', 'outcome', 'patient', 'response', 'sample', 'timepoint', 'log_counts', 'mt_frac', 'scvi_r1', 'cell_class', 'cell_type', 'cell_type_scvi', 'cell_class_scvi', 'TRB_cdr3', 'TRA_cdr3'
    obsm: 'X_umap'
    layers: 'counts'

In [3]:
Apexigen.obsm['X_umap'].shape

(16286, 2)

In [4]:
del Apexigen.obsm['X_umap']

In [5]:
Apexigen

AnnData object with n_obs × n_vars = 16286 × 15827
    obs: 'batch', 'n_counts', 'n_genes', 'outcome', 'patient', 'response', 'sample', 'timepoint', 'log_counts', 'mt_frac', 'scvi_r1', 'cell_class', 'cell_type', 'cell_type_scvi', 'cell_class_scvi', 'TRB_cdr3', 'TRA_cdr3'
    layers: 'counts'

In [6]:
Apexigen.obs

,batch,n_counts,n_genes,outcome,patient,response,sample,timepoint,log_counts,mt_frac,scvi_r1,cell_class,cell_type,cell_type_scvi,cell_class_scvi,TRB_cdr3,TRA_cdr3
AAACCTGAGGCGCTCT-1-4,4,1756.0,627,PD,05,pathCR,05_post,post_CD40,7.470794,0.032460,3,CD4T_naive,CD4T_naive3,CD4T_naive2,CD4T_naive,CASSVATAGGIGYTF,CAMREGWNTGTASKLTF
AAACCTGCATGCCACG-1-4,4,1787.0,707,PD,05,pathCR,05_post,post_CD40,7.488294,0.029659,2,CD4T_naive,CD4T_naive1,CD4T_naive1,CD4T_naive,CASSLGGVNTGELFF,CAASTGNDMRF
AAACCTGTCTCCTATA-1-6,6,1825.0,864,HD,HD_01,HD,HD_03,nan,7.509336,0.055342,3,CD4T_naive,CD4T_naive2,CD4T_naive2,CD4T_naive,CASSQGGLGLGGAVQPQHF,CAAGSGATNKLIF
AAACGGGAGGGATACC-1-8,8,974.0,470,PD,01,nopathCR,01_LTF2,follow_up,6.881412,0.075975,0,CD8T,CD8T_GrH1,CD8_GrH,CD8_T,CASSRLAEVNEQFF,CAESRSGGSYIPTF
AAACGGGCATCGGAAG-1-3,3,2800.0,865,PD,04,pathCR,04_surgery,surgery,7.937375,0.024286,7,CD4T_naive,CD4T_naive3,CD4T_naive3,CD4T_naive,CASSAGGARVSYEQYF,CAVFSGSRLTF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTCCTCCACTCGACG-1_05_post,0,4706.0,1357,PD,05,pathCR,05_post,post_CD40,8.456594,0.000000,1,CD4_Tcell,CD4T_naive,CD4_Tnaive1,CD4_T,CASSLDSYGYTF,CAVNMDRGSTLGRLYF
TTTGCGCGTGTGCCTG-1_05_post,0,2891.0,1380,PD,05,pathCR,05_post,post_CD40,7.969358,0.000000,3,CD8_Tcell,CD8T_GrK,CD8T_GrH,CD8_T,CASSLSYSEETQYF,CLVGERGSTLGRLYF
TTTGGTTCACCAGCAC-1_05_post,0,3474.0,1338,PD,05,pathCR,05_post,post_CD40,8.153062,0.000000,1,CD4_Tcell,CD4T_naive,CD4_Tnaive1,CD4_T,CASTQNGGDTQYF,CAVTLGGSYIPTF
TTTGGTTGTTCTGGTA-1_05_post,0,4632.0,1231,PD,05,pathCR,05_post,post_CD40,8.440744,0.000000,1,CD4_Tcell,CD4T_naive,CD4_Tnaive1,CD4_T,CASSNVRRSRDSPLHF,CAIRDGGAQKLVF
TTTGTCATCTGTTGAG-1_05_post,0,3331.0,1533,PD,05,pathCR,05_post,post_CD40,8.111028,0.000000,4,CD8_Tcell,CD8T_GrH,CD8T_GrB,CD8_T,CAWSVAGEGYTF,CAVPQTGANNLFF

In [9]:
sc.pp.highly_variable_genes(Apexigen, n_top_genes=2000)

/opt/homebrew/Caskroom/miniforge/base/envs/bioinformatics/lib/python3.9/site-packages/scanpy/preprocessing/_highly_variable_genes.py:216: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  disp_grouped = df.groupby('mean_bin')['dispersions']

In [10]:
Apexigen = Apexigen[:, Apexigen.var['highly_variable']]
Apexigen

View of AnnData object with n_obs × n_vars = 16286 × 2000
    obs: 'batch', 'n_counts', 'n_genes', 'outcome', 'patient', 'response', 'sample', 'timepoint', 'log_counts', 'mt_frac', 'scvi_r1', 'cell_class', 'cell_type', 'cell_type_scvi', 'cell_class_scvi', 'TRB_cdr3', 'TRA_cdr3'
    var: 'highly_variable', 'means', 'dispersions', 'dispersions_norm'
    uns: 'hvg'
    layers: 'counts'

In [11]:
sc.tl.pca(Apexigen, svd_solver='arpack')

In [11]:
Apexigen.obsm['X_pca'].shape

(16286, 50)

In [12]:
sc.external.pp.harmony_integrate(Apexigen, key='sample')

2026-01-19 11:08:45,869 - harmonypy - INFO - Computing initial centroids with sklearn.KMeans...
2026-01-19 11:08:50,358 - harmonypy - INFO - sklearn.KMeans initialization complete.
2026-01-19 11:08:50,396 - harmonypy - INFO - Iteration 1 of 10
2026-01-19 11:08:52,959 - harmonypy - INFO - Iteration 2 of 10
2026-01-19 11:08:55,602 - harmonypy - INFO - Iteration 3 of 10
2026-01-19 11:08:58,131 - harmonypy - INFO - Converged after 3 iterations

In [13]:
"X_pca_harmony" in Apexigen.obsm

True

In [15]:
import pandas as pd
pd.DataFrame(Apexigen.obsm['X_pca_harmony'])

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,-6.881746,-2.083833,-1.772055,-2.163732,-0.196292,0.254778,1.342183,-0.209563,0.088161,-0.128326,...,-2.789922,-0.331818,-0.281279,-1.292873,-1.512227,0.101204,-0.161070,-2.778829,0.469247,0.702207
1,-5.987329,0.200454,-6.547071,-0.401403,1.756419,0.022617,-1.232259,-0.810778,0.701651,-0.524196,...,0.206114,-0.209252,1.265524,-0.662786,-0.217794,-0.265044,0.093234,0.051101,-0.329304,1.559872
2,-7.623386,-1.918656,-0.780414,-1.247954,0.386133,-0.610372,0.632555,-0.643552,-2.008352,1.423668,...,-0.196193,0.292483,0.063412,-0.383630,-1.428634,0.131068,-0.492175,-2.446496,-1.858377,0.132560
3,-0.026194,-3.715467,-4.305068,3.462837,-4.314681,-2.651175,0.067919,-1.793121,1.634910,3.021374,...,0.269363,-0.173161,0.831411,-0.584656,-0.406464,-0.398118,0.059843,1.047233,-0.555673,-0.046356
4,-7.379850,-2.785322,-0.191137,-0.022922,0.683002,-0.028434,-1.310539,-0.586790,-1.602298,-0.933357,...,0.363644,0.549016,-0.848511,-0.739649,1.737968,0.232321,-1.369484,-2.201268,-0.079303,0.271009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16281,-9.064439,-2.631013,0.769345,0.010068,2.720746,2.095491,-1.395214,2.000051,0.115719,-0.690213,...,0.035263,-0.967383,-0.696547,0.525758,-0.363050,-0.636418,-0.712255,-0.146139,-0.411492,-1.146555
16282,6.521365,-0.165974,-0.623430,-0.543515,0.933362,5.635499,0.444258,1.345031,1.967603,1.285462,...,0.154532,-0.066587,0.675258,-0.319988,0.031488,0.883003,-1.666731,-0.231611,-0.087637,-1.807345
16283,-6.339083,-0.097388,4.259745,1.596809,-0.821369,-0.324184,0.707006,2.166697,-0.259932,1.045749,...,0.776139,0.889372,1.238427,-0.576193,0.459552,0.708182,-1.963651,-0.248910,-1.784720,-0.680893
16284,-6.771970,-2.764996,1.830845,-1.799969,2.235535,1.796908,-1.050171,0.622538,-2.479770,-2.399225,...,1.458113,1.239276,1.461401,0.814084,1.051313,-0.657688,-0.142874,0.801391,-1.019663,-1.103665
16285,4.110097,-2.172076,1.102526,0.460462,-1.868850,-0.118093,-0.472873,2.827628,-2.398038,-0.248584,...,0.395434,0.100371,0.832754,-1.306583,-1.623789,-0.525017,-0.874924,0.727993,0.679810,-0.018867

In [16]:
pd.DataFrame(Apexigen.obsm['X_pca_harmony']).to_csv('./data/Apexigen_data_pca_harmony_batch_correction_by_sample_embeddings.csv')