In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import json
import time
from pathlib import Path
from typing import Dict, Tuple, Optional, Union, Any, List
import warnings
import scanpy as sc
warnings.filterwarnings('ignore')

# Import additional libraries for neural network training
from sklearn.model_selection import train_test_split, StratifiedKFold, GroupShuffleSplit
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, average_precision_score
from sklearn.metrics import precision_recall_curve, roc_curve, roc_auc_score, average_precision_score, recall_score
from sklearn.utils.class_weight import compute_class_weight

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import (
    Dense, Dropout, BatchNormalization, Input, Add, Activation, 
    MultiHeadAttention, LayerNormalization, Reshape, Flatten,
    GlobalAveragePooling1D, Embedding
)
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint, LearningRateScheduler
from tensorflow.keras.regularizers import l1_l2
from tensorflow.keras import backend as K
from sklearn.ensemble import RandomForestClassifier

# PE + AE TCR

In [2]:
atchley = pd.read_csv("../data/atchley.txt", sep="\t")
# atchley['avg'] = atchley[['f1','f2','f3','f4','f5']] .sum(axis=0)
atchley
index_aa_converter = pd.DataFrame({"aa":atchley['amino.acid'].values, "pos": list(range(20))})

index_aa_converter.index = index_aa_converter['aa'].values
index_aa_converter.pop("aa")
index_aa_converter
atchley.pop('amino.acid')
atchley

cols = atchley.columns
cols
for col in cols:
    atchley[col] =  pd.to_numeric(atchley[col].str.replace("−", "-"), errors='coerce')
atchley['avg'] = atchley.sum(axis=1)
atchley
atchley_aa = pd.concat([index_aa_converter.reset_index(), atchley], axis=1)
atchley_aa
atchley_amino_prop = pd.concat([pd.DataFrame([[0]*atchley_aa.shape[1]],columns=atchley_aa.columns),atchley_aa], axis=0)
atchley_amino_prop
atchley_aa = atchley_amino_prop
atchley_aa.iloc[0,0]='*'
atchley_aa
# word_vectors = np.array(atchley_amino_prop)
word_vectors = np.array(atchley_amino_prop.iloc[:,2:8])
word_vectors.shape

(21, 6)

In [3]:
# We use aa that has length of at most 50
def get_atchley(receptor_seq, length = 35):
    res_atchley = np.zeros((length), dtype='int')
    # print(len(receptor_seq))
    if (len(receptor_seq) <= length):
        for l in range(len(receptor_seq)):
            # print(receptor_seq[l])
            if receptor_seq[l] in index_aa_converter.index:
                res_atchley[l] = 1+index_aa_converter.loc[receptor_seq[l]].values[0]
            else:
                res_atchley[l] = np.random.randint(0,20)
            # res_atchley[l,:] =  atchley.loc[index_aa_converter.loc[receptor_seq[l]].values[0]].values #atchley.loc[receptor_seq[l]]
            # res_atchley = res_atchley.append(atchley.loc[s])
    else:
        for l in range(length):
            # print(receptor_seq[l])
            if receptor_seq[l] in index_aa_converter.index:
                # print(index_aa_converter.loc[receptor_seq[l]].values[0])
                res_atchley[l] = 1+index_aa_converter.loc[receptor_seq[l]].values[0]
            else:
                res_atchley[l] = np.random.randint(0,20)
            # res_atchley[l,:] =  atchley.loc[index_aa_converter.loc[receptor_seq[l]].values[0]].values #atchley.loc[receptor_seq[l]]
            # res_atchley = res_atchley.append(atchley.loc[s])
    return res_atchley

In [4]:
# The input of AAEmbedding is the vectorization of amino acid sequence, i.e., the order of each amino acid letter base in the 
# list of 20 amino acid, we can obtain the input by using get_atchley function
class AAEmbedding(tf.keras.layers.Layer):
    def __init__(self, word_vectors):
        super(AAEmbedding, self).__init__()
        self.word_vectors = tf.constant(word_vectors, dtype=tf.float32)

    def call(self, inputs):
        embedded_inputs = tf.nn.embedding_lookup(self.word_vectors, inputs)
        return embedded_inputs

In [5]:
def positional_encoding(depth, length=25):
  depth = depth
  # print(depth)
  positions = np.arange(length)[:, np.newaxis]   
  positions = np.repeat(positions, depth, axis=1)
  # print(np.repeat(positions, 6, axis=1))
  # print(positions)  # (seq, 1)
  # depths = np.arange(depth)[np.newaxis, :]/depth   # (1, depth)
  # print(depths.shape)
  angle_rates = 1 / (1000)         # (1, depth)
  angle_rads = positions * angle_rates      # (pos, depth)
  # print("Angle radian", angle_rads.shape)
  s = np.sin(angle_rads)[::2]
  c = 1- np.cos(angle_rads)[1::2]
  # print(s)
  # print(c)

  # pos_encoding = np.concatenate(
  #     [np.sin(angle_rads), np.cos(angle_rads)],
  #     axis=-1) 
  pos_encoding = np.vstack(
      [s, c]) 
  return tf.cast(pos_encoding, dtype=tf.float32)

In [6]:
class PositionalEmbedding(tf.keras.layers.Layer):
  def __init__(self, d_model, word_vectors,length = 25):
    super().__init__()
    self.d_model = d_model
    self.length = length
    # self.embedding = tf.keras.layers.Embedding(vocab_size, d_model, mask_zero=True) 
    self.embedding = AAEmbedding(word_vectors)
    self.pos_encoding = positional_encoding(depth=d_model, length=length)

  def compute_mask(self, *args, **kwargs):
    return self.embedding.compute_mask(*args, **kwargs)

  def call(self, x):
    # length = tf.shape(x)[1]

    # print("PositionalEmbedding input shape", x)
    x = self.embedding(x)
    # print(f"beginning x shape {x.shape}")
    # This factor sets the relative scale of the embedding and positonal_encoding.
    x *= tf.math.sqrt(tf.cast(self.d_model, tf.float32))
    # print('self position encoding value',self.pos_encoding[tf.newaxis, :50, :].shape)
    # print("x value before last line PositionEmbedding",x.shape)
    # scale = tf.cast(x != 0, tf.float32)
    # print(self.pos_encoding[tf.newaxis, :25, :])
    # print(scale.shape)
    # po = self.pos_encoding[tf.newaxis, :25, :]
    # scale = tf.reshape(scale,po.shape)
    # print(po.shape)
    # x = x + tf.multiply(self.pos_encoding[tf.newaxis, :25, :],scale)
    x = x + self.pos_encoding[tf.newaxis, :self.length, :]
    # print("Finish Positional Embedding")
    return x

In [7]:
d_model = 6
pt = PositionalEmbedding(d_model=d_model,word_vectors=word_vectors,length=15)

In [8]:
AA_embed = AAEmbedding(word_vectors)
AA_eem = AA_embed(get_atchley("CASSLGTDTQYF"))
# pt(get_atchley("CASSLGTDTQYF"))

# Donor Split

We just finished doing Autoencoder from PE for TCR

# We do the same for TCR split for AE

In [9]:
# CAP-1 (CEA 571–579), YLSGANLNL
# CAP-1-6D (Modified CAP-1), YLSGADLNL
# CEA-553, QYSWFVNGTF
# CEA-694 (WT), GVLVGVALI
# CEA-694 (L2), GLLVGVALI
# CEA-694 (V9), GLLVGVALV
# CEA-694 (L2V9), GLLVGVALV 
# Identified as a peptide for HLA-A*2402, TYACFVSNL
# CEA.24, LLTFWNPPTTAKLTI
# CEA.33, TAKLTIESTPFNVAE
# CEA.50, EVLLLVHNLPQHLFG

In [23]:
IEDB_tumor_epitope = pd.read_csv("All_epitope_IEDB_McPAS_VDJdb.csv", index_col=0)

In [24]:
IEDB_tumor_epitope

          Epitope
1       SLLMWITQC
2       AAGIGILTV
4      ELAGIGILTV
5       YLEPGPVTV
6       YLEPGAVTA
...           ...
40071   QLCDVMFYL
40072   YLYDRLLRV
40073   LYPEFIASI
40074   MLIGIPVYV
40075  KLYGLDWAEL

[1147 rows x 1 columns]

In [26]:

train_raw_data = IEDB_tumor_epitope.copy()

In [27]:
train_raw_data[['Epitope']].drop_duplicates()

          Epitope
1       SLLMWITQC
2       AAGIGILTV
4      ELAGIGILTV
5       YLEPGPVTV
6       YLEPGAVTA
...           ...
40071   QLCDVMFYL
40072   YLYDRLLRV
40073   LYPEFIASI
40074   MLIGIPVYV
40075  KLYGLDWAEL

[1147 rows x 1 columns]

In [28]:

train_peptide = pd.DataFrame()
for s in train_raw_data.Epitope.values:
    train_peptide = pd.concat([train_peptide, pd.DataFrame(pt(get_atchley(s, length=15)).numpy().reshape(1,15*d_model))], axis=0)
# train_TCR.to_csv("train_TCR_PE_only_no_AE_random_split_1.csv", index=False)
# train_TCR.to_csv("train_TCR_PE_only_no_AE_tcr_split_1.csv", index=False)
train_peptide.to_csv(f"train_peptide_PE_only_no_AE_all_peptide_IEDB_McPAS_VDJdb.csv", index=False)
train_peptide = pd.read_csv(f"train_peptide_PE_only_no_AE_all_peptide_IEDB_McPAS_VDJdb.csv")
latent_dim = 50
input_dim = train_peptide.shape[1]
# Encoder
inp = keras.Input(shape=(input_dim,), name='encoder_input')
x = keras.layers.Dense(164)(inp)
x = keras.layers.BatchNormalization()(x)
latent = keras.layers.Dense(latent_dim, name="latent", activation="relu")(x)

# Decoder
x = keras.layers.Dense(164)(latent)
x = keras.layers.BatchNormalization()(x)
out = keras.layers.Dense(input_dim, activation="linear", name='decoder_output')(x) # Linear activation for reconstruction

In [29]:
# Model
model_random_split = keras.Model(inputs=inp, outputs=out, name="peptide_autoencoder")
model_random_split.compile(optimizer=keras.optimizers.Adam(1e-3), loss="mse")
model_random_split.fit(train_peptide, train_peptide, epochs=200, batch_size=64, validation_data=(train_peptide, train_peptide))
model_random_split.save_weights(f'./smart_aligned_v2_peptide_AE_PE_only_no_AE_all_peptide_IEDB_McPAS_VDJdb.h5')
latent_model = keras.Model(model_random_split.input, model_random_split.get_layer("latent").output)
embeddings_peptide_PE = latent_model.predict(train_peptide, batch_size=256)
np.save(f"train_peptide_with_PE_and_AE_embeddings_all_peptide_IEDB_McPAS_VDJdb.npy", embeddings_peptide_PE)

Epoch 1/200
18/18 [==============================] - 0s 5ms/step - loss: 12.7616 - val_loss: 9.7629
Epoch 2/200
18/18 [==============================] - 0s 2ms/step - loss: 8.8053 - val_loss: 7.1551
Epoch 3/200
18/18 [==============================] - 0s 2ms/step - loss: 6.7241 - val_loss: 5.8131
Epoch 4/200
18/18 [==============================] - 0s 2ms/step - loss: 5.3617 - val_loss: 4.8298
Epoch 5/200
18/18 [==============================] - 0s 2ms/step - loss: 4.4074 - val_loss: 4.0727
Epoch 6/200
18/18 [==============================] - 0s 2ms/step - loss: 3.7150 - val_loss: 3.4598
Epoch 7/200
18/18 [==============================] - 0s 2ms/step - loss: 3.2023 - val_loss: 2.9559
Epoch 8/200
18/18 [==============================] - 0s 3ms/step - loss: 2.8498 - val_loss: 2.5538
Epoch 9/200
18/18 [==============================] - 0s 2ms/step - loss: 2.5412 - val_loss: 2.2751
Epoch 10/200
18/18 [==============================] - 0s 2ms/step - loss: 2.3243 - val_loss: 2.0468
Epoch 11/200
18/18 [==============================] - 0s 2ms/step - loss: 2.1059 - val_loss: 1.8625
Epoch 12/200
18/18 [==============================] - 0s 2ms/step - loss: 1.9317 - val_loss: 1.7071
Epoch 13/200
18/18 [==============================] - 0s 2ms/step - loss: 1.7613 - val_loss: 1.5881
Epoch 14/200
18/18 [==============================] - 0s 2ms/step - loss: 1.6445 - val_loss: 1.4798
Epoch 15/200
18/18 [==============================] - 0s 2ms/step - loss: 1.4892 - val_loss: 1.3991
Epoch 16/200
18/18 [==============================] - 0s 2ms/step - loss: 1.3486 - val_loss: 1.3073
Epoch 17/200
18/18 [==============================] - 0s 2ms/step - loss: 1.2207 - val_loss: 1.2587
Epoch 18/200
18/18 [==============================] - 0s 2ms/step - loss: 1.1601 - val_loss: 1.1200
Epoch 19/200
18/18 [==============================] - 0s 2ms/step - loss: 1.0426 - val_loss: 1.0374
Epoch 20/200
18/18 [==============================] - 0s 2ms/step - loss: 0.9715 - val_loss: 0.9026
Epoch 21/200
18/18 [==============================] - 0s 2ms/step - loss: 0.8853 - val_loss: 0.8252
Epoch 22/200
18/18 [==============================] - 0s 2ms/step - loss: 0.8533 - val_loss: 0.7241
Epoch 23/200
18/18 [==============================] - 0s 2ms/step - loss: 0.8270 - val_loss: 0.6733
Epoch 24/200
18/18 [==============================] - 0s 2ms/step - loss: 0.7866 - val_loss: 0.6106
Epoch 25/200
18/18 [==============================] - 0s 2ms/step - loss: 0.7685 - val_loss: 0.5719
Epoch 26/200
18/18 [==============================] - 0s 2ms/step - loss: 0.7108 - val_loss: 0.5572
Epoch 27/200
18/18 [==============================] - 0s 2ms/step - loss: 0.7297 - val_loss: 0.5240
Epoch 28/200
18/18 [==============================] - 0s 2ms/step - loss: 0.6818 - val_loss: 0.4998
Epoch 29/200
18/18 [==============================] - 0s 2ms/step - loss: 0.6183 - val_loss: 0.4626
Epoch 30/200
18/18 [==============================] - 0s 2ms/step - loss: 0.6779 - val_loss: 0.4278
Epoch 31/200
18/18 [==============================] - 0s 2ms/step - loss: 0.6134 - val_loss: 0.4196
Epoch 32/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5995 - val_loss: 0.3927
Epoch 33/200
18/18 [==============================] - 0s 2ms/step - loss: 0.6182 - val_loss: 0.3611
Epoch 34/200
18/18 [==============================] - 0s 2ms/step - loss: 0.6373 - val_loss: 0.3716
Epoch 35/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5317 - val_loss: 0.3519
Epoch 36/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5615 - val_loss: 0.3631
Epoch 37/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5798 - val_loss: 0.3290
Epoch 38/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5624 - val_loss: 0.3046
Epoch 39/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5667 - val_loss: 0.3039
Epoch 40/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5152 - val_loss: 0.2924
Epoch 41/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5502 - val_loss: 0.2803
Epoch 42/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5294 - val_loss: 0.2965
Epoch 43/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5452 - val_loss: 0.2786
Epoch 44/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5594 - val_loss: 0.2894
Epoch 45/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5196 - val_loss: 0.2639
Epoch 46/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5186 - val_loss: 0.2599
Epoch 47/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5377 - val_loss: 0.2468
Epoch 48/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5396 - val_loss: 0.2569
Epoch 49/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5109 - val_loss: 0.2364
Epoch 50/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5051 - val_loss: 0.2438
Epoch 51/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5304 - val_loss: 0.2488
Epoch 52/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5194 - val_loss: 0.2360
Epoch 53/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5050 - val_loss: 0.2370
Epoch 54/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5070 - val_loss: 0.2253
Epoch 55/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4765 - val_loss: 0.2309
Epoch 56/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5138 - val_loss: 0.2324
Epoch 57/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5239 - val_loss: 0.2257
Epoch 58/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4911 - val_loss: 0.2353
Epoch 59/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4892 - val_loss: 0.2313
Epoch 60/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4887 - val_loss: 0.2341
Epoch 61/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4992 - val_loss: 0.2245
Epoch 62/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4768 - val_loss: 0.2186
Epoch 63/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4552 - val_loss: 0.2331
Epoch 64/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4775 - val_loss: 0.2217
Epoch 65/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4923 - val_loss: 0.2263
Epoch 66/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4824 - val_loss: 0.2226
Epoch 67/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4395 - val_loss: 0.2169
Epoch 68/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4826 - val_loss: 0.2194
Epoch 69/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4784 - val_loss: 0.2149
Epoch 70/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4656 - val_loss: 0.2205
Epoch 71/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4832 - val_loss: 0.2079
Epoch 72/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4696 - val_loss: 0.2170
Epoch 73/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4664 - val_loss: 0.2154
Epoch 74/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4979 - val_loss: 0.2072
Epoch 75/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4805 - val_loss: 0.2114
Epoch 76/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5036 - val_loss: 0.2095
Epoch 77/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4819 - val_loss: 0.2181
Epoch 78/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4762 - val_loss: 0.2064
Epoch 79/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4692 - val_loss: 0.2155
Epoch 80/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4903 - val_loss: 0.2041
Epoch 81/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4842 - val_loss: 0.2104
Epoch 82/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4979 - val_loss: 0.2022
Epoch 83/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4524 - val_loss: 0.2081
Epoch 84/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4770 - val_loss: 0.2062
Epoch 85/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4802 - val_loss: 0.2042
Epoch 86/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4593 - val_loss: 0.2029
Epoch 87/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4645 - val_loss: 0.2109
Epoch 88/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4232 - val_loss: 0.2153
Epoch 89/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4442 - val_loss: 0.2080
Epoch 90/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4540 - val_loss: 0.2064
Epoch 91/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4681 - val_loss: 0.2086
Epoch 92/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4589 - val_loss: 0.1988
Epoch 93/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4606 - val_loss: 0.2053
Epoch 94/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4533 - val_loss: 0.2147
Epoch 95/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4410 - val_loss: 0.2136
Epoch 96/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4760 - val_loss: 0.2083
Epoch 97/200
18/18 [==============================] - 0s 2ms/step - loss: 0.5187 - val_loss: 0.2029
Epoch 98/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4463 - val_loss: 0.2144
Epoch 99/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4484 - val_loss: 0.2041
Epoch 100/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4576 - val_loss: 0.1962
Epoch 101/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4406 - val_loss: 0.2066
Epoch 102/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4421 - val_loss: 0.2029
Epoch 103/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4037 - val_loss: 0.2006
Epoch 104/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4925 - val_loss: 0.1990
Epoch 105/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4574 - val_loss: 0.2035
Epoch 106/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4280 - val_loss: 0.2068
Epoch 107/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4353 - val_loss: 0.2048
Epoch 108/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4328 - val_loss: 0.2052
Epoch 109/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4446 - val_loss: 0.2031
Epoch 110/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4515 - val_loss: 0.2007
Epoch 111/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4441 - val_loss: 0.2016
Epoch 112/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4711 - val_loss: 0.2103
Epoch 113/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4432 - val_loss: 0.2003
Epoch 114/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4773 - val_loss: 0.2023
Epoch 115/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4676 - val_loss: 0.1929
Epoch 116/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4263 - val_loss: 0.1971
Epoch 117/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4642 - val_loss: 0.1965
Epoch 118/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4420 - val_loss: 0.2024
Epoch 119/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4326 - val_loss: 0.2168
Epoch 120/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4449 - val_loss: 0.1976
Epoch 121/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4431 - val_loss: 0.1980
Epoch 122/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4253 - val_loss: 0.1987
Epoch 123/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4459 - val_loss: 0.2037
Epoch 124/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4487 - val_loss: 0.2011
Epoch 125/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4391 - val_loss: 0.1986
Epoch 126/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4599 - val_loss: 0.1966
Epoch 127/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4926 - val_loss: 0.1968
Epoch 128/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4283 - val_loss: 0.1932
Epoch 129/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4632 - val_loss: 0.1985
Epoch 130/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4617 - val_loss: 0.1987
Epoch 131/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4492 - val_loss: 0.1991
Epoch 132/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4603 - val_loss: 0.1936
Epoch 133/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4389 - val_loss: 0.1880
Epoch 134/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4760 - val_loss: 0.1987
Epoch 135/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4276 - val_loss: 0.1979
Epoch 136/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4463 - val_loss: 0.1922
Epoch 137/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3991 - val_loss: 0.2077
Epoch 138/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4429 - val_loss: 0.1990
Epoch 139/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4364 - val_loss: 0.1909
Epoch 140/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4294 - val_loss: 0.2002
Epoch 141/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4445 - val_loss: 0.1867
Epoch 142/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4196 - val_loss: 0.1899
Epoch 143/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4759 - val_loss: 0.1986
Epoch 144/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4771 - val_loss: 0.1936
Epoch 145/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4754 - val_loss: 0.2089
Epoch 146/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4377 - val_loss: 0.2033
Epoch 147/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4645 - val_loss: 0.1976
Epoch 148/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4282 - val_loss: 0.2035
Epoch 149/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4463 - val_loss: 0.2091
Epoch 150/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4096 - val_loss: 0.2011
Epoch 151/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4571 - val_loss: 0.1996
Epoch 152/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4680 - val_loss: 0.1967
Epoch 153/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4564 - val_loss: 0.1948
Epoch 154/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4280 - val_loss: 0.1948
Epoch 155/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4298 - val_loss: 0.1975
Epoch 156/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4495 - val_loss: 0.1908
Epoch 157/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4507 - val_loss: 0.1926
Epoch 158/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4377 - val_loss: 0.2021
Epoch 159/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4473 - val_loss: 0.1916
Epoch 160/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4168 - val_loss: 0.1929
Epoch 161/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3993 - val_loss: 0.1966
Epoch 162/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4399 - val_loss: 0.1907
Epoch 163/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4452 - val_loss: 0.1956
Epoch 164/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4520 - val_loss: 0.1988
Epoch 165/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4289 - val_loss: 0.1941
Epoch 166/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4229 - val_loss: 0.1960
Epoch 167/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3989 - val_loss: 0.1981
Epoch 168/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4261 - val_loss: 0.2020
Epoch 169/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4499 - val_loss: 0.1889
Epoch 170/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4048 - val_loss: 0.1957
Epoch 171/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4539 - val_loss: 0.1960
Epoch 172/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4310 - val_loss: 0.1947
Epoch 173/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4604 - val_loss: 0.2007
Epoch 174/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4095 - val_loss: 0.1980
Epoch 175/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4245 - val_loss: 0.1963
Epoch 176/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4492 - val_loss: 0.2012
Epoch 177/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4404 - val_loss: 0.1932
Epoch 178/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4639 - val_loss: 0.1989
Epoch 179/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4587 - val_loss: 0.1898
Epoch 180/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4267 - val_loss: 0.1952
Epoch 181/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4167 - val_loss: 0.1930
Epoch 182/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4751 - val_loss: 0.1990
Epoch 183/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4764 - val_loss: 0.1918
Epoch 184/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4226 - val_loss: 0.1930
Epoch 185/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4156 - val_loss: 0.2095
Epoch 186/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4171 - val_loss: 0.1925
Epoch 187/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4400 - val_loss: 0.2049
Epoch 188/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4685 - val_loss: 0.2016
Epoch 189/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4244 - val_loss: 0.1982
Epoch 190/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4238 - val_loss: 0.1922
Epoch 191/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4668 - val_loss: 0.1954
Epoch 192/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4496 - val_loss: 0.1931
Epoch 193/200
18/18 [==============================] - 0s 2ms/step - loss: 0.3961 - val_loss: 0.2003
Epoch 194/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4435 - val_loss: 0.1944
Epoch 195/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4388 - val_loss: 0.1933
Epoch 196/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4520 - val_loss: 0.1935
Epoch 197/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4288 - val_loss: 0.1909
Epoch 198/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4345 - val_loss: 0.1915
Epoch 199/200
18/18 [==============================] - 0s 2ms/step - loss: 0.4141 - val_loss: 0.1987