In this work, we use transformer model to integrate gene expression and TCR amino acid sequences

Getting gene data

In [1]:
# %matplotlib inline

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import os 
import numpy as np

import pandas as pd
# import seaborn as sb
import matplotlib.pyplot as pl

import scanpy as sc

import anndata as ad

from scipy.sparse import csr_matrix
from matplotlib import rcParams
from matplotlib import colors

sc.settings.verbosity = 3

In [2]:
gene_TCR = ad.read_h5ad('../10Xdatasets/gex_merge_log1_5000_genes_all_peptides.h5ad')
gene_TCR

/home/phile/miniconda3/envs/integration/lib/python3.9/site-packages/anndata/_core/anndata.py:1754: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

AnnData object with n_obs × n_vars = 145479 × 5000
    obs: 'v_gene_TRA', 'v_gene_TRB', 'd_gene_TRA', 'd_gene_TRB', 'j_gene_TRA', 'j_gene_TRB', 'c_gene_TRA', 'c_gene_TRB', 'cdr3_TRA', 'cdr3_TRB', 'cdr3_nt_TRA', 'cdr3_nt_TRB', 'umis_TRA', 'umis_TRB', 'donor', 'cell_clono_cdr3_aa', 'cell_clono_cdr3_nt', 'CD3', 'CD19', 'CD45RA', 'CD4', 'CD8a', 'CD14', 'CD45RO', 'CD279_PD-1', 'IgG1', 'IgG2a', 'IgG2b', 'CD127', 'CD197_CCR7', 'HLA-DR', 'A0101_VTEHDTLLY_IE-1_CMV', 'A0201_KTWGQYWQV_gp100_Cancer', 'A0201_ELAGIGILTV_MART-1_Cancer', 'A0201_CLLWSFQTSA_Tyrosinase_Cancer', 'A0201_IMDQVPFSV_gp100_Cancer', 'A0201_SLLMWITQV_NY-ESO-1_Cancer', 'A0201_KVAELVHFL_MAGE-A3_Cancer', 'A0201_KVLEYVIKV_MAGE-A1_Cancer', 'A0201_CLLGTYTQDV_Kanamycin-B-dioxygenase', 'A0201_LLDFVRFMGV_EBNA-3B_EBV', 'A0201_LLMGTLGIVC_HPV-16E7_82-91', 'A0201_CLGGLLTMV_LMP-2A_EBV', 'A0201_YLLEMLWRL_LMP1_EBV', 'A0201_FLYALALLL_LMP2A_EBV', 'A0201_GILGFVFTL_Flu-MP_Influenza', 'A0201_GLCTLVAML_BMLF1_EBV', 'A0201_NLVPMVATV_pp65_CMV', 'A0201_ILKEPVHGV_RT_HIV', 'A0201_FLASKIGRLV_Ca2-indepen-Plip-A2', 'A2402_CYTWNQMNL_WT1-(235-243)236M_Y', 'A0201_RTLNAWVKV_Gag-protein_HIV', 'A0201_KLQCVDLHV_PSA146-154', 'A0201_LLFGYPVYV_HTLV-1', 'A0201_SLFNTVATL_Gag-protein_HIV', 'A0201_SLYNTVATLY_Gag-protein_HIV', 'A0201_SLFNTVATLY_Gag-protein_HIV', 'A0201_RMFPNAPYL_WT-1', 'A0201_YLNDHLEPWI_BCL-X_Cancer', 'A0201_MLDLQPETT_16E7_HPV', 'A0301_KLGGALQAK_IE-1_CMV', 'A0301_RLRAEAQVK_EMNA-3A_EBV', 'A0301_RIAAWMATY_BCL-2L1_Cancer', 'A1101_IVTDFSVIK_EBNA-3B_EBV', 'A1101_AVFDRKSDAK_EBNA-3B_EBV', 'B3501_IPSINVHHY_pp65_CMV', 'A2402_AYAQKIFKI_IE-1_CMV', 'A2402_QYDPVAALF_pp65_CMV', 'B0702_QPRAPIRPI_EBNA-6_EBV', 'B0702_TPRVTGGGAM_pp65_CMV', 'B0702_RPPIFIRRL_EBNA-3A_EBV', 'B0702_RPHERNGFTVL_pp65_CMV', 'B0801_RAKFKQLL_BZLF1_EBV', 'B0801_ELRRKMMYM_IE-1_CMV', 'B0801_FLRGRAYGL_EBNA-3A_EBV', 'A0101_SLEGGGLGY_NC', 'A0101_STEGGGLAY_NC', 'A0201_ALIAPVHAV_NC', 'A2402_AYSSAGASI_NC', 'B0702_GPAESAAGL_NC', 'NR(B0801)_AAKGRGAAL_NC', 'antigen', 'peptide', 'orig_ix', 'n_counts', 'log_counts', 'n_genes', 'mt_fraction'
    var: 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection'
    uns: 'donor_colors', 'hvg', 'log1p'
    layers: 'raw_counts'

In [3]:
gene_TCR = gene_TCR[gene_TCR.obs.donor == 'donor4']
gene_TCR

View of AnnData object with n_obs × n_vars = 21393 × 5000
    obs: 'v_gene_TRA', 'v_gene_TRB', 'd_gene_TRA', 'd_gene_TRB', 'j_gene_TRA', 'j_gene_TRB', 'c_gene_TRA', 'c_gene_TRB', 'cdr3_TRA', 'cdr3_TRB', 'cdr3_nt_TRA', 'cdr3_nt_TRB', 'umis_TRA', 'umis_TRB', 'donor', 'cell_clono_cdr3_aa', 'cell_clono_cdr3_nt', 'CD3', 'CD19', 'CD45RA', 'CD4', 'CD8a', 'CD14', 'CD45RO', 'CD279_PD-1', 'IgG1', 'IgG2a', 'IgG2b', 'CD127', 'CD197_CCR7', 'HLA-DR', 'A0101_VTEHDTLLY_IE-1_CMV', 'A0201_KTWGQYWQV_gp100_Cancer', 'A0201_ELAGIGILTV_MART-1_Cancer', 'A0201_CLLWSFQTSA_Tyrosinase_Cancer', 'A0201_IMDQVPFSV_gp100_Cancer', 'A0201_SLLMWITQV_NY-ESO-1_Cancer', 'A0201_KVAELVHFL_MAGE-A3_Cancer', 'A0201_KVLEYVIKV_MAGE-A1_Cancer', 'A0201_CLLGTYTQDV_Kanamycin-B-dioxygenase', 'A0201_LLDFVRFMGV_EBNA-3B_EBV', 'A0201_LLMGTLGIVC_HPV-16E7_82-91', 'A0201_CLGGLLTMV_LMP-2A_EBV', 'A0201_YLLEMLWRL_LMP1_EBV', 'A0201_FLYALALLL_LMP2A_EBV', 'A0201_GILGFVFTL_Flu-MP_Influenza', 'A0201_GLCTLVAML_BMLF1_EBV', 'A0201_NLVPMVATV_pp65_CMV', 'A0201_ILKEPVHGV_RT_HIV', 'A0201_FLASKIGRLV_Ca2-indepen-Plip-A2', 'A2402_CYTWNQMNL_WT1-(235-243)236M_Y', 'A0201_RTLNAWVKV_Gag-protein_HIV', 'A0201_KLQCVDLHV_PSA146-154', 'A0201_LLFGYPVYV_HTLV-1', 'A0201_SLFNTVATL_Gag-protein_HIV', 'A0201_SLYNTVATLY_Gag-protein_HIV', 'A0201_SLFNTVATLY_Gag-protein_HIV', 'A0201_RMFPNAPYL_WT-1', 'A0201_YLNDHLEPWI_BCL-X_Cancer', 'A0201_MLDLQPETT_16E7_HPV', 'A0301_KLGGALQAK_IE-1_CMV', 'A0301_RLRAEAQVK_EMNA-3A_EBV', 'A0301_RIAAWMATY_BCL-2L1_Cancer', 'A1101_IVTDFSVIK_EBNA-3B_EBV', 'A1101_AVFDRKSDAK_EBNA-3B_EBV', 'B3501_IPSINVHHY_pp65_CMV', 'A2402_AYAQKIFKI_IE-1_CMV', 'A2402_QYDPVAALF_pp65_CMV', 'B0702_QPRAPIRPI_EBNA-6_EBV', 'B0702_TPRVTGGGAM_pp65_CMV', 'B0702_RPPIFIRRL_EBNA-3A_EBV', 'B0702_RPHERNGFTVL_pp65_CMV', 'B0801_RAKFKQLL_BZLF1_EBV', 'B0801_ELRRKMMYM_IE-1_CMV', 'B0801_FLRGRAYGL_EBNA-3A_EBV', 'A0101_SLEGGGLGY_NC', 'A0101_STEGGGLAY_NC', 'A0201_ALIAPVHAV_NC', 'A2402_AYSSAGASI_NC', 'B0702_GPAESAAGL_NC', 'NR(B0801)_AAKGRGAAL_NC', 'antigen', 'peptide', 'orig_ix', 'n_counts', 'log_counts', 'n_genes', 'mt_fraction'
    var: 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection'
    uns: 'donor_colors', 'hvg', 'log1p'
    layers: 'raw_counts'

In [4]:
gene_TCR.obs.donor

barcode
TTGGAACTCCGTCATC-8    donor4
GACGTTAAGATGTCGG-8    donor4
CGTGTAAAGGGCACTA-6    donor4
ATCCGAAGTTTGGGCC-2    donor4
CTCGAAAAGGAGTAGA-3    donor4
                       ...
GAAGCAGAGCAGGCTA-3    donor4
CAGTCCTTCATCACCC-8    donor4
GACTACACACGGTAAG-3    donor4
ATCGAGTAGTTTCCTT-4    donor4
ACCCACTTCTTGGGTA-3    donor4
Name: donor, Length: 21393, dtype: category
Categories (1, object): ['donor4']

In [5]:
gene = pd.DataFrame(gene_TCR.X.todense())
gene

,0,1,2,3,4,5,6,7,8,9,...,4990,4991,4992,4993,4994,4995,4996,4997,4998,4999
0,0.0,0.693147,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.693147,0.000000,0.0,0.0
1,0.0,0.000000,0.0,0.000000,0.0,0.0,0.693147,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,1.791759,0.693147,0.0,0.0
2,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,1.609438,0.693147,0.0,0.0
3,0.0,0.693147,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.693147,0.0,...,0.693147,0.0,0.000000,0.0,0.000000,0.0,0.693147,1.098612,0.0,0.0
4,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.693147,0.0,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,1.609438,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21388,0.0,0.693147,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0
21389,0.0,0.693147,0.0,0.693147,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,0.693147,0.0,1.791759,1.386294,0.0,0.0
21390,0.0,0.693147,0.0,0.000000,0.0,0.0,0.000000,0.693147,0.693147,0.0,...,0.000000,0.0,0.693147,0.0,0.000000,0.0,0.693147,0.693147,0.0,0.0
21391,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,1.098612,0.693147,0.0,0.0
21392,0.0,0.693147,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,1.098612,0.693147,0.0,0.0

In [6]:
tcr_seq = gene_TCR.obs[['cdr3_TRB']]
tcr_seq

                            cdr3_TRB
barcode
TTGGAACTCCGTCATC-8      CASSTGAGEQYF
GACGTTAAGATGTCGG-8    CASSLRGANNEQFF
CGTGTAAAGGGCACTA-6       CAWRGFRGYTF
ATCCGAAGTTTGGGCC-2    CATSDRLAGGELFF
CTCGAAAAGGAGTAGA-3   CASSLWTGPQETQYF
...                              ...
GAAGCAGAGCAGGCTA-3    CATSDRLAGGELFF
CAGTCCTTCATCACCC-8  CASSYLAGDFTDTQYF
GACTACACACGGTAAG-3   CASRTGLASTDTQYF
ATCGAGTAGTTTCCTT-4  CASSTTGRTNTGELFF
ACCCACTTCTTGGGTA-3  CASRVSGSLSYNEQFF

[21393 rows x 1 columns]

In [7]:
import tensorflow as tf

2026-02-26 12:26:45.061367: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-02-26 12:26:45.214961: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-02-26 12:26:45.257815: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

In [8]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Reshape, Conv2D, Conv2DTranspose, Flatten, Dropout
from tensorflow.keras.initializers import HeNormal

# Define input layer
input_gex = Input(shape=(100,))
gex = Dense(units=64, activation='relu', kernel_initializer=HeNormal())(input_gex)
gex = Reshape(target_shape=(8,8,1))(gex)

# Convolutional layers
gex = Conv2D(filters=64, kernel_size=3, strides=1, activation='relu', padding="same")(gex)
gex = Conv2D(filters=32, kernel_size=3, strides=1, activation='relu', padding="same")(gex)

gex = Flatten()(gex)
hidden_layer = Dense(units=225, activation='relu', kernel_initializer=HeNormal())(gex)

# Transposed Convolutional layers
tcr = Reshape(target_shape=(15,15,1))(hidden_layer)
tcr = Conv2DTranspose(filters=16, kernel_size=3, strides=1, activation='relu', padding="same")(tcr)
tcr = Conv2DTranspose(filters=32, kernel_size=3, strides=1, activation='relu', padding="same")(tcr)
tcr = Dropout(rate=0.2)(tcr)
tcr = Flatten()(tcr)
tcr = Dense(units=150, activation='relu', kernel_initializer=HeNormal())(tcr)
tcr = Dense(units=130, activation='relu')(tcr)  # Ensure proper activation
tcr = Dense(units=121)(tcr)
# Define model
model = Model(inputs=input_gex, outputs=tcr)
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0015),
              loss='mse')

# Check layer names
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_1 (InputLayer)        [(None, 100)]             0

 dense (Dense)               (None, 64)                6464

 reshape (Reshape)           (None, 8, 8, 1)           0

 conv2d (Conv2D)             (None, 8, 8, 64)          640

 conv2d_1 (Conv2D)           (None, 8, 8, 32)          18464

 flatten (Flatten)           (None, 2048)              0

 dense_1 (Dense)             (None, 225)               461025

 reshape_1 (Reshape)         (None, 15, 15, 1)         0

 conv2d_transpose (Conv2DTra  (None, 15, 15, 16)       160
 nspose)

 conv2d_transpose_1 (Conv2DT  (None, 15, 15, 32)       4640
 ranspose)

 dropout (Dropout)           (None, 15, 15, 32)        0

 flatten_1 (Flatten)         (None, 7200)              0

 dense_2 (Dense)             (None, 150)               1080150

 dense_3 (Dense)             (None, 130)               19630

 dense_4 (Dense)             (None, 121)               15851

=================================================================
Total params: 1,607,024
Trainable params: 1,607,024
Non-trainable params: 0
_________________________________________________________________

2026-02-26 12:26:47.009064: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-02-26 12:26:47.164987: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 18333 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:17:00.0, compute capability: 8.6

In [9]:
AE_tcr = pd.read_csv("../AE_emb_TRB_all_peptides_10X_donor_4_only.csv")
AE_tcr

,0,1,2,3,4,5,6,7,8,9,...,111,112,113,114,115,116,117,118,119,120
0,-578.545800,643.72100,19.97399,36.18518,522.106450,308.46360,-121.881230,-504.18234,-44.327106,-141.961990,...,611.465760,558.75890,-629.210700,-135.228560,-136.85368,-77.605034,-663.28406,194.074050,-332.754880,129.144600
1,-260.955440,-166.87968,-397.96503,-512.32580,-26.874681,-199.71866,50.246600,-209.96062,37.158900,16.608343,...,-269.681760,833.96840,543.433100,313.055000,-414.39044,-168.984710,743.24600,1380.880200,-28.762701,-353.440860
2,-392.291780,221.41151,230.58847,-48.90060,-467.185180,-175.72255,-417.281340,362.83102,-486.289800,-66.351900,...,14.493301,-136.76251,-15.745383,-122.987620,457.00250,-410.685500,358.23334,1665.129500,-788.868500,-644.535000
3,-512.594400,-576.57745,-841.85034,-472.11697,-47.690357,-245.14503,299.702880,-409.62897,-274.262540,191.513120,...,-605.121300,1250.64930,-388.323060,282.790900,-704.64404,37.460087,647.88403,1549.309700,352.393370,-108.645460
4,129.581150,-313.10944,268.98666,766.28190,-473.843140,979.15393,390.149500,479.94060,263.797360,-736.299740,...,-474.085820,748.01800,809.877260,-49.473446,631.27747,-380.982940,274.19620,-88.337395,-572.748600,-13.084727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21388,-512.594400,-576.57745,-841.85034,-472.11697,-47.690357,-245.14503,299.702880,-409.62897,-274.262540,191.513120,...,-605.121300,1250.64930,-388.323060,282.790900,-704.64404,37.460087,647.88403,1549.309700,352.393370,-108.645460
21389,226.274460,956.16350,176.05058,-689.92930,162.394580,608.82800,-269.477200,-744.45310,-219.842960,835.156430,...,31.987175,508.31200,-341.937840,-267.425540,-786.67950,-816.931150,291.38525,466.537630,-74.314720,-342.459840
21390,1080.433200,373.86273,-65.57250,-259.77710,35.480900,-554.94800,-441.794220,93.13524,-163.760600,155.478740,...,-251.648390,687.42700,-52.242027,-690.953370,523.99010,-314.377530,-316.33014,697.732060,40.809720,-1766.797200
21391,55.882042,-766.63635,229.29404,-177.78714,634.726900,-295.03427,92.827690,443.62744,244.667280,-787.343700,...,385.697270,895.55615,-700.939100,-126.451060,-803.60010,133.600590,-130.16379,348.644780,-400.828280,38.264300
21392,278.828000,385.64963,778.76685,-226.10637,-271.815060,803.10120,31.005762,-202.65787,319.472100,-896.443200,...,-155.597520,-415.30970,24.382822,143.311360,198.31082,802.341000,-1194.20070,1312.900300,-973.222960,-750.028000

In [10]:
import numpy as np
from sklearn.decomposition import NMF

# Generate random non-negative data
data = gene.to_numpy()

# Initialize the NMF model
n_components = 100
model_nmf = NMF(n_components=n_components, init='random', random_state=0)

# Fit the model to the data
W = model_nmf.fit_transform(data)
H = model_nmf.components_

# Display the results
print("Basis matrix (W):\n", W)
print("Coefficients matrix (H):\n", H)

/home/phile/miniconda3/envs/integration/lib/python3.9/site-packages/sklearn/decomposition/_nmf.py:1742: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(

Basis matrix (W):
 [[0.65588474 0.5470397  0.0521722  ... 0.07750414 0.         0.        ]
 [0.71132225 0.5102544  0.         ... 0.00402349 0.00669418 0.00819835]
 [0.7988329  0.69548815 0.28390643 ... 0.22728091 0.02105804 0.01490938]
 ...
 [0.90891445 0.08494315 0.67154783 ... 0.20570257 0.00487804 0.00460975]
 [0.         0.01184397 0.         ... 0.         0.00553914 0.        ]
 [0.6582172  0.22561976 0.95175385 ... 0.12736581 0.01004636 0.00202849]]
Coefficients matrix (H):
 [[0.         0.05022614 0.         ... 0.         0.         0.        ]
 [0.         0.00116642 0.         ... 0.         0.         0.        ]
 [0.         0.04755427 0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.00388899]
 [0.00337751 0.         0.         ... 0.         0.         0.00996204]
 [0.         0.         0.         ... 0.         0.         0.04406664]]

In [11]:
W = pd.DataFrame(W)
W

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.655885,0.547040,0.052172,0.302054,0.000000,0.000000,0.007344,0.008392,0.000000,0.125792,...,0.000000,0.000000,0.001850,0.009266,0.000000,0.000000,0.006932,0.077504,0.000000,0.000000
1,0.711322,0.510254,0.000000,0.254477,0.012534,0.001916,0.000647,0.000000,0.000000,0.178682,...,0.000000,0.000000,0.064455,0.010931,0.047753,0.001505,0.008079,0.004023,0.006694,0.008198
2,0.798833,0.695488,0.283906,0.526086,0.000000,0.001700,0.006966,0.000000,0.000000,0.161375,...,0.054184,0.000000,0.106702,0.000000,0.047100,0.027175,0.013801,0.227281,0.021058,0.014909
3,0.127750,0.209531,0.764994,0.085311,0.557679,0.000000,0.011223,0.011077,0.219407,0.078343,...,0.033616,0.027941,0.069957,0.028916,0.000000,0.008010,0.011309,0.078524,0.000000,0.000340
4,0.872419,0.386753,0.000000,0.542574,0.000000,0.018086,0.011532,0.006256,0.000000,0.152062,...,0.000000,0.000000,0.074202,0.007931,0.020739,0.013283,0.016447,0.076225,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21388,0.000000,0.000000,0.000000,0.000000,0.000000,0.000169,0.000171,0.029582,0.000000,0.000000,...,0.076934,0.079335,0.000333,0.027689,0.001277,0.043940,0.000069,0.003663,0.000000,0.000000
21389,0.751038,0.191501,0.000000,0.258498,0.467071,0.000000,0.012280,0.010047,0.118869,0.183304,...,0.034551,0.000000,0.000000,0.045172,0.000000,0.000000,0.000375,0.184599,0.009241,0.003461
21390,0.908914,0.084943,0.671548,0.000415,0.256613,0.001464,0.000766,0.017459,0.113861,0.169165,...,0.035153,0.052311,0.000000,0.045544,0.000000,0.029628,0.006845,0.205703,0.004878,0.004610
21391,0.000000,0.011844,0.000000,0.000000,0.100574,0.007823,0.011897,0.004592,0.026068,0.125654,...,0.033723,0.000000,0.001601,0.000000,0.033015,0.027142,0.000000,0.000000,0.005539,0.000000
21392,0.658217,0.225620,0.951754,0.096427,0.146262,0.009819,0.000000,0.011920,0.241073,0.000000,...,0.050898,0.105984,0.099951,0.029160,0.000000,0.006819,0.006976,0.127366,0.010046,0.002028

In [12]:

# es_callback = EarlyStopping(monitor= 'val_auc', patience=20, restore_best_weights=True)
reduce_learning_rate = tf.keras.callbacks.ReduceLROnPlateau(factor=0.1, patience=50, monitor='loss', min_delta=100)

history = model.fit(W,AE_tcr, 
                epochs=8000, 
                batch_size=256, 
                shuffle = True,
                # callbacks=[es_callback, checkpoint,reduce_learning_rate])
                # callbacks=[reduce_learning_rate]
                )

Epoch 1/8000

2026-02-26 12:29:04.898831: I tensorflow/stream_executor/cuda/cuda_blas.cc:1614] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
2026-02-26 12:29:05.607442: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8100
2026-02-26 12:29:06.574117: I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory

84/84 [==============================] - 3s 5ms/step - loss: 256805.4219
Epoch 2/8000
84/84 [==============================] - 0s 4ms/step - loss: 222412.6719
Epoch 3/8000
84/84 [==============================] - 0s 4ms/step - loss: 221953.0000
Epoch 4/8000
84/84 [==============================] - 0s 4ms/step - loss: 221866.1406
Epoch 5/8000
84/84 [==============================] - 0s 4ms/step - loss: 221806.9375
Epoch 6/8000
84/84 [==============================] - 0s 4ms/step - loss: 221573.5156
Epoch 7/8000
84/84 [==============================] - 0s 4ms/step - loss: 203273.8438
Epoch 8/8000
84/84 [==============================] - 0s 4ms/step - loss: 187258.6406
Epoch 9/8000
84/84 [==============================] - 0s 4ms/step - loss: 186719.3438
Epoch 10/8000
84/84 [==============================] - 0s 4ms/step - loss: 186189.1406
Epoch 11/8000
84/84 [==============================] - 0s 4ms/step - loss: 181602.5625
Epoch 12/8000
84/84 [==============================] - 0s 4ms/step - loss: 171181.9531
Epoch 13/8000
84/84 [==============================] - 0s 5ms/step - loss: 163951.3750
Epoch 14/8000
84/84 [==============================] - 0s 4ms/step - loss: 161184.9219
Epoch 15/8000
84/84 [==============================] - 0s 4ms/step - loss: 159156.7969
Epoch 16/8000
84/84 [==============================] - 0s 4ms/step - loss: 157379.6406
Epoch 17/8000
84/84 [==============================] - 0s 4ms/step - loss: 156529.1250
Epoch 18/8000
84/84 [==============================] - 0s 4ms/step - loss: 155859.9062
Epoch 19/8000
84/84 [==============================] - 0s 4ms/step - loss: 154960.5000
Epoch 20/8000
84/84 [==============================] - 0s 4ms/step - loss: 154505.5000
Epoch 21/8000
84/84 [==============================] - 0s 4ms/step - loss: 153805.8906
Epoch 22/8000
84/84 [==============================] - 0s 4ms/step - loss: 153345.6562
Epoch 23/8000
84/84 [==============================] - 0s 4ms/step - loss: 152956.8906
Epoch 24/8000
84/84 [==============================] - 0s 4ms/step - loss: 152631.0625
Epoch 25/8000
84/84 [==============================] - 0s 4ms/step - loss: 152538.2500
Epoch 26/8000
84/84 [==============================] - 0s 4ms/step - loss: 152154.6406
Epoch 27/8000
84/84 [==============================] - 0s 4ms/step - loss: 152067.2188
Epoch 28/8000
84/84 [==============================] - 0s 4ms/step - loss: 151720.4062
Epoch 29/8000
84/84 [==============================] - 0s 4ms/step - loss: 151329.1719
Epoch 30/8000
84/84 [==============================] - 0s 4ms/step - loss: 151184.2031
Epoch 31/8000
84/84 [==============================] - 0s 4ms/step - loss: 151037.0156
Epoch 32/8000
84/84 [==============================] - 0s 4ms/step - loss: 150766.8438
Epoch 33/8000
84/84 [==============================] - 0s 4ms/step - loss: 150534.1719
Epoch 34/8000
84/84 [==============================] - 0s 4ms/step - loss: 150154.1406
Epoch 35/8000
84/84 [==============================] - 0s 4ms/step - loss: 150138.0156
Epoch 36/8000
84/84 [==============================] - 0s 4ms/step - loss: 149705.4688
Epoch 37/8000
84/84 [==============================] - 0s 4ms/step - loss: 149268.6406
Epoch 38/8000
84/84 [==============================] - 0s 5ms/step - loss: 148739.8594
Epoch 39/8000
84/84 [==============================] - 0s 4ms/step - loss: 148385.2031
Epoch 40/8000
84/84 [==============================] - 0s 4ms/step - loss: 148168.9844
Epoch 41/8000
84/84 [==============================] - 0s 4ms/step - loss: 147603.6094
Epoch 42/8000
84/84 [==============================] - 0s 4ms/step - loss: 147309.2344
Epoch 43/8000
84/84 [==============================] - 0s 4ms/step - loss: 146941.1719
Epoch 44/8000
84/84 [==============================] - 0s 4ms/step - loss: 146857.3125
Epoch 45/8000
84/84 [==============================] - 0s 4ms/step - loss: 146197.0469
Epoch 46/8000
84/84 [==============================] - 0s 4ms/step - loss: 145907.3906
Epoch 47/8000
84/84 [==============================] - 0s 4ms/step - loss: 145650.9531
Epoch 48/8000
84/84 [==============================] - 0s 4ms/step - loss: 145510.6875
Epoch 49/8000
84/84 [==============================] - 0s 4ms/step - loss: 145610.1719
Epoch 50/8000
84/84 [==============================] - 0s 4ms/step - loss: 144951.9531
Epoch 51/8000
84/84 [==============================] - 0s 4ms/step - loss: 144803.0000
Epoch 52/8000
84/84 [==============================] - 0s 4ms/step - loss: 144659.2812
Epoch 53/8000
84/84 [==============================] - 0s 4ms/step - loss: 144257.9062
Epoch 54/8000
84/84 [==============================] - 0s 4ms/step - loss: 143913.2344
Epoch 55/8000
84/84 [==============================] - 0s 4ms/step - loss: 143841.7188
Epoch 56/8000
84/84 [==============================] - 0s 4ms/step - loss: 143694.2969
Epoch 57/8000
84/84 [==============================] - 0s 4ms/step - loss: 143466.9062
Epoch 58/8000
84/84 [==============================] - 0s 5ms/step - loss: 143039.9844
Epoch 59/8000
84/84 [==============================] - 0s 4ms/step - loss: 142754.5000
Epoch 60/8000
84/84 [==============================] - 0s 4ms/step - loss: 142364.4375
Epoch 61/8000
84/84 [==============================] - 0s 4ms/step - loss: 142190.7500
Epoch 62/8000
84/84 [==============================] - 0s 4ms/step - loss: 141808.0938
Epoch 63/8000
84/84 [==============================] - 0s 4ms/step - loss: 141616.0625
Epoch 64/8000
84/84 [==============================] - 0s 4ms/step - loss: 141245.9844
Epoch 65/8000
84/84 [==============================] - 0s 4ms/step - loss: 141130.6719
Epoch 66/8000
84/84 [==============================] - 0s 4ms/step - loss: 140740.7969
Epoch 67/8000
84/84 [==============================] - 0s 4ms/step - loss: 140366.3281
Epoch 68/8000
84/84 [==============================] - 0s 4ms/step - loss: 140047.0469
Epoch 69/8000
84/84 [==============================] - 0s 4ms/step - loss: 139608.2656
Epoch 70/8000
84/84 [==============================] - 0s 4ms/step - loss: 139329.8438
Epoch 71/8000
84/84 [==============================] - 0s 4ms/step - loss: 139304.8438
Epoch 72/8000
84/84 [==============================] - 0s 4ms/step - loss: 139023.1719
Epoch 73/8000
84/84 [==============================] - 0s 4ms/step - loss: 138851.1875
Epoch 74/8000
84/84 [==============================] - 0s 4ms/step - loss: 138728.1719
Epoch 75/8000
84/84 [==============================] - 0s 4ms/step - loss: 138338.3438
Epoch 76/8000
84/84 [==============================] - 0s 4ms/step - loss: 138122.8281
Epoch 77/8000
84/84 [==============================] - 0s 4ms/step - loss: 137853.0312
Epoch 78/8000
84/84 [==============================] - 0s 4ms/step - loss: 137657.3906
Epoch 79/8000
84/84 [==============================] - 0s 4ms/step - loss: 137411.0938
Epoch 80/8000
84/84 [==============================] - 0s 4ms/step - loss: 137244.8438
Epoch 81/8000
84/84 [==============================] - 0s 4ms/step - loss: 137266.0938
Epoch 82/8000
84/84 [==============================] - 0s 5ms/step - loss: 136599.0469
Epoch 83/8000
84/84 [==============================] - 0s 4ms/step - loss: 136396.2344
Epoch 84/8000
84/84 [==============================] - 0s 4ms/step - loss: 136131.4062
Epoch 85/8000
84/84 [==============================] - 0s 4ms/step - loss: 135788.6562
Epoch 86/8000
84/84 [==============================] - 0s 4ms/step - loss: 135807.1094
Epoch 87/8000
84/84 [==============================] - 0s 4ms/step - loss: 135427.1719
Epoch 88/8000
84/84 [==============================] - 0s 4ms/step - loss: 135218.3125
Epoch 89/8000
84/84 [==============================] - 0s 4ms/step - loss: 134962.9062
Epoch 90/8000
84/84 [==============================] - 0s 4ms/step - loss: 134700.5781
Epoch 91/8000
84/84 [==============================] - 0s 4ms/step - loss: 134894.1094
Epoch 92/8000
84/84 [==============================] - 0s 4ms/step - loss: 134610.7969
Epoch 93/8000
84/84 [==============================] - 0s 4ms/step - loss: 133981.8750
Epoch 94/8000
84/84 [==============================] - 0s 4ms/step - loss: 133750.5469
Epoch 95/8000
84/84 [==============================] - 0s 4ms/step - loss: 133295.0156
Epoch 96/8000
84/84 [==============================] - 0s 4ms/step - loss: 133053.2656
Epoch 97/8000
84/84 [==============================] - 0s 4ms/step - loss: 132623.8125
Epoch 98/8000
84/84 [==============================] - 0s 4ms/step - loss: 132356.9844
Epoch 99/8000
84/84 [==============================] - 0s 4ms/step - loss: 132161.8906
Epoch 100/8000
84/84 [==============================] - 0s 4ms/step - loss: 131858.1406
Epoch 101/8000
84/84 [==============================] - 0s 4ms/step - loss: 131738.2188
Epoch 102/8000
84/84 [==============================] - 0s 4ms/step - loss: 131211.5625
Epoch 103/8000
84/84 [==============================] - 0s 4ms/step - loss: 130973.4062
Epoch 104/8000
84/84 [==============================] - 0s 4ms/step - loss: 130755.5703
Epoch 105/8000
84/84 [==============================] - 0s 4ms/step - loss: 130234.8125
Epoch 106/8000
84/84 [==============================] - 0s 4ms/step - loss: 130321.1250
Epoch 107/8000
84/84 [==============================] - 0s 5ms/step - loss: 129669.3047
Epoch 108/8000
84/84 [==============================] - 0s 4ms/step - loss: 129506.2500
Epoch 109/8000
84/84 [==============================] - 0s 4ms/step - loss: 129156.6875
Epoch 110/8000
84/84 [==============================] - 0s 4ms/step - loss: 128654.3750
Epoch 111/8000
84/84 [==============================] - 0s 4ms/step - loss: 128276.9062
Epoch 112/8000
84/84 [==============================] - 0s 4ms/step - loss: 128376.8516
Epoch 113/8000
84/84 [==============================] - 0s 4ms/step - loss: 127674.0781
Epoch 114/8000
84/84 [==============================] - 0s 4ms/step - loss: 127243.7031
Epoch 115/8000
84/84 [==============================] - 0s 4ms/step - loss: 126971.1328
Epoch 116/8000
84/84 [==============================] - 0s 4ms/step - loss: 126628.8516
Epoch 117/8000
84/84 [==============================] - 0s 4ms/step - loss: 126292.2344
Epoch 118/8000
84/84 [==============================] - 0s 5ms/step - loss: 125965.7891
Epoch 119/8000
84/84 [==============================] - 0s 5ms/step - loss: 125618.9844
Epoch 120/8000
84/84 [==============================] - 0s 5ms/step - loss: 125140.2031
Epoch 121/8000
84/84 [==============================] - 0s 4ms/step - loss: 124724.1406
Epoch 122/8000
84/84 [==============================] - 0s 5ms/step - loss: 124679.0234
Epoch 123/8000
84/84 [==============================] - 0s 5ms/step - loss: 124163.0000
Epoch 124/8000
84/84 [==============================] - 0s 4ms/step - loss: 123730.1406
Epoch 125/8000
84/84 [==============================] - 0s 4ms/step - loss: 123401.3672
Epoch 126/8000
84/84 [==============================] - 0s 5ms/step - loss: 123009.3125
Epoch 127/8000
84/84 [==============================] - 0s 4ms/step - loss: 122612.4141
Epoch 128/8000
84/84 [==============================] - 0s 4ms/step - loss: 121918.0547
Epoch 129/8000
84/84 [==============================] - 0s 4ms/step - loss: 121735.7812
Epoch 130/8000
84/84 [==============================] - 0s 4ms/step - loss: 121311.7109
Epoch 131/8000
84/84 [==============================] - 0s 4ms/step - loss: 120919.5234
Epoch 132/8000
84/84 [==============================] - 0s 4ms/step - loss: 120634.1953
Epoch 133/8000
84/84 [==============================] - 0s 4ms/step - loss: 119837.2188
Epoch 134/8000
84/84 [==============================] - 0s 4ms/step - loss: 119494.2109
Epoch 135/8000
84/84 [==============================] - 0s 4ms/step - loss: 119289.5156
Epoch 136/8000
84/84 [==============================] - 0s 4ms/step - loss: 118913.9766
Epoch 137/8000
84/84 [==============================] - 0s 4ms/step - loss: 119061.7891
Epoch 138/8000
84/84 [==============================] - 0s 4ms/step - loss: 118504.1953
Epoch 139/8000
84/84 [==============================] - 0s 4ms/step - loss: 117873.7422
Epoch 140/8000
84/84 [==============================] - 0s 4ms/step - loss: 117387.7188
Epoch 141/8000
84/84 [==============================] - 0s 4ms/step - loss: 116948.0469
Epoch 142/8000
84/84 [==============================] - 0s 4ms/step - loss: 116772.6562
Epoch 143/8000
84/84 [==============================] - 0s 4ms/step - loss: 116298.4062
Epoch 144/8000
84/84 [==============================] - 0s 4ms/step - loss: 116242.8203
Epoch 145/8000
84/84 [==============================] - 0s 4ms/step - loss: 115836.8828
Epoch 146/8000
84/84 [==============================] - 0s 4ms/step - loss: 115193.9062
Epoch 147/8000
84/84 [==============================] - 0s 4ms/step - loss: 115118.3281
Epoch 148/8000
84/84 [==============================] - 0s 4ms/step - loss: 114887.2031
Epoch 149/8000
84/84 [==============================] - 0s 5ms/step - loss: 114599.0625
Epoch 150/8000
84/84 [==============================] - 0s 4ms/step - loss: 114300.8438
Epoch 151/8000
84/84 [==============================] - 0s 4ms/step - loss: 114173.0703
Epoch 152/8000
84/84 [==============================] - 0s 4ms/step - loss: 113389.3438
Epoch 153/8000
84/84 [==============================] - 0s 4ms/step - loss: 113255.2578
Epoch 154/8000
84/84 [==============================] - 0s 4ms/step - loss: 113168.1641
Epoch 155/8000
84/84 [==============================] - 0s 4ms/step - loss: 112790.2969
Epoch 156/8000
84/84 [==============================] - 0s 4ms/step - loss: 112176.6094
Epoch 157/8000
84/84 [==============================] - 0s 4ms/step - loss: 112131.4453
Epoch 158/8000
84/84 [==============================] - 0s 4ms/step - loss: 111482.5000
Epoch 159/8000
84/84 [==============================] - 0s 4ms/step - loss: 111418.2422
Epoch 160/8000
84/84 [==============================] - 0s 4ms/step - loss: 111160.6953
Epoch 161/8000
84/84 [==============================] - 0s 4ms/step - loss: 110928.7031
Epoch 162/8000
84/84 [==============================] - 0s 4ms/step - loss: 110807.1328
Epoch 163/8000
84/84 [==============================] - 0s 4ms/step - loss: 110305.3984
Epoch 164/8000
84/84 [==============================] - 0s 4ms/step - loss: 109871.2656
Epoch 165/8000
84/84 [==============================] - 0s 4ms/step - loss: 109647.1328
Epoch 166/8000
84/84 [==============================] - 0s 4ms/step - loss: 109422.7734
Epoch 167/8000
84/84 [==============================] - 0s 4ms/step - loss: 109243.8047
Epoch 168/8000
84/84 [==============================] - 0s 4ms/step - loss: 108862.4141
Epoch 169/8000
84/84 [==============================] - 0s 4ms/step - loss: 108704.4922
Epoch 170/8000
84/84 [==============================] - 0s 4ms/step - loss: 108139.8750
Epoch 171/8000
84/84 [==============================] - 0s 4ms/step - loss: 108092.5859
Epoch 172/8000
84/84 [==============================] - 0s 4ms/step - loss: 108195.5938
Epoch 173/8000
84/84 [==============================] - 0s 4ms/step - loss: 107518.3984
Epoch 174/8000
84/84 [==============================] - 0s 4ms/step - loss: 106932.9375
Epoch 175/8000
84/84 [==============================] - 0s 4ms/step - loss: 107113.9766
Epoch 176/8000
84/84 [==============================] - 0s 4ms/step - loss: 106661.3672
Epoch 177/8000
84/84 [==============================] - 0s 4ms/step - loss: 106518.6016
Epoch 178/8000
84/84 [==============================] - 0s 4ms/step - loss: 106135.2188
Epoch 179/8000
84/84 [==============================] - 0s 4ms/step - loss: 105905.1172
Epoch 180/8000
84/84 [==============================] - 0s 4ms/step - loss: 105741.8125
Epoch 181/8000
84/84 [==============================] - 0s 4ms/step - loss: 105682.7891
Epoch 182/8000
84/84 [==============================] - 0s 4ms/step - loss: 105483.3594
Epoch 183/8000
84/84 [==============================] - 0s 4ms/step - loss: 104851.6406
Epoch 184/8000
84/84 [==============================] - 0s 4ms/step - loss: 104596.2422
Epoch 185/8000
84/84 [==============================] - 0s 4ms/step - loss: 104583.3438
Epoch 186/8000
84/84 [==============================] - 0s 4ms/step - loss: 104229.2266
Epoch 187/8000
84/84 [==============================] - 0s 4ms/step - loss: 103888.6953
Epoch 188/8000
84/84 [==============================] - 0s 4ms/step - loss: 103830.9453
Epoch 189/8000
84/84 [==============================] - 0s 4ms/step - loss: 103484.0703
Epoch 190/8000
84/84 [==============================] - 0s 4ms/step - loss: 103484.0391
Epoch 191/8000
84/84 [==============================] - 0s 4ms/step - loss: 103086.1406
Epoch 192/8000
84/84 [==============================] - 0s 4ms/step - loss: 102658.4375
Epoch 193/8000
84/84 [==============================] - 0s 4ms/step - loss: 102789.3828
Epoch 194/8000
84/84 [==============================] - 0s 5ms/step - loss: 102374.8828
Epoch 195/8000
84/84 [==============================] - 0s 4ms/step - loss: 102127.0703
Epoch 196/8000
84/84 [==============================] - 0s 4ms/step - loss: 101730.4688
Epoch 197/8000
84/84 [==============================] - 0s 4ms/step - loss: 101683.4688
Epoch 198/8000
84/84 [==============================] - 0s 4ms/step - loss: 101577.7109
Epoch 199/8000
84/84 [==============================] - 0s 4ms/step - loss: 101358.9688
Epoch 200/8000
84/84 [==============================] - 0s 4ms/step - loss: 100825.2031
Epoch 201/8000
84/84 [==============================] - 0s 4ms/step - loss: 100820.0859
Epoch 202/8000
84/84 [==============================] - 0s 4ms/step - loss: 100429.8984
Epoch 203/8000
84/84 [==============================] - 0s 4ms/step - loss: 100444.9062
Epoch 204/8000
84/84 [==============================] - 0s 4ms/step - loss: 100362.7891
Epoch 205/8000
84/84 [==============================] - 0s 4ms/step - loss: 100431.6953
Epoch 206/8000
84/84 [==============================] - 0s 4ms/step - loss: 99902.4375
Epoch 207/8000
84/84 [==============================] - 0s 4ms/step - loss: 99852.0078
Epoch 208/8000
84/84 [==============================] - 0s 4ms/step - loss: 99222.0859
Epoch 209/8000
84/84 [==============================] - 0s 4ms/step - loss: 99079.4219
Epoch 210/8000
84/84 [==============================] - 0s 4ms/step - loss: 99021.3438
Epoch 211/8000
84/84 [==============================] - 0s 4ms/step - loss: 98491.4297
Epoch 212/8000
84/84 [==============================] - 0s 5ms/step - loss: 98460.6094
Epoch 213/8000
84/84 [==============================] - 0s 4ms/step - loss: 98369.6875
Epoch 214/8000
84/84 [==============================] - 0s 4ms/step - loss: 98007.9141
Epoch 215/8000
84/84 [==============================] - 0s 4ms/step - loss: 97833.7031
Epoch 216/8000
84/84 [==============================] - 0s 4ms/step - loss: 97690.4375
Epoch 217/8000
84/84 [==============================] - 0s 4ms/step - loss: 97532.6016
Epoch 218/8000
84/84 [==============================] - 0s 4ms/step - loss: 97466.8906
Epoch 219/8000
84/84 [==============================] - 0s 4ms/step - loss: 97079.6250
Epoch 220/8000
84/84 [==============================] - 0s 4ms/step - loss: 97003.3125
Epoch 221/8000
84/84 [==============================] - 0s 4ms/step - loss: 96571.3828
Epoch 222/8000
84/84 [==============================] - 0s 4ms/step - loss: 96755.4531
Epoch 223/8000
84/84 [==============================] - 0s 4ms/step - loss: 96662.8359
Epoch 224/8000
84/84 [==============================] - 0s 4ms/step - loss: 96148.6875
Epoch 225/8000
84/84 [==============================] - 0s 4ms/step - loss: 96105.9844
Epoch 226/8000
84/84 [==============================] - 0s 4ms/step - loss: 96104.0156
Epoch 227/8000
84/84 [==============================] - 0s 4ms/step - loss: 95963.6719
Epoch 228/8000
84/84 [==============================] - 0s 4ms/step - loss: 95634.1016
Epoch 229/8000

In [13]:
for layer in model.layers:
    print(layer.name)

input_1
dense
reshape
conv2d
conv2d_1
flatten
dense_1
reshape_1
conv2d_transpose
conv2d_transpose_1
dropout
flatten_1
dense_2
dense_3
dense_4

In [14]:
from tensorflow.keras.models import Model
latent_model = Model(inputs=input_gex, outputs=hidden_layer)

In [15]:
model.predict( W.iloc[1:2])

1/1 [==============================] - 0s 185ms/step

array([[-2.24208359e+02, -1.97359116e+02, -2.10799942e+02,
        -3.08458618e+02, -1.65448837e+01, -2.63240845e+02,
        -1.70755768e+02, -1.69316559e+02, -2.39512787e+02,
        -2.39700348e+02, -3.12680016e+01,  4.28726654e+02,
        -2.49372681e+02,  1.47123840e+02, -3.47111816e+02,
        -2.10083141e+01, -9.39030228e+01, -1.13395882e+02,
        -1.28423309e+02,  3.45298431e+02, -9.17555923e+01,
        -7.97398682e+01, -7.08769043e+02, -3.73078705e+02,
        -2.63861511e+02, -9.31281921e+02,  9.07449417e+01,
        -1.29708176e+02, -2.50253189e+02,  4.84682693e+01,
        -7.77644226e+02,  5.12047913e+02, -5.03804932e+01,
        -1.02488070e+01,  8.89728638e+02,  1.85931969e+01,
         1.86489243e+02,  1.68347893e+01, -2.44829178e+01,
        -1.18158981e+02,  5.75618286e+02, -2.63524292e+02,
         1.15523758e+02,  7.16984253e+01,  1.29332748e+02,
        -1.12879974e+02,  8.45600815e+01, -1.97439041e+02,
         1.70638428e+02,  6.25315063e+02, -3.16162018e+02,
        -2.27699463e+02,  2.82797424e+02,  4.15980316e+02,
        -2.72173248e+02,  3.15005096e+02, -3.62712646e+02,
         2.68308239e+01,  1.53373810e+02,  1.23565435e+01,
        -6.24909515e+01,  4.58003693e+01, -3.52143646e+02,
        -4.05895233e+02,  1.50074142e+02, -3.52754120e+02,
        -9.60368530e+02,  3.09181470e+03,  8.52457504e+01,
        -5.48741760e+02,  1.94466171e+02, -1.93854370e+02,
        -3.81164861e+00,  6.01174133e+02, -6.90093842e+01,
         2.63807068e+02, -3.26316040e+02, -4.08834442e+02,
         3.49828339e+02,  1.33502487e+02,  6.79213867e+02,
         8.66230249e-01,  1.08806808e+02, -5.18139038e+02,
        -9.71311035e+01,  4.31011780e+02,  8.03005219e+01,
         2.32283035e+02,  3.07249756e+02, -5.24642029e+02,
        -1.58786636e+02,  1.68725677e+02, -2.84228638e+02,
         3.29388977e+02,  3.68063751e+02,  8.86595886e+02,
         8.36972839e+02, -7.17134277e+02,  2.87563477e+02,
        -3.85186859e+02, -4.14655380e+01, -3.54431458e+02,
         1.31365784e+02, -3.02739136e+02, -1.31958008e+02,
         9.95546341e+01,  7.99018127e+02,  2.88222961e+02,
        -4.24806366e+02,  5.52813110e+02,  3.39579865e+02,
         1.53808609e+02,  9.66509338e+02,  2.69090790e+02,
         7.97928619e+01, -2.99118896e+02, -2.15173141e+02,
         8.95384827e+02,  1.23153955e+03,  1.56114922e+01,
        -1.97139465e+02]], dtype=float32)

In [16]:
model.predict( W.iloc[4:5])

1/1 [==============================] - 0s 23ms/step

array([[ 2.99025097e+01, -1.29823334e+02,  5.04053375e+02,
         1.02576099e+03, -4.59208252e+02,  9.47378784e+02,
         5.51705261e+02,  6.47405273e+02,  4.24101044e+02,
        -7.85735535e+02,  5.21903076e+02, -1.05286133e+02,
         6.43223755e+02,  6.10786255e+02, -2.51719131e+02,
         3.03378315e+01,  2.37277206e+02,  3.74429993e+02,
        -3.30582916e+02,  5.72548096e+02, -7.45910767e+02,
         5.96614380e+02,  6.01103149e+02,  5.87497314e+02,
        -4.40165161e+02, -6.34387939e+02,  9.74856140e+02,
        -7.61237244e+02, -7.79006165e+02, -1.26725305e+03,
        -9.25203629e+01, -1.19824005e+02,  4.54723663e+02,
         2.67174408e+02, -5.93422119e+02, -2.20216827e+02,
        -1.88264389e+02,  3.54315979e+02, -6.14906738e+02,
        -1.84951324e+01, -1.29966751e+02, -1.19321472e+02,
         2.81959564e+02, -4.46191528e+02,  1.52803772e+02,
        -3.38887299e+02,  1.73328278e+02,  5.09690002e+02,
         7.32550354e+01,  2.32565048e+02, -1.55338165e+02,
         2.41227402e+02,  6.85648499e+02,  4.89092041e+02,
        -5.84333252e+02,  8.43896423e+02, -4.40373840e+02,
         4.51546387e+02,  2.84375763e+02,  3.98158932e+00,
        -5.11650757e+02,  1.12863480e+02, -3.11429626e+02,
        -1.82084320e+02, -5.86688171e+02, -2.98860535e+02,
        -5.42705566e+02,  3.57835034e+03,  1.05039721e+01,
         8.43627319e+01, -7.56489075e+02, -2.70653778e+02,
         6.79591614e+02, -4.62591217e+02,  1.50052155e+02,
        -8.42638016e+01, -7.08464111e+02,  1.79888992e+02,
         5.12056458e+02,  7.56218338e+01,  1.13855789e+02,
         8.16862946e+01, -4.80614990e+02,  6.04599487e+02,
         3.16930771e+00,  1.50595154e+02, -8.94868713e+02,
         3.03405975e+02, -4.22994110e+02, -1.16510083e+03,
        -1.18543556e+02, -3.63056580e+02, -8.60936707e+02,
         5.12729797e+02, -2.26012192e+02, -1.57736115e+02,
         7.03415222e+02, -1.90951538e+02,  5.07543335e+02,
        -9.47165833e+02, -5.67689697e+02, -7.90290405e+02,
         6.49029007e+01,  2.50548584e+02,  1.95856323e+02,
        -7.34781616e+02,  1.14161621e+02,  5.53564575e+02,
        -2.11960831e+02, -2.91888550e+02,  3.11419159e+02,
        -3.68501648e+02,  7.38336731e+02,  7.50450378e+02,
         9.65189209e+01,  6.78930908e+02, -3.43581970e+02,
        -5.00552597e+01, -9.45935440e+01, -6.77966553e+02,
         2.17338043e+02]], dtype=float32)

In [17]:
integration_pred = latent_model.predict( W)

669/669 [==============================] - 1s 819us/step

In [18]:
pd.DataFrame(integration_pred[1:50,1:50])

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,0.000000,122.068420,144.880676,0.0,0.0,0.0,235.171188,133.973587,0.0,54.973404,...,0.0,110.244179,0.0,0.0,0.000000,2.161657,0.0,100.892456,0.0,0.000000
1,0.000000,177.388382,175.409531,0.0,0.0,0.0,264.593536,50.165634,0.0,37.211384,...,0.0,97.916641,0.0,0.0,158.319702,1.101223,0.0,0.000000,0.0,0.000000
2,0.000000,79.017914,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.0,30.997129,0.000000,0.0,0.000000,0.0,0.000000
3,0.000000,144.278122,73.185326,0.0,0.0,0.0,172.237823,0.000000,0.0,0.000000,...,0.0,24.806492,0.0,0.0,178.823868,151.895065,0.0,8.056357,0.0,0.000000
4,0.000000,94.950539,68.161316,0.0,0.0,0.0,183.732925,89.298347,0.0,85.119553,...,0.0,159.515182,0.0,0.0,111.759735,29.540537,0.0,83.102173,0.0,0.000000
5,0.000000,108.689705,104.009605,0.0,0.0,0.0,177.110977,123.488007,0.0,128.793594,...,0.0,88.715446,0.0,0.0,96.653870,0.000000,0.0,126.614189,0.0,0.000000
6,0.000000,99.639862,166.959854,0.0,0.0,0.0,35.398140,73.442856,0.0,0.000000,...,0.0,0.000000,0.0,0.0,68.998665,7.713584,0.0,0.000000,0.0,0.000000
7,0.000000,33.599720,24.182539,0.0,0.0,0.0,254.607193,116.135643,0.0,0.000000,...,0.0,44.849846,0.0,0.0,0.000000,7.122348,0.0,27.922842,0.0,0.000000
8,322.369934,308.229858,289.871307,0.0,0.0,0.0,260.251099,0.000000,0.0,173.091080,...,0.0,262.992004,0.0,0.0,262.000336,166.428574,0.0,0.000000,0.0,392.639282
9,0.000000,97.831253,118.094978,0.0,0.0,0.0,198.399567,153.333588,0.0,47.584805,...,0.0,271.500000,0.0,0.0,53.936348,34.616501,0.0,156.498688,0.0,0.000000
10,0.000000,71.960426,241.806534,0.0,0.0,0.0,16.134346,0.000000,0.0,0.000000,...,0.0,115.428932,0.0,0.0,70.153557,81.170403,0.0,0.000000,0.0,0.000000
11,0.000000,18.900845,89.336464,0.0,0.0,0.0,232.828888,107.217072,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000
12,0.000000,151.222839,28.029804,0.0,0.0,0.0,101.473900,12.217771,0.0,80.590790,...,0.0,105.121208,0.0,0.0,65.932831,56.077923,0.0,69.206963,0.0,0.000000
13,0.000000,177.740097,116.496666,0.0,0.0,0.0,131.708817,82.332291,0.0,0.000000,...,0.0,92.825996,0.0,0.0,171.268173,187.957550,0.0,0.000000,0.0,0.000000
14,0.000000,107.535782,133.321045,0.0,0.0,0.0,0.000000,63.051319,0.0,113.188927,...,0.0,54.605812,0.0,0.0,167.715088,18.426092,0.0,0.000000,0.0,0.000000
15,0.000000,155.671860,168.978088,0.0,0.0,0.0,152.765076,0.000000,0.0,113.097099,...,0.0,53.767426,0.0,0.0,174.299698,70.358116,0.0,0.000000,0.0,0.000000
16,0.000000,5.514876,109.358444,0.0,0.0,0.0,64.341560,90.051056,0.0,0.000000,...,0.0,79.948830,0.0,0.0,64.371178,0.000000,0.0,47.752995,0.0,145.549438
17,387.626007,272.984528,468.170685,0.0,0.0,0.0,254.922287,198.353210,0.0,224.208008,...,0.0,197.254257,0.0,0.0,202.927826,244.571320,0.0,0.000000,0.0,310.540710
18,0.000000,110.671898,106.015717,0.0,0.0,0.0,142.462891,132.257690,0.0,0.000000,...,0.0,111.971931,0.0,0.0,0.000000,115.782486,0.0,0.000000,0.0,108.362831
19,0.000000,57.878872,0.000000,0.0,0.0,0.0,88.674881,80.771820,0.0,158.631180,...,0.0,70.102898,0.0,0.0,102.184227,89.699104,0.0,49.296120,0.0,0.000000
20,0.000000,138.354523,136.819489,0.0,0.0,0.0,85.953377,47.483521,0.0,55.108456,...,0.0,53.789825,0.0,0.0,92.012894,6.807560,0.0,0.000000,0.0,0.000000
21,302.214569,405.799133,224.313538,0.0,0.0,0.0,314.060608,32.123104,0.0,126.365685,...,0.0,347.852539,0.0,0.0,190.408234,237.798615,0.0,0.000000,0.0,386.454987
22,0.000000,79.132919,67.218369,0.0,0.0,0.0,130.137222,95.999329,0.0,25.985355,...,0.0,115.648201,0.0,0.0,0.000000,18.752035,0.0,56.880787,0.0,0.000000
23,0.000000,211.269928,171.304718,0.0,0.0,0.0,111.244217,31.395678,0.0,0.000000,...,0.0,0.000000,0.0,0.0,19.612152,79.972511,0.0,87.633408,0.0,0.000000
24,0.000000,145.568130,57.976772,0.0,0.0,0.0,55.673473,66.637199,0.0,25.723770,...,0.0,66.856827,0.0,0.0,97.762398,101.977768,0.0,68.391113,0.0,0.000000
25,0.000000,186.376236,91.513908,0.0,0.0,0.0,71.369766,121.962044,0.0,124.031906,...,0.0,86.904915,0.0,0.0,56.768368,0.000000,0.0,143.869980,0.0,32.482006
26,0.000000,453.074097,495.579651,0.0,0.0,0.0,294.295685,283.953064,0.0,285.882904,...,0.0,303.285370,0.0,0.0,306.568878,279.781067,0.0,0.000000,0.0,0.000000
27,0.000000,40.155933,149.972351,0.0,0.0,0.0,151.685745,21.349833,0.0,0.000000,...,0.0,54.732536,0.0,0.0,0.000000,15.454143,0.0,0.000000,0.0,0.000000
28,0.000000,112.291916,102.418732,0.0,0.0,0.0,0.000000,83.722214,0.0,1.663557,...,0.0,28.796036,0.0,0.0,60.941582,0.000000,0.0,0.000000,0.0,0.000000
29,0.000000,84.650398,142.084183,0.0,0.0,0.0,172.143890,88.184975,0.0,69.101280,...,0.0,35.803207,0.0,0.0,0.000000,41.245872,0.0,0.000000,0.0,0.000000
30,0.000000,188.574570,138.336853,0.0,0.0,0.0,93.983284,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.0,88.342842,13.389685,0.0,39.805859,0.0,0.000000
31,0.000000,66.104630,91.458015,0.0,0.0,0.0,50.572521,98.266602,0.0,0.000000,...,0.0,13.010934,0.0,0.0,77.880348,0.000000,0.0,0.000000,0.0,96.507423
32,0.000000,87.902634,67.265999,0.0,0.0,0.0,137.398331,90.018570,0.0,19.377922,...,0.0,121.242882,0.0,0.0,88.651642,8.149082,0.0,111.191605,0.0,0.000000
33,0.000000,90.488068,38.246979,0.0,0.0,0.0,141.291046,102.328537,0.0,63.558216,...,0.0,115.225243,0.0,0.0,102.917938,30.945860,0.0,182.446243,0.0,0.000000
34,0.000000,0.000000,177.039474,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,...,0.0,59.402153,0.0,0.0,106.546471,74.996132,0.0,0.000000,0.0,0.000000
35,289.843292,280.610687,230.289597,0.0,0.0,0.0,223.158966,113.222061,0.0,13.360394,...,0.0,297.425110,0.0,0.0,128.842255,209.955032,0.0,0.000000,0.0,306.662292
36,0.000000,53.779480,78.666473,0.0,0.0,0.0,87.896751,21.685566,0.0,2.474794,...,0.0,33.462387,0.0,0.0,6.660513,74.490524,0.0,75.545464,0.0,0.000000
37,356.028320,276.585938,484.471863,0.0,0.0,0.0,114.861137,137.685074,0.0,178.536316,...,0.0,241.662903,0.0,0.0,186.820206,236.738663,0.0,0.000000,0.0,409.414246
38,0.000000,129.804871,196.031998,0.0,0.0,0.0,97.541611,67.272614,0.0,15.043379,...,0.0,5.250242,0.0,0.0,28.207209,0.000000,0.0,0.000000,0.0,0.000000
39,0.000000,47.054302,0.000000,0.0,0.0,0.0,89.622124,47.584667,0.0,67.976814,...,0.0,100.961502,0.0,0.0,24.756908,0.000000,0.0,0.000000,0.0,0.000000
40,0.000000,40.514221,104.743813,0.0,0.0,0.0,75.907936,120.303352,0.0,127.554672,...,0.0,27.047920,0.0,0.0,17.215916,21.064478,0.0,135.145035,0.0,20.024315
41,0.000000,118.683479,91.735413,0.0,0.0,0.0,120.057228,126.562958,0.0,37.300228,...,0.0,35.169556,0.0,0.0,65.315987,15.851642,0.0,36.512878,0.0,0.000000
42,314.463104,297.634216,416.176392,0.0,0.0,0.0,362.587616,172.443512,0.0,249.816666,...,0.0,302.636292,0.0,0.0,283.634827,196.538223,0.0,0.000000,0.0,448.863892
43,0.000000,85.754959,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.000000,68.818947,0.0,0.000000,0.0,0.000000
44,0.000000,87.035004,20.937832,0.0,0.0,0.0,231.496597,0.000000,0.0,17.724030,...,0.0,74.174416,0.0,0.0,104.753471,92.118652,0.0,92.656120,0.0,0.000000
45,319.564545,204.015030,306.741272,0.0,0.0,0.0,337.911072,189.494934,0.0,39.389061,...,0.0,335.393250,0.0,0.0,188.972992,247.490936,0.0,0.000000,0.0,464.925781
46,0.000000,58.859264,82.638100,0.0,0.0,0.0,43.706646,0.000000,0.0,0.000000,...,0.0,0.000000,0.0,0.0,50.100349,75.365616,0.0,0.000000,0.0,0.000000
47,0.000000,487.928162,489.069183,0.0,0.0,0.0,514.449463,549.901184,0.0,258.689331,...,0.0,355.363342,0.0,0.0,365.908417,269.636719,0.0,0.000000,0.0,0.000000
48,0.000000,73.690308,43.445175,0.0,0.0,0.0,154.960495,153.869019,0.0,73.272949,...,0.0,67.283638,0.0,0.0,112.859016,0.000000,0.0,112.547775,0.0,0.000000

In [19]:
integration_pred = integration_pred.reshape([integration_pred.shape[0],-1])

In [20]:
integration_pred.shape

(21393, 225)

In [21]:
integration_pred = integration_pred.reshape([integration_pred.shape[0],-1])
integration_pred.shape

(21393, 225)

In [22]:
pd.DataFrame(integration_pred)

,0,1,2,3,4,5,6,7,8,9,...,215,216,217,218,219,220,221,222,223,224
0,0.000000,0.0000,44.936493,91.680641,0.0,0.0,0.0,53.601440,38.394032,0.0,...,0.0,0.000000,0.0,27.987392,122.077484,0.0,0.0,0.000000,0.000000,0.000000
1,0.000000,0.0000,122.068420,144.880676,0.0,0.0,0.0,235.171188,133.973587,0.0,...,0.0,0.000000,0.0,0.000000,58.173519,0.0,0.0,0.000000,0.000000,92.982040
2,0.000000,0.0000,177.388382,175.409531,0.0,0.0,0.0,264.593536,50.165634,0.0,...,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,50.614620
3,0.000000,0.0000,79.017914,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.0,55.561527,0.0,97.908569,83.885185,0.0,0.0,35.345871,0.000000,0.000000
4,0.000000,0.0000,144.278122,73.185326,0.0,0.0,0.0,172.237823,0.000000,0.0,...,0.0,0.000000,0.0,0.000000,97.810318,0.0,0.0,0.000000,0.000000,18.829268
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21388,0.000000,0.0000,83.636475,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.0,108.500023,0.0,115.580772,166.173477,0.0,0.0,71.598198,0.000000,0.000000
21389,15.489287,0.0000,82.227959,85.610451,0.0,0.0,0.0,161.260818,0.000000,0.0,...,0.0,0.000000,0.0,0.000000,218.587601,0.0,0.0,0.000000,0.000000,62.542667
21390,0.000000,208.6073,189.220612,269.774323,0.0,0.0,0.0,19.516222,100.878342,0.0,...,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,55.067757,68.850571
21391,0.000000,0.0000,101.666344,159.804276,0.0,0.0,0.0,189.779175,125.373993,0.0,...,0.0,0.000000,0.0,0.000000,56.488537,0.0,0.0,0.000000,0.000000,0.000000
21392,0.000000,0.0000,435.704529,404.014343,0.0,0.0,0.0,376.657715,373.153809,0.0,...,0.0,170.892563,0.0,0.000000,303.796295,0.0,0.0,0.000000,189.689102,219.259918

In [23]:
pd.DataFrame(integration_pred).to_csv("integration_pred_new_method_gex_to_TCR_beta_chain_10X_donor_4_only_022626.csv", index=False)