In this work, we use transformer model to integrate gene expression and TCR amino acid sequences

Getting gene data

In [1]:
# %matplotlib inline

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import os 
import numpy as np

import pandas as pd
# import seaborn as sb
import matplotlib.pyplot as pl

import scanpy as sc

import anndata as ad

from scipy.sparse import csr_matrix
from matplotlib import rcParams
from matplotlib import colors

sc.settings.verbosity = 3

In [2]:
gene_TCR = ad.read_h5ad('../10Xdatasets/gex_merge_log1_5000_genes_all_peptides.h5ad')
gene_TCR

/home/phile/miniconda3/envs/integration/lib/python3.9/site-packages/anndata/_core/anndata.py:1754: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

AnnData object with n_obs × n_vars = 145479 × 5000
    obs: 'v_gene_TRA', 'v_gene_TRB', 'd_gene_TRA', 'd_gene_TRB', 'j_gene_TRA', 'j_gene_TRB', 'c_gene_TRA', 'c_gene_TRB', 'cdr3_TRA', 'cdr3_TRB', 'cdr3_nt_TRA', 'cdr3_nt_TRB', 'umis_TRA', 'umis_TRB', 'donor', 'cell_clono_cdr3_aa', 'cell_clono_cdr3_nt', 'CD3', 'CD19', 'CD45RA', 'CD4', 'CD8a', 'CD14', 'CD45RO', 'CD279_PD-1', 'IgG1', 'IgG2a', 'IgG2b', 'CD127', 'CD197_CCR7', 'HLA-DR', 'A0101_VTEHDTLLY_IE-1_CMV', 'A0201_KTWGQYWQV_gp100_Cancer', 'A0201_ELAGIGILTV_MART-1_Cancer', 'A0201_CLLWSFQTSA_Tyrosinase_Cancer', 'A0201_IMDQVPFSV_gp100_Cancer', 'A0201_SLLMWITQV_NY-ESO-1_Cancer', 'A0201_KVAELVHFL_MAGE-A3_Cancer', 'A0201_KVLEYVIKV_MAGE-A1_Cancer', 'A0201_CLLGTYTQDV_Kanamycin-B-dioxygenase', 'A0201_LLDFVRFMGV_EBNA-3B_EBV', 'A0201_LLMGTLGIVC_HPV-16E7_82-91', 'A0201_CLGGLLTMV_LMP-2A_EBV', 'A0201_YLLEMLWRL_LMP1_EBV', 'A0201_FLYALALLL_LMP2A_EBV', 'A0201_GILGFVFTL_Flu-MP_Influenza', 'A0201_GLCTLVAML_BMLF1_EBV', 'A0201_NLVPMVATV_pp65_CMV', 'A0201_ILKEPVHGV_RT_HIV', 'A0201_FLASKIGRLV_Ca2-indepen-Plip-A2', 'A2402_CYTWNQMNL_WT1-(235-243)236M_Y', 'A0201_RTLNAWVKV_Gag-protein_HIV', 'A0201_KLQCVDLHV_PSA146-154', 'A0201_LLFGYPVYV_HTLV-1', 'A0201_SLFNTVATL_Gag-protein_HIV', 'A0201_SLYNTVATLY_Gag-protein_HIV', 'A0201_SLFNTVATLY_Gag-protein_HIV', 'A0201_RMFPNAPYL_WT-1', 'A0201_YLNDHLEPWI_BCL-X_Cancer', 'A0201_MLDLQPETT_16E7_HPV', 'A0301_KLGGALQAK_IE-1_CMV', 'A0301_RLRAEAQVK_EMNA-3A_EBV', 'A0301_RIAAWMATY_BCL-2L1_Cancer', 'A1101_IVTDFSVIK_EBNA-3B_EBV', 'A1101_AVFDRKSDAK_EBNA-3B_EBV', 'B3501_IPSINVHHY_pp65_CMV', 'A2402_AYAQKIFKI_IE-1_CMV', 'A2402_QYDPVAALF_pp65_CMV', 'B0702_QPRAPIRPI_EBNA-6_EBV', 'B0702_TPRVTGGGAM_pp65_CMV', 'B0702_RPPIFIRRL_EBNA-3A_EBV', 'B0702_RPHERNGFTVL_pp65_CMV', 'B0801_RAKFKQLL_BZLF1_EBV', 'B0801_ELRRKMMYM_IE-1_CMV', 'B0801_FLRGRAYGL_EBNA-3A_EBV', 'A0101_SLEGGGLGY_NC', 'A0101_STEGGGLAY_NC', 'A0201_ALIAPVHAV_NC', 'A2402_AYSSAGASI_NC', 'B0702_GPAESAAGL_NC', 'NR(B0801)_AAKGRGAAL_NC', 'antigen', 'peptide', 'orig_ix', 'n_counts', 'log_counts', 'n_genes', 'mt_fraction'
    var: 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection'
    uns: 'donor_colors', 'hvg', 'log1p'
    layers: 'raw_counts'

In [3]:
gene = pd.DataFrame(gene_TCR.layers['raw_counts'].todense())
gene

,0,1,2,3,4,5,6,7,8,9,...,4990,4991,4992,4993,4994,4995,4996,4997,4998,4999
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,1.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0
4,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145474,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
145475,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,5.0,3.0,0.0,0.0
145476,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
145477,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0
145478,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0

In [4]:
tcr_seq = gene_TCR.obs[['cdr3_TRB']]
tcr_seq

                             cdr3_TRB
barcode
AGGGTGAGTATTACCG-18    CSAPSGEGRDTQYF
CTTGGCTTCGTTGCCT-25    CASSLFDSQETQYF
ACGATACTCGCAGGCT-40  CASSLFDSGRLDTQYF
ACGCCAGTCATGTCTT-8       CSASPGDYEQYF
TTCTTAGCAAAGAATC-4     CASSHGKGGNEQFF
...                               ...
GAAGCAGAGCAGGCTA-3     CATSDRLAGGELFF
CAGTCCTTCATCACCC-8   CASSYLAGDFTDTQYF
GACTACACACGGTAAG-3    CASRTGLASTDTQYF
ATCGAGTAGTTTCCTT-4   CASSTTGRTNTGELFF
ACCCACTTCTTGGGTA-3   CASRVSGSLSYNEQFF

[145479 rows x 1 columns]

In [5]:
import tensorflow as tf

2026-03-03 15:43:55.272667: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-03-03 15:43:55.424094: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-03 15:43:55.455882: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

In [16]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Reshape, Conv2D, Conv2DTranspose, Flatten, Dropout
from tensorflow.keras.initializers import HeNormal
# Define input layer
input_gex = Input(shape=(100,))
gex = Dense(units=64, activation='relu', kernel_initializer=HeNormal())(input_gex)
gex = Reshape(target_shape=(8,8,1))(gex)

# Convolutional layers
gex = Conv2D(filters=64, kernel_size=3, strides=1, activation='relu', padding="same")(gex)
gex = Conv2D(filters=32, kernel_size=3, strides=1, activation='relu', padding="same")(gex)

gex = Flatten()(gex)
hidden_layer = Dense(units=64, activation='relu', kernel_initializer=HeNormal())(gex)

# Transposed Convolutional layers
tcr = Reshape(target_shape=(8,8,1))(hidden_layer)
tcr = Conv2DTranspose(filters=16, kernel_size=3, strides=1, activation='relu', padding="same")(tcr)
tcr = Conv2DTranspose(filters=32, kernel_size=3, strides=1, activation='relu', padding="same")(tcr)
tcr = Dropout(rate=0.2)(tcr)
tcr = Flatten()(tcr)
tcr = Dense(units=150, activation='relu', kernel_initializer=HeNormal())(tcr)
tcr = Dense(units=130, activation='relu')(tcr)  # Ensure proper activation
tcr = Dense(units=121, activation='relu')(tcr)
# Define model
model = Model(inputs=input_gex, outputs=tcr)
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.00015),
              loss='mse')

# Check layer names
model.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_3 (InputLayer)        [(None, 100)]             0

 dense_10 (Dense)            (None, 64)                6464

 reshape_4 (Reshape)         (None, 8, 8, 1)           0

 conv2d_4 (Conv2D)           (None, 8, 8, 64)          640

 conv2d_5 (Conv2D)           (None, 8, 8, 32)          18464

 flatten_4 (Flatten)         (None, 2048)              0

 dense_11 (Dense)            (None, 64)                131136

 reshape_5 (Reshape)         (None, 8, 8, 1)           0

 conv2d_transpose_4 (Conv2DT  (None, 8, 8, 16)         160
 ranspose)

 conv2d_transpose_5 (Conv2DT  (None, 8, 8, 32)         4640
 ranspose)

 dropout_2 (Dropout)         (None, 8, 8, 32)          0

 flatten_5 (Flatten)         (None, 2048)              0

 dense_12 (Dense)            (None, 150)               307350

 dense_13 (Dense)            (None, 130)               19630

 dense_14 (Dense)            (None, 121)               15851

=================================================================
Total params: 504,335
Trainable params: 504,335
Non-trainable params: 0
_________________________________________________________________

In [7]:
# import tensorflow as tf
# from tensorflow.keras.models import Model
# from tensorflow.keras.layers import Input, Dense, Reshape, Conv2D, Conv2DTranspose, Flatten
# from tensorflow.keras.initializers import HeNormal

# # Define input layer
# input_gex = Input(shape=(100,))
# gex = Dense(units=64, activation='relu', kernel_initializer=HeNormal())(input_gex)
# gex = Reshape(target_shape=(8,8,1))(gex)

# # Convolutional layers
# gex = Conv2D(filters=64, kernel_size=3, strides=1, activation='relu', padding="same")(gex)
# gex = Conv2D(filters=32, kernel_size=3, strides=1, activation='relu', padding="same")(gex)

# gex = Flatten()(gex)
# hidden_layer = Dense(units=225, activation='relu', kernel_initializer=HeNormal())(gex)

# # Transposed Convolutional layers
# tcr = Reshape(target_shape=(8,8,1))(hidden_layer)
# tcr = Conv2DTranspose(filters=16, kernel_size=3, strides=1, activation='relu', padding="same")(tcr)
# tcr = Conv2DTranspose(filters=32, kernel_size=3, strides=1, activation='relu', padding="same")(tcr)

# tcr = Flatten()(tcr)
# tcr = Dense(units=64, activation='relu', kernel_initializer=HeNormal())(tcr)
# tcr = Dense(units=121)(tcr)  # Ensure proper activation

# # Define model
# model = Model(inputs=input_gex, outputs=tcr)
# model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
#               loss='mse')

# # Check layer names
# model.summary()

In [8]:
AE_tcr = pd.read_csv("../AE_emb_TRB_all_peptides_10X_all_donors.csv")
AE_tcr

,0,1,2,3,4,5,6,7,8,9,...,111,112,113,114,115,116,117,118,119,120
0,-1541.692100,431.963380,-113.48751,363.83960,-617.465500,-576.38770,-152.861240,-985.72640,445.512240,-236.100420,...,28.279720,1018.37134,261.223200,87.342865,-228.999980,146.428400,532.794070,865.979250,-578.558960,855.616900
1,-273.513100,-398.893860,616.80430,-877.82350,-871.226700,375.48306,422.579040,192.50789,-199.132490,-265.096560,...,494.893800,258.40955,-404.777220,-428.136350,-191.204730,-372.523960,203.390100,1186.992800,96.218480,-457.060200
2,380.871000,58.110577,-132.31460,-259.36774,-274.578430,-194.46793,248.315840,265.90674,-60.173637,-98.568726,...,92.126270,29.88193,-891.704800,370.281830,59.372814,-729.678000,902.504940,1161.101400,-700.613340,-425.839780
3,-1229.993200,261.055080,-116.35792,339.64825,-440.477600,65.39269,-221.381640,-939.52580,145.774370,39.421880,...,153.995830,770.41030,-417.146600,194.590100,-287.056100,-4.876206,-74.260704,43.650208,-67.906160,-309.779940
4,-1113.337300,-93.408485,-280.13140,-150.60530,-93.476110,-520.02313,64.995720,-1008.05770,174.263440,-62.470676,...,-56.364480,984.19050,467.822940,247.904310,409.301880,-60.920048,744.377300,1218.065600,-456.735320,617.486100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145474,-512.594500,-576.577700,-841.85020,-472.11673,-47.690334,-245.14507,299.702820,-409.62906,-274.262500,191.512990,...,-605.121150,1250.64900,-388.322940,282.790900,-704.643740,37.460022,647.884160,1549.309400,352.393280,-108.645310
145475,226.274380,956.163450,176.05064,-689.92920,162.394490,608.82790,-269.477480,-744.45300,-219.842730,835.156560,...,31.987225,508.31207,-341.937840,-267.425480,-786.679300,-816.931300,291.385250,466.537630,-74.314735,-342.459630
145476,1080.433300,373.862700,-65.57249,-259.77700,35.480648,-554.94806,-441.794400,93.13507,-163.760620,155.478730,...,-251.648400,687.42706,-52.241924,-690.953600,523.990230,-314.377440,-316.330050,697.732100,40.809692,-1766.797400
145477,55.882103,-766.636600,229.29408,-177.78737,634.726900,-295.03433,92.827480,443.62762,244.667330,-787.343600,...,385.697330,895.55630,-700.939200,-126.450980,-803.600100,133.600450,-130.163740,348.644740,-400.828250,38.264355
145478,278.827970,385.649570,778.76685,-226.10646,-271.815100,803.10120,31.005701,-202.65800,319.472100,-896.443360,...,-155.597400,-415.30975,24.382898,143.311220,198.310820,802.341100,-1194.200600,1312.900500,-973.223140,-750.028100

In [9]:
# import numpy as np
# from sklearn.decomposition import NMF

# # Generate random non-negative data
# data = gene.to_numpy()

# # Initialize the NMF model
# n_components = 100
# model_nmf = NMF(n_components=n_components, init='random', random_state=0)

# # Fit the model to the data
# W = model_nmf.fit_transform(data)
# H = model_nmf.components_

# # Display the results
# print("Basis matrix (W):\n", W)
# print("Coefficients matrix (H):\n", H)

In [10]:

# W = pd.DataFrame(W)
# W

In [11]:
# W.to_csv('gex_nmf_100_components_all_peptides_10X_all_donors.csv', index=False)
W = pd.read_csv('gex_nmf_100_components_all_peptides_10X_all_donors.csv')
W

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.227333,7.086625,0.466240,0.436161,0.334158,0.003627,0.198576,0.001280,0.004045,0.002781,...,0.004944,0.033126,0.143294,0.116318,0.053315,0.090684,0.018362,0.296472,0.013140,0.083483
1,1.316014,5.126111,0.649829,0.694511,0.023224,0.000310,0.057097,0.012929,0.008026,0.030475,...,0.007351,0.088509,0.556798,0.192283,0.042265,0.103002,0.001494,0.392443,0.000000,0.052590
2,0.000000,0.000000,0.405181,0.836287,4.124795,0.007945,0.000000,0.003714,0.002770,0.026438,...,0.006715,0.044787,0.544515,0.088714,0.143255,0.056269,0.018553,0.658247,0.050502,0.113769
3,0.000000,2.308417,0.119431,0.120097,3.985985,0.015477,0.000000,0.004406,0.025324,0.015539,...,0.009446,0.125159,0.000000,0.071700,0.156441,0.074255,0.014709,0.105227,0.006118,0.081632
4,0.000000,0.000000,0.546531,1.292965,3.482252,0.010140,0.046020,0.018085,0.022204,0.046295,...,0.061491,0.027266,0.298706,0.421875,0.362350,0.100456,0.010704,0.897931,0.000000,0.181201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145474,0.000000,0.000000,0.132730,0.000000,0.000000,0.000000,0.024647,0.000000,0.000000,0.001994,...,0.002062,0.000000,0.025164,0.052784,0.000000,0.000000,0.000000,0.171280,0.000000,0.066642
145475,0.000000,2.239055,0.186252,0.369426,0.800173,0.016219,0.026338,0.019682,0.022974,0.000450,...,0.002169,0.031499,0.040721,0.270443,0.118005,0.139055,0.019971,0.630590,0.052803,0.172927
145476,0.024406,0.937475,0.406066,0.069124,2.025419,0.009820,0.002730,0.004958,0.010678,0.029238,...,0.000000,0.024329,0.136838,0.133530,0.076204,0.023668,0.002195,0.451703,0.004854,0.133263
145477,0.000000,0.000000,0.244838,0.000000,0.000000,0.002488,0.039718,0.000000,0.001914,0.000000,...,0.000000,0.004401,0.046355,0.000000,0.011181,0.003384,0.009216,0.004487,0.000000,0.025856
145478,1.075820,0.456346,0.333504,0.290401,4.403868,0.001839,0.002383,0.017212,0.001585,0.015016,...,0.007945,0.009559,0.214486,0.041203,0.143325,0.075504,0.005863,0.114854,0.000000,0.115488

In [17]:

# es_callback = EarlyStopping(monitor= 'val_auc', patience=20, restore_best_weights=True)
reduce_learning_rate = tf.keras.callbacks.ReduceLROnPlateau(factor=0.1, patience=25, monitor='loss', min_delta=100)

history = model.fit(W,AE_tcr, 
                epochs=3000, 
                batch_size=256, 
                shuffle = True,
                # callbacks=[es_callback, checkpoint,reduce_learning_rate])
                # callbacks=[reduce_learning_rate]
                )

Epoch 1/3000
569/569 [==============================] - 3s 4ms/step - loss: 265401.8750
Epoch 2/3000
569/569 [==============================] - 2s 4ms/step - loss: 247646.0938
Epoch 3/3000
569/569 [==============================] - 2s 4ms/step - loss: 247610.5000
Epoch 4/3000
569/569 [==============================] - 2s 4ms/step - loss: 247602.3906
Epoch 5/3000
569/569 [==============================] - 2s 4ms/step - loss: 247586.0938
Epoch 6/3000
569/569 [==============================] - 2s 4ms/step - loss: 247579.6250
Epoch 7/3000
569/569 [==============================] - 2s 4ms/step - loss: 247575.0000
Epoch 8/3000
569/569 [==============================] - 2s 4ms/step - loss: 247564.3281
Epoch 9/3000
569/569 [==============================] - 2s 4ms/step - loss: 247536.6875
Epoch 10/3000
569/569 [==============================] - 2s 4ms/step - loss: 247505.8594
Epoch 11/3000
569/569 [==============================] - 2s 4ms/step - loss: 247478.4219
Epoch 12/3000
569/569 [==============================] - 2s 4ms/step - loss: 246742.5000
Epoch 13/3000
569/569 [==============================] - 2s 4ms/step - loss: 244998.2031
Epoch 14/3000
569/569 [==============================] - 2s 4ms/step - loss: 244972.0781
Epoch 15/3000
569/569 [==============================] - 2s 4ms/step - loss: 244950.0312
Epoch 16/3000
569/569 [==============================] - 2s 4ms/step - loss: 244858.4688
Epoch 17/3000
569/569 [==============================] - 2s 4ms/step - loss: 244237.2188
Epoch 18/3000
569/569 [==============================] - 2s 4ms/step - loss: 243330.6562
Epoch 19/3000
569/569 [==============================] - 2s 4ms/step - loss: 242971.2500
Epoch 20/3000
569/569 [==============================] - 2s 4ms/step - loss: 242754.5625
Epoch 21/3000
569/569 [==============================] - 2s 4ms/step - loss: 242515.4688
Epoch 22/3000
569/569 [==============================] - 2s 4ms/step - loss: 242340.7969
Epoch 23/3000
569/569 [==============================] - 2s 4ms/step - loss: 242148.0469
Epoch 24/3000
569/569 [==============================] - 2s 4ms/step - loss: 241886.9688
Epoch 25/3000
569/569 [==============================] - 2s 4ms/step - loss: 241616.1719
Epoch 26/3000
569/569 [==============================] - 2s 4ms/step - loss: 241341.5156
Epoch 27/3000
569/569 [==============================] - 2s 4ms/step - loss: 241194.6562
Epoch 28/3000
569/569 [==============================] - 3s 5ms/step - loss: 241038.4219
Epoch 29/3000
569/569 [==============================] - 2s 4ms/step - loss: 240378.8594
Epoch 30/3000
569/569 [==============================] - 2s 4ms/step - loss: 240116.6406
Epoch 31/3000
569/569 [==============================] - 2s 4ms/step - loss: 239926.0000
Epoch 32/3000
569/569 [==============================] - 2s 4ms/step - loss: 239723.4219
Epoch 33/3000
569/569 [==============================] - 2s 4ms/step - loss: 239450.5156
Epoch 34/3000
569/569 [==============================] - 2s 4ms/step - loss: 239255.2656
Epoch 35/3000
569/569 [==============================] - 2s 4ms/step - loss: 239119.8594
Epoch 36/3000
569/569 [==============================] - 2s 4ms/step - loss: 238945.2500
Epoch 37/3000
569/569 [==============================] - 2s 4ms/step - loss: 238797.5469
Epoch 38/3000
569/569 [==============================] - 2s 4ms/step - loss: 238712.1719
Epoch 39/3000
569/569 [==============================] - 2s 4ms/step - loss: 238585.0312
Epoch 40/3000
569/569 [==============================] - 2s 4ms/step - loss: 238474.4844
Epoch 41/3000
569/569 [==============================] - 3s 5ms/step - loss: 238371.8906
Epoch 42/3000
569/569 [==============================] - 2s 4ms/step - loss: 238275.2656
Epoch 43/3000
569/569 [==============================] - 2s 4ms/step - loss: 238186.5938
Epoch 44/3000
569/569 [==============================] - 2s 4ms/step - loss: 238085.1562
Epoch 45/3000
569/569 [==============================] - 2s 4ms/step - loss: 238026.2031
Epoch 46/3000
569/569 [==============================] - 2s 4ms/step - loss: 237920.2500
Epoch 47/3000
569/569 [==============================] - 2s 4ms/step - loss: 237839.9844
Epoch 48/3000
569/569 [==============================] - 2s 4ms/step - loss: 237743.7188
Epoch 49/3000
569/569 [==============================] - 2s 4ms/step - loss: 237622.8125
Epoch 50/3000
569/569 [==============================] - 2s 4ms/step - loss: 237465.1719
Epoch 51/3000
569/569 [==============================] - 2s 4ms/step - loss: 237389.3906
Epoch 52/3000
569/569 [==============================] - 2s 4ms/step - loss: 237308.4375
Epoch 53/3000
569/569 [==============================] - 2s 4ms/step - loss: 237222.6250
Epoch 54/3000
569/569 [==============================] - 2s 4ms/step - loss: 237085.1094
Epoch 55/3000
569/569 [==============================] - 2s 4ms/step - loss: 237020.0781
Epoch 56/3000
569/569 [==============================] - 2s 4ms/step - loss: 236962.6406
Epoch 57/3000
569/569 [==============================] - 2s 4ms/step - loss: 236888.8125
Epoch 58/3000
569/569 [==============================] - 2s 4ms/step - loss: 236853.1719
Epoch 59/3000
569/569 [==============================] - 2s 4ms/step - loss: 236730.2188
Epoch 60/3000
569/569 [==============================] - 2s 4ms/step - loss: 236703.7500
Epoch 61/3000
569/569 [==============================] - 2s 4ms/step - loss: 236545.2656
Epoch 62/3000
569/569 [==============================] - 2s 4ms/step - loss: 236441.3438
Epoch 63/3000
569/569 [==============================] - 2s 4ms/step - loss: 236387.8750
Epoch 64/3000
569/569 [==============================] - 2s 4ms/step - loss: 236333.1875
Epoch 65/3000
569/569 [==============================] - 2s 4ms/step - loss: 236279.2500
Epoch 66/3000
569/569 [==============================] - 2s 4ms/step - loss: 236229.4375
Epoch 67/3000
569/569 [==============================] - 2s 4ms/step - loss: 236122.4219
Epoch 68/3000
569/569 [==============================] - 2s 4ms/step - loss: 236041.7812
Epoch 69/3000
569/569 [==============================] - 2s 4ms/step - loss: 235957.7344
Epoch 70/3000
569/569 [==============================] - 2s 4ms/step - loss: 235719.5312
Epoch 71/3000
569/569 [==============================] - 2s 4ms/step - loss: 235598.9688
Epoch 72/3000
569/569 [==============================] - 2s 4ms/step - loss: 235559.4844
Epoch 73/3000
569/569 [==============================] - 2s 4ms/step - loss: 235513.4531
Epoch 74/3000
569/569 [==============================] - 2s 4ms/step - loss: 235470.6406
Epoch 75/3000
569/569 [==============================] - 2s 4ms/step - loss: 235411.3125
Epoch 76/3000
569/569 [==============================] - 2s 4ms/step - loss: 235380.7656
Epoch 77/3000
569/569 [==============================] - 2s 4ms/step - loss: 235329.3125
Epoch 78/3000
569/569 [==============================] - 2s 4ms/step - loss: 235277.0781
Epoch 79/3000
569/569 [==============================] - 2s 4ms/step - loss: 235165.1406
Epoch 80/3000
569/569 [==============================] - 2s 4ms/step - loss: 234834.9844
Epoch 81/3000
569/569 [==============================] - 2s 4ms/step - loss: 234745.8594
Epoch 82/3000
569/569 [==============================] - 2s 4ms/step - loss: 234719.4688
Epoch 83/3000
569/569 [==============================] - 2s 4ms/step - loss: 234654.5625
Epoch 84/3000
569/569 [==============================] - 2s 4ms/step - loss: 234625.0625
Epoch 85/3000
569/569 [==============================] - 2s 4ms/step - loss: 234587.5469
Epoch 86/3000
569/569 [==============================] - 2s 4ms/step - loss: 234541.1406
Epoch 87/3000
569/569 [==============================] - 2s 4ms/step - loss: 234515.1250
Epoch 88/3000
569/569 [==============================] - 2s 4ms/step - loss: 234470.3906
Epoch 89/3000
569/569 [==============================] - 2s 4ms/step - loss: 234453.5000
Epoch 90/3000
569/569 [==============================] - 2s 4ms/step - loss: 234424.9844
Epoch 91/3000
569/569 [==============================] - 2s 4ms/step - loss: 234374.0625
Epoch 92/3000
569/569 [==============================] - 2s 4ms/step - loss: 234333.7812
Epoch 93/3000
569/569 [==============================] - 2s 4ms/step - loss: 234290.4531
Epoch 94/3000
569/569 [==============================] - 2s 4ms/step - loss: 234283.7656
Epoch 95/3000
569/569 [==============================] - 2s 4ms/step - loss: 234221.8750
Epoch 96/3000
569/569 [==============================] - 2s 4ms/step - loss: 234198.3281
Epoch 97/3000
569/569 [==============================] - 2s 4ms/step - loss: 234180.1406
Epoch 98/3000
569/569 [==============================] - 2s 4ms/step - loss: 234162.9375
Epoch 99/3000
569/569 [==============================] - 2s 4ms/step - loss: 234108.1875
Epoch 100/3000
569/569 [==============================] - 2s 4ms/step - loss: 234067.0312
Epoch 101/3000
569/569 [==============================] - 2s 4ms/step - loss: 234041.8125
Epoch 102/3000
569/569 [==============================] - 2s 4ms/step - loss: 234035.2969
Epoch 103/3000
569/569 [==============================] - 2s 4ms/step - loss: 233980.4375
Epoch 104/3000
569/569 [==============================] - 2s 4ms/step - loss: 233950.1250
Epoch 105/3000
569/569 [==============================] - 2s 4ms/step - loss: 233907.5000
Epoch 106/3000
569/569 [==============================] - 2s 4ms/step - loss: 233743.8906
Epoch 107/3000
569/569 [==============================] - 2s 4ms/step - loss: 233693.9219
Epoch 108/3000
569/569 [==============================] - 2s 4ms/step - loss: 233642.7344
Epoch 109/3000
569/569 [==============================] - 2s 4ms/step - loss: 233607.0000
Epoch 110/3000
569/569 [==============================] - 2s 4ms/step - loss: 233596.3750
Epoch 111/3000
569/569 [==============================] - 2s 4ms/step - loss: 233554.3438
Epoch 112/3000
569/569 [==============================] - 2s 4ms/step - loss: 233542.2188
Epoch 113/3000
569/569 [==============================] - 2s 4ms/step - loss: 233498.3750
Epoch 114/3000
569/569 [==============================] - 2s 4ms/step - loss: 233455.8438
Epoch 115/3000
569/569 [==============================] - 2s 4ms/step - loss: 233427.7031
Epoch 116/3000
569/569 [==============================] - 2s 4ms/step - loss: 233374.7188
Epoch 117/3000
569/569 [==============================] - 2s 4ms/step - loss: 233369.3906
Epoch 118/3000
569/569 [==============================] - 2s 4ms/step - loss: 233315.2188
Epoch 119/3000
569/569 [==============================] - 2s 4ms/step - loss: 233284.3750
Epoch 120/3000
569/569 [==============================] - 2s 4ms/step - loss: 233245.6250
Epoch 121/3000
569/569 [==============================] - 2s 4ms/step - loss: 233220.5312
Epoch 122/3000
569/569 [==============================] - 2s 4ms/step - loss: 233219.5781
Epoch 123/3000
569/569 [==============================] - 2s 4ms/step - loss: 233210.2188
Epoch 124/3000
569/569 [==============================] - 2s 4ms/step - loss: 233159.5000
Epoch 125/3000
569/569 [==============================] - 2s 4ms/step - loss: 233063.8594
Epoch 126/3000
569/569 [==============================] - 2s 4ms/step - loss: 233028.2969
Epoch 127/3000
569/569 [==============================] - 2s 4ms/step - loss: 233030.5469
Epoch 128/3000
569/569 [==============================] - 2s 4ms/step - loss: 232990.1250
Epoch 129/3000
569/569 [==============================] - 2s 4ms/step - loss: 232965.8438
Epoch 130/3000
569/569 [==============================] - 2s 4ms/step - loss: 232938.1875
Epoch 131/3000
569/569 [==============================] - 2s 4ms/step - loss: 232896.6094
Epoch 132/3000
569/569 [==============================] - 2s 4ms/step - loss: 232872.1875
Epoch 133/3000
569/569 [==============================] - 2s 4ms/step - loss: 232837.0156
Epoch 134/3000
569/569 [==============================] - 2s 4ms/step - loss: 232807.1719
Epoch 135/3000
569/569 [==============================] - 2s 4ms/step - loss: 232792.2656
Epoch 136/3000
569/569 [==============================] - 2s 4ms/step - loss: 232756.0938
Epoch 137/3000
569/569 [==============================] - 2s 4ms/step - loss: 232724.9531
Epoch 138/3000
569/569 [==============================] - 2s 4ms/step - loss: 232702.5312
Epoch 139/3000
569/569 [==============================] - 2s 4ms/step - loss: 232648.0781
Epoch 140/3000
569/569 [==============================] - 2s 4ms/step - loss: 232643.4375
Epoch 141/3000
569/569 [==============================] - 2s 4ms/step - loss: 232569.2656
Epoch 142/3000
569/569 [==============================] - 2s 4ms/step - loss: 232552.0625
Epoch 143/3000
569/569 [==============================] - 2s 4ms/step - loss: 232544.1406
Epoch 144/3000
569/569 [==============================] - 2s 4ms/step - loss: 232529.1406
Epoch 145/3000
569/569 [==============================] - 2s 4ms/step - loss: 232449.6406
Epoch 146/3000
569/569 [==============================] - 2s 4ms/step - loss: 232425.0938
Epoch 147/3000
569/569 [==============================] - 2s 4ms/step - loss: 232408.2969
Epoch 148/3000
569/569 [==============================] - 2s 4ms/step - loss: 232378.2031
Epoch 149/3000
569/569 [==============================] - 2s 4ms/step - loss: 232338.8750
Epoch 150/3000
569/569 [==============================] - 2s 4ms/step - loss: 232300.5000
Epoch 151/3000
569/569 [==============================] - 2s 4ms/step - loss: 232026.9375
Epoch 152/3000
569/569 [==============================] - 2s 4ms/step - loss: 231923.5938
Epoch 153/3000
569/569 [==============================] - 2s 4ms/step - loss: 231901.4219
Epoch 154/3000
569/569 [==============================] - 2s 4ms/step - loss: 231851.4062
Epoch 155/3000
569/569 [==============================] - 2s 4ms/step - loss: 231805.4375
Epoch 156/3000
569/569 [==============================] - 2s 4ms/step - loss: 231760.9531
Epoch 157/3000
569/569 [==============================] - 2s 4ms/step - loss: 231742.7344
Epoch 158/3000
569/569 [==============================] - 2s 4ms/step - loss: 231720.7812
Epoch 159/3000
569/569 [==============================] - 2s 4ms/step - loss: 231656.8281
Epoch 160/3000
569/569 [==============================] - 2s 4ms/step - loss: 231634.0625
Epoch 161/3000
569/569 [==============================] - 2s 4ms/step - loss: 231622.2344
Epoch 162/3000
569/569 [==============================] - 2s 4ms/step - loss: 231555.3750
Epoch 163/3000
569/569 [==============================] - 2s 4ms/step - loss: 231552.6719
Epoch 164/3000
569/569 [==============================] - 2s 4ms/step - loss: 231519.3125
Epoch 165/3000
569/569 [==============================] - 2s 4ms/step - loss: 231480.1250
Epoch 166/3000
569/569 [==============================] - 2s 4ms/step - loss: 231425.2031
Epoch 167/3000
569/569 [==============================] - 2s 4ms/step - loss: 231415.1250
Epoch 168/3000
569/569 [==============================] - 2s 4ms/step - loss: 231359.3594
Epoch 169/3000
569/569 [==============================] - 2s 4ms/step - loss: 231322.4375
Epoch 170/3000
569/569 [==============================] - 2s 4ms/step - loss: 231285.6094
Epoch 171/3000
569/569 [==============================] - 2s 4ms/step - loss: 231269.0156
Epoch 172/3000
569/569 [==============================] - 2s 4ms/step - loss: 231184.2969
Epoch 173/3000
569/569 [==============================] - 2s 4ms/step - loss: 231120.7344
Epoch 174/3000
569/569 [==============================] - 2s 4ms/step - loss: 231120.9688
Epoch 175/3000
569/569 [==============================] - 2s 4ms/step - loss: 231089.3750
Epoch 176/3000
569/569 [==============================] - 2s 4ms/step - loss: 231027.2812
Epoch 177/3000
569/569 [==============================] - 2s 4ms/step - loss: 230995.9375
Epoch 178/3000
569/569 [==============================] - 2s 4ms/step - loss: 230966.7656
Epoch 179/3000
569/569 [==============================] - 2s 4ms/step - loss: 230937.9844
Epoch 180/3000
569/569 [==============================] - 2s 4ms/step - loss: 230907.5781
Epoch 181/3000
569/569 [==============================] - 2s 4ms/step - loss: 230889.2969
Epoch 182/3000
569/569 [==============================] - 2s 4ms/step - loss: 230857.8750
Epoch 183/3000
569/569 [==============================] - 2s 4ms/step - loss: 230862.0781
Epoch 184/3000
569/569 [==============================] - 2s 4ms/step - loss: 230796.7500
Epoch 185/3000
569/569 [==============================] - 2s 4ms/step - loss: 230766.7500
Epoch 186/3000
569/569 [==============================] - 2s 4ms/step - loss: 230737.5625
Epoch 187/3000
569/569 [==============================] - 2s 4ms/step - loss: 230732.9062
Epoch 188/3000
569/569 [==============================] - 2s 4ms/step - loss: 230667.3906
Epoch 189/3000
569/569 [==============================] - 2s 4ms/step - loss: 230669.5312
Epoch 190/3000
569/569 [==============================] - 2s 4ms/step - loss: 230600.3125
Epoch 191/3000
569/569 [==============================] - 2s 4ms/step - loss: 230621.5469
Epoch 192/3000
569/569 [==============================] - 2s 4ms/step - loss: 230620.0781
Epoch 193/3000
569/569 [==============================] - 2s 4ms/step - loss: 230554.9375
Epoch 194/3000
569/569 [==============================] - 2s 4ms/step - loss: 230531.7812
Epoch 195/3000
569/569 [==============================] - 2s 4ms/step - loss: 230517.0000
Epoch 196/3000
569/569 [==============================] - 2s 4ms/step - loss: 230494.9844
Epoch 197/3000
569/569 [==============================] - 2s 4ms/step - loss: 230454.2344
Epoch 198/3000
569/569 [==============================] - 2s 4ms/step - loss: 230446.0625
Epoch 199/3000
569/569 [==============================] - 2s 4ms/step - loss: 230418.0469
Epoch 200/3000
569/569 [==============================] - 2s 4ms/step - loss: 230385.1094
Epoch 201/3000
569/569 [==============================] - 2s 4ms/step - loss: 230381.3750
Epoch 202/3000
569/569 [==============================] - 2s 4ms/step - loss: 230329.0625
Epoch 203/3000
569/569 [==============================] - 2s 3ms/step - loss: 230314.8906
Epoch 204/3000
569/569 [==============================] - 2s 3ms/step - loss: 230284.2188
Epoch 205/3000
569/569 [==============================] - 2s 3ms/step - loss: 230255.8438
Epoch 206/3000
569/569 [==============================] - 2s 4ms/step - loss: 230240.8125
Epoch 207/3000
569/569 [==============================] - 2s 3ms/step - loss: 230198.6875
Epoch 208/3000
569/569 [==============================] - 2s 3ms/step - loss: 230194.4531
Epoch 209/3000
569/569 [==============================] - 2s 3ms/step - loss: 230172.8281
Epoch 210/3000
569/569 [==============================] - 2s 3ms/step - loss: 230112.7344
Epoch 211/3000
569/569 [==============================] - 2s 3ms/step - loss: 230151.7500
Epoch 212/3000
569/569 [==============================] - 2s 3ms/step - loss: 230120.1094
Epoch 213/3000
569/569 [==============================] - 2s 3ms/step - loss: 230053.2812
Epoch 214/3000
569/569 [==============================] - 2s 3ms/step - loss: 230039.7188
Epoch 215/3000
569/569 [==============================] - 2s 4ms/step - loss: 230022.8594
Epoch 216/3000
569/569 [==============================] - 2s 4ms/step - loss: 229968.3438
Epoch 217/3000
569/569 [==============================] - 2s 3ms/step - loss: 229974.5469
Epoch 218/3000
569/569 [==============================] - 2s 3ms/step - loss: 229922.1875
Epoch 219/3000
569/569 [==============================] - 2s 3ms/step - loss: 229829.6094
Epoch 220/3000
569/569 [==============================] - 2s 4ms/step - loss: 229910.5938
Epoch 221/3000
569/569 [==============================] - 2s 3ms/step - loss: 229809.2656
Epoch 222/3000
569/569 [==============================] - 2s 3ms/step - loss: 229759.7344
Epoch 223/3000
569/569 [==============================] - 2s 3ms/step - loss: 229765.4375
Epoch 224/3000

In [18]:
for layer in model.layers:
    print(layer.name)

input_3
dense_10
reshape_4
conv2d_4
conv2d_5
flatten_4
dense_11
reshape_5
conv2d_transpose_4
conv2d_transpose_5
dropout_2
flatten_5
dense_12
dense_13
dense_14

In [19]:
from tensorflow.keras.models import Model
latent_model = Model(inputs=input_gex, outputs=hidden_layer)

In [20]:
model.predict( W.iloc[1:2])

1/1 [==============================] - 0s 281ms/step

array([[1.4161285e+00, 1.4728477e+01, 0.0000000e+00, 0.0000000e+00,
        1.1333625e+02, 1.3411736e+02, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 2.2403737e+02,
        3.4631618e+01, 1.0363980e+01, 0.0000000e+00, 8.1015961e+01,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.7631659e+02,
        0.0000000e+00, 6.7272713e+01, 0.0000000e+00, 1.3567583e+01,
        0.0000000e+00, 0.0000000e+00, 2.1936079e+02, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 2.9494916e+02,
        9.7496510e-03, 4.1074982e+00, 2.1382764e+02, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 1.7310286e+01, 2.2469633e+01,
        3.3231320e+02, 0.0000000e+00, 4.9780823e+01, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 1.2952959e+02, 5.0697479e+01,
        5.8972458e+01, 2.3102707e+02, 0.0000000e+00, 7.0421692e+01,
        1.8198050e+02, 0.0000000e+00, 0.0000000e+00, 1.0037173e+02,
        0.0000000e+00, 6.3402172e+01, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 2.3035638e+02, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 3.3935415e+03,
        0.0000000e+00, 0.0000000e+00, 1.3651697e+02, 0.0000000e+00,
        5.3706436e+01, 3.6167919e+01, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 2.7470648e+02, 0.0000000e+00,
        2.3058496e+02, 0.0000000e+00, 2.1565172e+02, 0.0000000e+00,
        0.0000000e+00, 6.1856299e+02, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        4.1276203e+01, 3.1613989e+02, 2.6824307e+02, 4.7791879e+02,
        6.5167352e+02, 0.0000000e+00, 4.8704018e+01, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 6.2805012e+01, 1.4266707e+02,
        0.0000000e+00, 1.7964198e+02, 2.9274008e+02, 8.5678162e+01,
        2.3131633e+00, 1.7780913e+02, 2.9889498e+01, 6.2172382e+01,
        4.9908304e+02, 0.0000000e+00, 1.2060072e+01, 0.0000000e+00,
        0.0000000e+00, 2.2465717e+02, 7.6137799e+02, 0.0000000e+00,
        0.0000000e+00]], dtype=float32)

In [21]:
model.predict( W.iloc[4:5])

1/1 [==============================] - 0s 29ms/step

array([[   0.      ,  174.24878 ,    0.      ,    0.      ,    0.      ,
           0.      ,    0.      ,    0.      ,    0.      ,   21.098475,
           0.      ,  473.93912 ,    0.      ,  310.0596  ,   19.797068,
          19.892818,    0.      ,   33.72309 ,    0.      ,  451.73447 ,
          79.50054 ,    0.      ,    0.      ,    0.      ,    0.      ,
           0.      ,  567.37665 ,    0.      ,    0.      ,    0.      ,
           0.      ,  488.4411  ,    0.      ,  406.46127 ,  226.22427 ,
           0.      ,  147.11958 ,    0.      ,  119.98261 ,  219.60951 ,
         566.93164 ,    0.      ,   77.6459  ,    0.      ,  150.1516  ,
           0.      ,  344.30066 ,    0.      ,  127.53725 ,  455.30582 ,
          80.05705 ,  161.16725 ,  416.7667  ,    0.      ,    0.      ,
         108.2167  ,   30.950115,  328.0904  ,   91.58552 ,  153.59523 ,
           0.      ,  260.20523 ,    0.      ,    0.      ,   24.666965,
           0.      ,    0.      , 3600.0847  ,    0.      ,    0.      ,
          87.17272 ,    0.      ,   24.645567,  152.94902 ,    0.      ,
          87.33054 ,    0.      ,    0.      ,  306.16687 ,   40.89264 ,
         325.52014 ,    0.      ,  188.08565 ,    0.      ,    0.      ,
         391.25644 ,    0.      ,    0.      ,    0.      ,    0.      ,
         179.47379 ,    0.      ,  156.63866 ,  566.38837 ,  375.51993 ,
         597.09686 , 1147.367   ,    0.      ,    0.      ,    0.      ,
           0.      ,    0.      ,  187.14398 ,  332.24246 ,    0.      ,
         569.79987 ,  480.74683 ,  114.138016,    0.      ,  366.01178 ,
         259.20587 ,  346.30826 ,  802.4158  ,  138.00447 ,    0.      ,
           0.      ,    0.      ,  752.62415 ,  958.8006  ,    0.      ,
           0.      ]], dtype=float32)

In [22]:
integration_pred = latent_model.predict( W)

4547/4547 [==============================] - 5s 983us/step

In [23]:
pd.DataFrame(integration_pred[1:50,1:50])

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,0.000000,0.0,0.0,3.701933,9.362439,13.073524,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,1.064706,0.0,0.000000,0.000000,3.154169
1,0.000000,0.0,0.0,1.647828,2.164470,14.929717,0.0,0.0,0.000000,0.0,...,3.197256,0.000000,0.000000,0.0,0.000000,5.914854,0.0,3.724772,0.000000,0.000000
2,0.942395,0.0,0.0,4.074978,7.017201,4.498881,0.0,0.0,3.047668,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.718090,0.0,0.000000,0.000000,0.000000
3,6.829710,0.0,0.0,0.000000,0.033535,4.822514,0.0,0.0,2.093441,0.0,...,1.865396,0.000000,16.174997,0.0,0.000000,4.308629,0.0,5.155125,2.983720,0.000000
4,2.266372,0.0,0.0,1.287762,3.185766,4.524041,0.0,0.0,0.093549,0.0,...,2.064587,0.000000,3.668772,0.0,0.000000,5.566699,0.0,1.957512,5.690331,0.000000
5,0.000000,0.0,0.0,0.085645,0.547467,4.704464,0.0,0.0,0.000000,0.0,...,1.703755,0.000000,0.000000,0.0,0.381489,2.377525,0.0,5.272830,0.000000,2.012871
6,0.000000,0.0,0.0,0.000000,6.943415,8.848470,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,5.178318,0.0,0.547465,0.698390,0.000000
7,0.176724,0.0,0.0,1.368825,3.738276,0.368692,0.0,0.0,1.994269,0.0,...,0.000000,0.000000,0.000000,0.0,3.943576,4.909998,0.0,0.000000,2.257046,1.336611
8,0.000000,0.0,0.0,0.000000,0.772625,1.925091,0.0,0.0,0.000000,0.0,...,0.000000,1.209625,3.322177,0.0,0.633170,4.440424,0.0,3.146820,2.106181,0.000000
9,0.000000,0.0,0.0,2.363780,5.307608,8.065827,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,4.300633,0.0,2.084829,0.000000,0.000000
10,0.000000,0.0,0.0,0.000000,6.629670,4.448581,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,3.368103,0.000000,0.0,0.000000,0.000000,0.000000
11,4.411447,0.0,0.0,0.000000,4.290316,4.350180,0.0,0.0,1.860075,0.0,...,5.513765,0.000000,4.669794,0.0,3.410924,1.863488,0.0,3.058588,6.691453,1.050720
12,2.020546,0.0,0.0,0.906255,0.133584,0.019889,0.0,0.0,0.862486,0.0,...,1.937603,0.000000,0.000000,0.0,0.000000,1.134416,0.0,0.000000,2.434535,0.000000
13,0.000000,0.0,0.0,3.515905,3.351940,6.421131,0.0,0.0,1.808686,0.0,...,2.359220,0.000000,2.634679,0.0,1.105815,3.238353,0.0,0.000000,0.000000,0.000000
14,0.000000,0.0,0.0,3.480650,3.590272,5.830298,0.0,0.0,0.873966,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.911217,0.0,0.000000,0.000000,0.000000
15,1.515939,0.0,0.0,1.191389,1.669453,5.731090,0.0,0.0,0.000000,0.0,...,0.939726,4.548232,0.074698,0.0,1.368464,5.118366,0.0,0.034526,2.563798,0.000000
16,0.000000,0.0,0.0,0.000000,5.295931,0.133170,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,1.675666,0.0,0.000000,6.234473,0.000000
17,0.239600,0.0,0.0,7.643393,1.729790,10.482022,0.0,0.0,0.493624,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
18,0.000000,0.0,0.0,4.107968,5.492026,5.723028,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,5.014536,0.0,0.000000,0.000000,0.000000
19,9.158015,0.0,0.0,2.003034,7.985902,1.929437,0.0,0.0,1.877313,0.0,...,3.257147,0.000000,14.335203,0.0,2.058252,4.357425,0.0,2.426593,2.050989,2.833390
20,0.000000,0.0,0.0,8.145164,3.046954,3.693825,0.0,0.0,3.977376,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,1.069208,0.0,0.000000,0.000000,0.000000
21,2.799131,0.0,0.0,6.513453,8.261513,5.399414,0.0,0.0,0.000000,0.0,...,0.343339,0.000000,4.105841,0.0,0.000000,2.869114,0.0,0.688651,0.000000,0.761820
22,0.000000,0.0,0.0,0.000000,4.629928,8.689012,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,1.625906,0.602254,0.0,0.000000,1.014108,0.074358
23,1.889226,0.0,0.0,0.000000,0.705800,4.984628,0.0,0.0,0.000000,0.0,...,1.455388,0.528858,2.960678,0.0,1.750403,3.174131,0.0,3.506808,9.049591,0.000000
24,0.000000,0.0,0.0,2.670840,0.971413,10.509162,0.0,0.0,0.000000,0.0,...,5.345781,3.143277,2.445784,0.0,0.314636,4.821111,0.0,2.961331,0.000000,2.815120
25,0.180755,0.0,0.0,0.807907,7.019026,6.197093,0.0,0.0,1.980009,0.0,...,0.000000,0.000000,0.000000,0.0,2.350233,3.670579,0.0,2.054796,0.000000,2.319479
26,11.668575,0.0,0.0,1.293476,6.148946,0.000000,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.474406,0.0,0.000000,0.000000,0.0,6.144311,0.000000,0.000000
27,0.000000,0.0,0.0,0.000000,2.875070,6.844918,0.0,0.0,0.000000,0.0,...,0.000000,1.107472,0.000000,0.0,0.000000,3.864375,0.0,0.000000,6.136003,0.000000
28,1.539231,0.0,0.0,0.000000,1.446596,5.168429,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,5.480255,0.0,0.946557,0.000000,0.000000
29,0.000000,0.0,0.0,1.324620,3.204950,8.656315,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,2.294661,4.728731,0.0,0.000000,0.000000,0.000000
30,0.000000,0.0,0.0,3.442945,1.640135,15.737350,0.0,0.0,0.000000,0.0,...,4.798447,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,3.697781
31,0.000000,0.0,0.0,0.000000,4.005383,1.076526,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.762430,0.0,3.699369,0.000000,0.000000
32,1.751167,0.0,0.0,0.000000,2.702647,2.585530,0.0,0.0,0.000000,0.0,...,2.013605,0.000000,4.063749,0.0,5.624095,1.671425,0.0,2.937214,4.239435,2.521259
33,0.000000,0.0,0.0,0.000000,5.961047,4.631100,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,3.684750,0.0,0.000000,0.000000,0.523737
34,0.000000,0.0,0.0,0.000000,0.000000,7.631484,0.0,0.0,0.000000,0.0,...,0.159356,0.000000,1.189301,0.0,1.016618,4.282873,0.0,0.748676,0.000000,0.000000
35,0.000000,0.0,0.0,4.621584,0.000000,7.482611,0.0,0.0,0.000000,0.0,...,1.584006,2.977190,0.000000,0.0,0.000000,3.257485,0.0,1.525168,0.000000,0.272720
36,0.000000,0.0,0.0,7.080562,6.998673,15.402891,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,3.071023,0.0,0.000000,0.213828,4.685262
37,2.360483,0.0,0.0,0.000000,0.227447,3.155391,0.0,0.0,0.161622,0.0,...,1.290355,3.519377,1.510094,0.0,2.414110,3.220118,0.0,2.631315,4.475466,0.349675
38,0.000000,0.0,0.0,0.000000,11.721333,12.021560,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,5.138562
39,0.000000,0.0,0.0,0.000000,5.512610,4.934310,0.0,0.0,0.000000,0.0,...,3.428807,0.000000,0.375058,0.0,3.477784,5.188530,0.0,0.000000,7.249453,0.000000
40,0.000000,0.0,0.0,0.828384,3.678485,8.220988,0.0,0.0,0.000000,0.0,...,2.463354,0.000000,0.000000,0.0,0.000000,4.595574,0.0,5.800242,0.000000,0.542373
41,7.739772,0.0,0.0,2.460158,2.576036,2.374393,0.0,0.0,2.809076,0.0,...,0.000000,0.000000,8.286990,0.0,4.515871,7.373478,0.0,0.000000,3.207603,0.354051
42,0.000000,0.0,0.0,6.922713,0.480163,17.499378,0.0,0.0,0.000000,0.0,...,0.724717,1.237905,0.000000,0.0,0.000000,4.525254,0.0,0.000000,0.000000,1.963670
43,0.000000,0.0,0.0,5.983740,3.107594,13.223029,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
44,0.000000,0.0,0.0,0.000000,4.798679,8.831272,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,5.979114,0.0,5.117118,0.000000,1.411369
45,0.000000,0.0,0.0,0.000000,1.333035,0.000000,0.0,0.0,3.344766,0.0,...,1.020460,0.000000,5.958398,0.0,7.404221,4.653326,0.0,1.990682,9.466281,5.233542
46,0.680238,0.0,0.0,0.000000,3.603500,4.228805,0.0,0.0,0.000000,0.0,...,0.169533,0.000000,0.000000,0.0,1.612516,3.331466,0.0,0.972860,0.000000,0.000000
47,0.000000,0.0,0.0,1.614950,15.007895,18.637121,0.0,0.0,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,1.899922,0.0,0.000000,4.706549,5.445868
48,0.000000,0.0,0.0,0.140694,3.117366,5.555142,0.0,0.0,1.408668,0.0,...,3.197400,0.000000,0.000000,0.0,1.365622,3.095718,0.0,0.000000,2.009260,2.598889

In [24]:
integration_pred = integration_pred.reshape([integration_pred.shape[0],-1])

In [25]:
integration_pred.shape

(145479, 64)

In [26]:
integration_pred = integration_pred.reshape([integration_pred.shape[0],-1])
integration_pred.shape

(145479, 64)

In [27]:
pd.DataFrame(integration_pred)

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,4.672718,0.000000,0.0,0.0,6.857419,1.872721,6.280306,0.0,0.0,2.004314,...,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000
1,0.000000,0.000000,0.0,0.0,3.701933,9.362439,13.073524,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,10.413274
2,2.364559,0.000000,0.0,0.0,1.647828,2.164470,14.929717,0.0,0.0,0.000000,...,0.0,3.946451,0.0,0.0,0.000000,0.0,1.942125,0.000000,0.0,6.559614
3,9.046071,0.942395,0.0,0.0,4.074978,7.017201,4.498881,0.0,0.0,3.047668,...,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.118451,0.0,2.342225
4,0.000000,6.829710,0.0,0.0,0.000000,0.033535,4.822514,0.0,0.0,2.093441,...,0.0,0.000000,0.0,0.0,12.873353,0.0,3.674380,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145474,0.000000,1.919112,0.0,0.0,2.697479,8.671455,5.111042,0.0,0.0,0.296422,...,0.0,4.186335,0.0,0.0,0.000000,0.0,1.781378,6.192757,0.0,0.806127
145475,0.000000,0.000000,0.0,0.0,2.046324,5.926474,10.747284,0.0,0.0,0.000000,...,0.0,0.821332,0.0,0.0,0.000000,0.0,5.394743,1.891414,0.0,10.415553
145476,0.000000,2.299400,0.0,0.0,0.000000,1.161693,1.747009,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.000000,0.0,7.276559,2.727138,0.0,8.348395
145477,0.000000,0.000000,0.0,0.0,0.000000,7.797906,8.841404,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.000000,0.0,2.543676,0.305229,0.0,4.229376
145478,0.000000,6.126895,0.0,0.0,2.732969,2.296522,1.577272,0.0,0.0,0.700064,...,0.0,2.664397,0.0,0.0,0.000000,0.0,5.658577,4.418759,0.0,2.890531

In [28]:
pd.DataFrame(integration_pred).to_csv("integration_pred_new_method_gex_to_TCR_beta_chain_10X_all_peptides_64_03032026.csv", index=False)