In this work, we use transformer model to integrate gene expression and TCR amino acid sequences

Getting gene data

In [1]:
# %matplotlib inline

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import os 
import numpy as np

import pandas as pd
# import seaborn as sb
import matplotlib.pyplot as pl

import scanpy as sc

import anndata as ad

from scipy.sparse import csr_matrix
from matplotlib import rcParams
from matplotlib import colors

sc.settings.verbosity = 3

In [2]:
gene_TCR = ad.read_h5ad('../10Xdatasets/gex_merge_log1_5000_genes_all_peptides.h5ad')
gene_TCR

/home/phile/miniconda3/envs/integration/lib/python3.9/site-packages/anndata/_core/anndata.py:1754: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

AnnData object with n_obs × n_vars = 145479 × 5000
    obs: 'v_gene_TRA', 'v_gene_TRB', 'd_gene_TRA', 'd_gene_TRB', 'j_gene_TRA', 'j_gene_TRB', 'c_gene_TRA', 'c_gene_TRB', 'cdr3_TRA', 'cdr3_TRB', 'cdr3_nt_TRA', 'cdr3_nt_TRB', 'umis_TRA', 'umis_TRB', 'donor', 'cell_clono_cdr3_aa', 'cell_clono_cdr3_nt', 'CD3', 'CD19', 'CD45RA', 'CD4', 'CD8a', 'CD14', 'CD45RO', 'CD279_PD-1', 'IgG1', 'IgG2a', 'IgG2b', 'CD127', 'CD197_CCR7', 'HLA-DR', 'A0101_VTEHDTLLY_IE-1_CMV', 'A0201_KTWGQYWQV_gp100_Cancer', 'A0201_ELAGIGILTV_MART-1_Cancer', 'A0201_CLLWSFQTSA_Tyrosinase_Cancer', 'A0201_IMDQVPFSV_gp100_Cancer', 'A0201_SLLMWITQV_NY-ESO-1_Cancer', 'A0201_KVAELVHFL_MAGE-A3_Cancer', 'A0201_KVLEYVIKV_MAGE-A1_Cancer', 'A0201_CLLGTYTQDV_Kanamycin-B-dioxygenase', 'A0201_LLDFVRFMGV_EBNA-3B_EBV', 'A0201_LLMGTLGIVC_HPV-16E7_82-91', 'A0201_CLGGLLTMV_LMP-2A_EBV', 'A0201_YLLEMLWRL_LMP1_EBV', 'A0201_FLYALALLL_LMP2A_EBV', 'A0201_GILGFVFTL_Flu-MP_Influenza', 'A0201_GLCTLVAML_BMLF1_EBV', 'A0201_NLVPMVATV_pp65_CMV', 'A0201_ILKEPVHGV_RT_HIV', 'A0201_FLASKIGRLV_Ca2-indepen-Plip-A2', 'A2402_CYTWNQMNL_WT1-(235-243)236M_Y', 'A0201_RTLNAWVKV_Gag-protein_HIV', 'A0201_KLQCVDLHV_PSA146-154', 'A0201_LLFGYPVYV_HTLV-1', 'A0201_SLFNTVATL_Gag-protein_HIV', 'A0201_SLYNTVATLY_Gag-protein_HIV', 'A0201_SLFNTVATLY_Gag-protein_HIV', 'A0201_RMFPNAPYL_WT-1', 'A0201_YLNDHLEPWI_BCL-X_Cancer', 'A0201_MLDLQPETT_16E7_HPV', 'A0301_KLGGALQAK_IE-1_CMV', 'A0301_RLRAEAQVK_EMNA-3A_EBV', 'A0301_RIAAWMATY_BCL-2L1_Cancer', 'A1101_IVTDFSVIK_EBNA-3B_EBV', 'A1101_AVFDRKSDAK_EBNA-3B_EBV', 'B3501_IPSINVHHY_pp65_CMV', 'A2402_AYAQKIFKI_IE-1_CMV', 'A2402_QYDPVAALF_pp65_CMV', 'B0702_QPRAPIRPI_EBNA-6_EBV', 'B0702_TPRVTGGGAM_pp65_CMV', 'B0702_RPPIFIRRL_EBNA-3A_EBV', 'B0702_RPHERNGFTVL_pp65_CMV', 'B0801_RAKFKQLL_BZLF1_EBV', 'B0801_ELRRKMMYM_IE-1_CMV', 'B0801_FLRGRAYGL_EBNA-3A_EBV', 'A0101_SLEGGGLGY_NC', 'A0101_STEGGGLAY_NC', 'A0201_ALIAPVHAV_NC', 'A2402_AYSSAGASI_NC', 'B0702_GPAESAAGL_NC', 'NR(B0801)_AAKGRGAAL_NC', 'antigen', 'peptide', 'orig_ix', 'n_counts', 'log_counts', 'n_genes', 'mt_fraction'
    var: 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection'
    uns: 'donor_colors', 'hvg', 'log1p'
    layers: 'raw_counts'

In [3]:
gene = pd.DataFrame(gene_TCR.layers['raw_counts'].todense())
gene

,0,1,2,3,4,5,6,7,8,9,...,4990,4991,4992,4993,4994,4995,4996,4997,4998,4999
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,1.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0
4,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145474,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
145475,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,5.0,3.0,0.0,0.0
145476,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
145477,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0
145478,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0

In [4]:
tcr_seq = gene_TCR.obs[['cdr3_TRA']]
tcr_seq

                             cdr3_TRA
barcode
AGGGTGAGTATTACCG-18    CALSEASGTYKYIF
CTTGGCTTCGTTGCCT-25     CAAILFGNEKLTF
ACGATACTCGCAGGCT-40     CALSADTGNQFYF
ACGCCAGTCATGTCTT-8   CAMNPAWGGATNKLIF
TTCTTAGCAAAGAATC-4     CAETALGNTGKLIF
...                               ...
GAAGCAGAGCAGGCTA-3      CAVEPLYGNKLVF
CAGTCCTTCATCACCC-8     CAATHASGYDKVIF
GACTACACACGGTAAG-3    CAVDLMKTSYDKVIF
ATCGAGTAGTTTCCTT-4     CAVREGRGTDKLIF
ACCCACTTCTTGGGTA-3   CAVNWEEQGGSYIPTF

[145479 rows x 1 columns]

In [5]:
import tensorflow as tf

2025-07-22 21:03:39.591312: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-07-22 21:03:39.795727: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-07-22 21:03:39.887798: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

In [6]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Reshape, Conv2D, Conv2DTranspose, Flatten, Dropout
from tensorflow.keras.initializers import HeNormal
# Define input layer
input_gex = Input(shape=(100,))
gex = Dense(units=64, activation='relu', kernel_initializer=HeNormal())(input_gex)
gex = Reshape(target_shape=(8,8,1))(gex)

# Convolutional layers
gex = Conv2D(filters=64, kernel_size=3, strides=1, activation='relu', padding="same")(gex)
gex = Conv2D(filters=32, kernel_size=3, strides=1, activation='relu', padding="same")(gex)

gex = Flatten()(gex)
hidden_layer = Dense(units=225, activation='relu', kernel_initializer=HeNormal())(gex)

# Transposed Convolutional layers
tcr = Reshape(target_shape=(15,15,1))(hidden_layer)
tcr = Conv2DTranspose(filters=16, kernel_size=3, strides=1, activation='relu', padding="same")(tcr)
tcr = Conv2DTranspose(filters=32, kernel_size=3, strides=1, activation='relu', padding="same")(tcr)
tcr = Dropout(rate=0.2)(tcr)
tcr = Flatten()(tcr)
tcr = Dense(units=150, activation='relu', kernel_initializer=HeNormal())(tcr)
tcr = Dense(units=130, activation='relu')(tcr)  # Ensure proper activation
tcr = Dense(units=121, activation='relu')(tcr)
# Define model
model = Model(inputs=input_gex, outputs=tcr)
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0015),
              loss='mse')

# Check layer names
model.summary()

2025-07-22 21:03:42.184534: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-07-22 21:03:42.329306: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21210 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:17:00.0, compute capability: 8.6

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_1 (InputLayer)        [(None, 100)]             0

 dense (Dense)               (None, 64)                6464

 reshape (Reshape)           (None, 8, 8, 1)           0

 conv2d (Conv2D)             (None, 8, 8, 64)          640

 conv2d_1 (Conv2D)           (None, 8, 8, 32)          18464

 flatten (Flatten)           (None, 2048)              0

 dense_1 (Dense)             (None, 225)               461025

 reshape_1 (Reshape)         (None, 15, 15, 1)         0

 conv2d_transpose (Conv2DTra  (None, 15, 15, 16)       160
 nspose)

 conv2d_transpose_1 (Conv2DT  (None, 15, 15, 32)       4640
 ranspose)

 dropout (Dropout)           (None, 15, 15, 32)        0

 flatten_1 (Flatten)         (None, 7200)              0

 dense_2 (Dense)             (None, 150)               1080150

 dense_3 (Dense)             (None, 130)               19630

 dense_4 (Dense)             (None, 121)               15851

=================================================================
Total params: 1,607,024
Trainable params: 1,607,024
Non-trainable params: 0
_________________________________________________________________

In [7]:
# import tensorflow as tf
# from tensorflow.keras.models import Model
# from tensorflow.keras.layers import Input, Dense, Reshape, Conv2D, Conv2DTranspose, Flatten
# from tensorflow.keras.initializers import HeNormal

# # Define input layer
# input_gex = Input(shape=(100,))
# gex = Dense(units=64, activation='relu', kernel_initializer=HeNormal())(input_gex)
# gex = Reshape(target_shape=(8,8,1))(gex)

# # Convolutional layers
# gex = Conv2D(filters=64, kernel_size=3, strides=1, activation='relu', padding="same")(gex)
# gex = Conv2D(filters=32, kernel_size=3, strides=1, activation='relu', padding="same")(gex)

# gex = Flatten()(gex)
# hidden_layer = Dense(units=64, activation='relu', kernel_initializer=HeNormal())(gex)

# # Transposed Convolutional layers
# tcr = Reshape(target_shape=(8,8,1))(hidden_layer)
# tcr = Conv2DTranspose(filters=16, kernel_size=3, strides=1, activation='relu', padding="same")(tcr)
# tcr = Conv2DTranspose(filters=32, kernel_size=3, strides=1, activation='relu', padding="same")(tcr)

# tcr = Flatten()(tcr)
# tcr = Dense(units=64, activation='relu', kernel_initializer=HeNormal())(tcr)
# tcr = Dense(units=121)(tcr)  # Ensure proper activation

# # Define model
# model = Model(inputs=input_gex, outputs=tcr)
# model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
#               loss='mse')

# # Check layer names
# model.summary()

In [8]:
AE_tcr = pd.read_csv("../AE_emb_TRA_all_peptides_10X_all_donors.csv")
AE_tcr

,0,1,2,3,4,5,6,7,8,9,...,111,112,113,114,115,116,117,118,119,120
0,-316.207800,-800.64910,-320.83533,346.98510,705.439450,464.974000,809.040000,-895.359200,-1054.613000,63.288700,...,116.577480,1000.989600,194.82726,-46.40611,-925.15344,504.46783,242.50058,807.05420,-840.84436,563.784200
1,107.312775,-176.85265,102.58903,259.01474,-389.094970,-170.045550,578.626900,-56.362595,119.735520,-1107.644800,...,596.523200,114.596214,178.70210,-618.82056,-126.63640,694.53640,458.34180,163.17456,-900.83606,-564.017150
2,-682.544400,126.96287,-266.74478,811.06690,54.793247,1033.749500,-5.409876,-477.162020,-626.985600,107.843820,...,25.007103,342.110350,701.48700,-220.56151,-274.78030,223.89500,-241.35388,-33.82157,-857.79560,44.841785
3,-239.374860,-539.07450,575.21450,-95.55604,-700.538450,-136.053050,-1057.042000,104.907840,-1014.197700,359.407930,...,-398.675840,270.228850,-488.31903,38.05454,-748.61510,135.54909,-319.03033,407.83580,-370.18942,-125.665770
4,-610.030900,-91.12127,-39.60043,-118.94101,455.614140,164.932970,550.304100,-489.563350,6.282069,-311.035920,...,50.310820,-81.869070,1121.82230,378.41960,260.26187,643.58246,611.14950,1115.37130,-1020.05316,133.965320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145474,-74.493700,981.68530,-577.37530,80.77775,-110.932080,-38.066833,293.816070,61.911617,-337.861570,552.293460,...,382.998200,227.379090,154.56630,-429.43268,-259.98810,458.89886,763.64197,602.20220,-777.30910,-1238.829200
145475,-1575.272600,363.77660,-873.83280,562.79400,-473.024100,-72.573760,336.400300,-1090.651400,395.956420,50.373066,...,-234.910930,625.048600,776.61240,287.09317,225.88951,1206.85420,-217.31377,1682.24980,-1090.58060,598.500000
145476,480.570680,-144.17064,119.83445,589.88513,-349.911400,-180.624530,649.415160,95.300840,-695.461100,-119.363530,...,-441.681460,834.983200,751.47670,-261.79773,697.58650,-201.78462,1361.48830,-67.69755,-651.23334,-256.774750
145477,-1076.087000,497.47763,376.98120,179.86403,100.149270,-1056.312600,410.896270,-764.348200,615.423300,-425.644530,...,490.229200,867.736760,362.18200,-200.04040,540.37300,751.93810,-323.77700,1519.47960,-1185.24760,764.347050
145478,1097.766200,-239.16643,179.04736,490.30347,118.410020,-858.095700,436.422600,20.929373,-67.992740,-689.179900,...,-545.761500,1205.361700,-457.14023,-133.04083,467.47968,377.96988,208.01460,1627.13680,-440.96906,-260.932770

In [9]:
import numpy as np
from sklearn.decomposition import NMF

# Generate random non-negative data
data = gene.to_numpy()

# Initialize the NMF model
n_components = 100
model_nmf = NMF(n_components=n_components, init='random', random_state=0)

# Fit the model to the data
W = model_nmf.fit_transform(data)
H = model_nmf.components_

# Display the results
print("Basis matrix (W):\n", W)
print("Coefficients matrix (H):\n", H)

KeyboardInterrupt:

In [ ]:
W = pd.DataFrame(W)
W

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.227333,7.086625,0.466240,0.436161,0.334158,0.003627,0.198576,0.001280,0.004045,0.002781,...,0.004944,0.033126,0.143294,0.116318,0.053315,0.090684,0.018362,0.296472,0.013140,0.083483
1,1.316014,5.126111,0.649829,0.694511,0.023224,0.000310,0.057097,0.012929,0.008026,0.030475,...,0.007351,0.088509,0.556798,0.192283,0.042265,0.103002,0.001494,0.392443,0.000000,0.052590
2,0.000000,0.000000,0.405181,0.836287,4.124795,0.007945,0.000000,0.003714,0.002770,0.026438,...,0.006715,0.044787,0.544515,0.088714,0.143255,0.056269,0.018553,0.658247,0.050502,0.113769
3,0.000000,2.308417,0.119431,0.120097,3.985986,0.015477,0.000000,0.004406,0.025324,0.015539,...,0.009446,0.125159,0.000000,0.071700,0.156441,0.074255,0.014709,0.105227,0.006118,0.081632
4,0.000000,0.000000,0.546531,1.292965,3.482252,0.010140,0.046020,0.018085,0.022204,0.046295,...,0.061491,0.027266,0.298706,0.421875,0.362350,0.100456,0.010704,0.897931,0.000000,0.181201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145474,0.000000,0.000000,0.132730,0.000000,0.000000,0.000000,0.024647,0.000000,0.000000,0.001994,...,0.002062,0.000000,0.025164,0.052784,0.000000,0.000000,0.000000,0.171280,0.000000,0.066642
145475,0.000000,2.239055,0.186252,0.369426,0.800173,0.016219,0.026338,0.019682,0.022974,0.000450,...,0.002169,0.031499,0.040721,0.270443,0.118005,0.139055,0.019971,0.630590,0.052803,0.172927
145476,0.024406,0.937475,0.406066,0.069124,2.025419,0.009820,0.002730,0.004958,0.010678,0.029238,...,0.000000,0.024329,0.136838,0.133530,0.076204,0.023668,0.002195,0.451703,0.004854,0.133263
145477,0.000000,0.000000,0.244838,0.000000,0.000000,0.002488,0.039718,0.000000,0.001914,0.000000,...,0.000000,0.004401,0.046355,0.000000,0.011181,0.003384,0.009216,0.004487,0.000000,0.025856
145478,1.075820,0.456346,0.333504,0.290401,4.403868,0.001839,0.002383,0.017212,0.001585,0.015016,...,0.007945,0.009559,0.214486,0.041203,0.143325,0.075504,0.005863,0.114854,0.000000,0.115488

In [ ]:

# es_callback = EarlyStopping(monitor= 'val_auc', patience=20, restore_best_weights=True)
reduce_learning_rate = tf.keras.callbacks.ReduceLROnPlateau(factor=0.1, patience=5, monitor='loss', min_delta=0.01)

history = model.fit(W,AE_tcr, 
                epochs=1400, 
                batch_size=128, 
                shuffle = True
                # callbacks=[es_callback, checkpoint,reduce_learning_rate])
                # callbacks=[es_callback,reduce_learning_rate]
                )

Epoch 1/1400

2025-07-22 17:50:22.584791: I tensorflow/stream_executor/cuda/cuda_blas.cc:1614] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
2025-07-22 17:50:23.270978: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8100
2025-07-22 17:50:24.091258: I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory

1137/1137 [==============================] - 13s 9ms/step - loss: 279383.5938
Epoch 2/1400
1137/1137 [==============================] - 10s 9ms/step - loss: 277509.1875
Epoch 3/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 274531.1562
Epoch 4/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 267725.0312
Epoch 5/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 265712.2812
Epoch 6/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 264239.3125
Epoch 7/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 263086.3750
Epoch 8/1400
1137/1137 [==============================] - 10s 9ms/step - loss: 262111.7031
Epoch 9/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 261307.1094
Epoch 10/1400
1137/1137 [==============================] - 10s 9ms/step - loss: 260619.1875
Epoch 11/1400
1137/1137 [==============================] - 10s 9ms/step - loss: 260122.8438
Epoch 12/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 259622.7500
Epoch 13/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 259212.2188
Epoch 14/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 258651.9531
Epoch 15/1400
1137/1137 [==============================] - 11s 9ms/step - loss: 256986.7656
Epoch 16/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 256526.0625
Epoch 17/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 256275.1719
Epoch 18/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 256002.3750
Epoch 19/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 255695.3750
Epoch 20/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 255325.4375
Epoch 21/1400
1137/1137 [==============================] - 11s 9ms/step - loss: 255125.2812
Epoch 22/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 254702.9062
Epoch 23/1400
1137/1137 [==============================] - 9s 8ms/step - loss: 254461.7188
Epoch 24/1400
1137/1137 [==============================] - 10s 9ms/step - loss: 254235.8125
Epoch 25/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 254007.3594
Epoch 26/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 253760.0938
Epoch 27/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 253450.5000
Epoch 28/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 253252.7969
Epoch 29/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 253074.0938
Epoch 30/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 252827.7344
Epoch 31/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 252659.3125
Epoch 32/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 252382.9375
Epoch 33/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 252163.3594
Epoch 34/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 251959.7969
Epoch 35/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 251498.4688
Epoch 36/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 250752.2969
Epoch 37/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 250509.6875
Epoch 38/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 250208.6719
Epoch 39/1400
1137/1137 [==============================] - 11s 9ms/step - loss: 249896.6250
Epoch 40/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 249638.1562
Epoch 41/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 249399.2344
Epoch 42/1400
1137/1137 [==============================] - 11s 9ms/step - loss: 249207.0000
Epoch 43/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 248997.3750
Epoch 44/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 248700.0000
Epoch 45/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 248435.4219
Epoch 46/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 248233.1562
Epoch 47/1400
1137/1137 [==============================] - 11s 9ms/step - loss: 248055.6719
Epoch 48/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 247732.7344
Epoch 49/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 247522.3438
Epoch 50/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 247060.6875
Epoch 51/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 246767.0625
Epoch 52/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 246610.1250
Epoch 53/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 246284.7031
Epoch 54/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 246098.6562
Epoch 55/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 245756.3438
Epoch 56/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 245587.0469
Epoch 57/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 245276.2031
Epoch 58/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 244985.9219
Epoch 59/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 244696.4688
Epoch 60/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 244522.6094
Epoch 61/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 244234.2344
Epoch 62/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 244026.8750
Epoch 63/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 243779.4531
Epoch 64/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 243506.2500
Epoch 65/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 243397.1875
Epoch 66/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 243150.7969
Epoch 67/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 242874.3438
Epoch 68/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 242757.8594
Epoch 69/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 242459.5781
Epoch 70/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 242221.8906
Epoch 71/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 242169.2969
Epoch 72/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 241987.9531
Epoch 73/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 241719.5156
Epoch 74/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 241575.4531
Epoch 75/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 241408.7656
Epoch 76/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 241195.8281
Epoch 77/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 241046.2812
Epoch 78/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 240782.2031
Epoch 79/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 240586.9531
Epoch 80/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 240525.4844
Epoch 81/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 240317.7812
Epoch 82/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 240217.6094
Epoch 83/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 240019.4219
Epoch 84/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 239816.4844
Epoch 85/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 239760.6250
Epoch 86/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 239644.2031
Epoch 87/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 239286.9844
Epoch 88/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 239109.4688
Epoch 89/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 238955.0156
Epoch 90/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 238812.2344
Epoch 91/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 238731.5938
Epoch 92/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 238701.2188
Epoch 93/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 238357.0781
Epoch 94/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 238220.2500
Epoch 95/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 238022.5156
Epoch 96/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 237582.5625
Epoch 97/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 237044.3750
Epoch 98/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 236922.5469
Epoch 99/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 236841.1094
Epoch 100/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 236599.3438
Epoch 101/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 236496.5000
Epoch 102/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 236412.2812
Epoch 103/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 236199.0625
Epoch 104/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 236242.1094
Epoch 105/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 236044.5781
Epoch 106/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 235895.2656
Epoch 107/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 235693.9531
Epoch 108/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 235604.5781
Epoch 109/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 235591.4375
Epoch 110/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 235443.7969
Epoch 111/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 235445.8594
Epoch 112/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 235245.1250
Epoch 113/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 235106.6406
Epoch 114/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 235068.5938
Epoch 115/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 234788.0938
Epoch 116/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 234633.9062
Epoch 117/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 234478.2656
Epoch 118/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 234463.1250
Epoch 119/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 234316.0312
Epoch 120/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 234168.9062
Epoch 121/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 234168.0469
Epoch 122/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 234072.1406
Epoch 123/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 233937.2344
Epoch 124/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 233768.0469
Epoch 125/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 233620.0781
Epoch 126/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 233510.4531
Epoch 127/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 233435.6875
Epoch 128/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 233317.3750
Epoch 129/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 233305.6094
Epoch 130/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 233188.8281
Epoch 131/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 233095.1875
Epoch 132/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 232939.6250
Epoch 133/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 232456.7031
Epoch 134/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 232032.3906
Epoch 135/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 232174.7188
Epoch 136/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 231789.5938
Epoch 137/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 231608.4375
Epoch 138/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 231377.2500
Epoch 139/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 231232.2188
Epoch 140/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 231108.1406
Epoch 141/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 231008.5469
Epoch 142/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 230854.4688
Epoch 143/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 230932.5000
Epoch 144/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 230661.7500
Epoch 145/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 230772.0312
Epoch 146/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 230446.3438
Epoch 147/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 230267.1406
Epoch 148/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 230114.6406
Epoch 149/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 229967.8594
Epoch 150/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 230000.6406
Epoch 151/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 229722.0781
Epoch 152/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 229769.3125
Epoch 153/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 229739.5156
Epoch 154/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 229566.3438
Epoch 155/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 229592.7344
Epoch 156/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 229418.4375
Epoch 157/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 229509.8281
Epoch 158/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 229256.8750
Epoch 159/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 229231.2969
Epoch 160/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 229241.7031
Epoch 161/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 229143.5156
Epoch 162/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 229105.3594
Epoch 163/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 228971.1875
Epoch 164/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 228862.4844
Epoch 165/1400
1137/1137 [==============================] - 11s 9ms/step - loss: 228840.2344
Epoch 166/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 228832.5312
Epoch 167/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 228747.4219
Epoch 168/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 228711.4844
Epoch 169/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 228611.0312
Epoch 170/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 228485.4844
Epoch 171/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 228419.2969
Epoch 172/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 228325.4062
Epoch 173/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 228352.7188
Epoch 174/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 228209.9844
Epoch 175/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 228143.6094
Epoch 176/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 228108.3438
Epoch 177/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 227879.5312
Epoch 178/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 227971.8906
Epoch 179/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 227859.8438
Epoch 180/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 227764.5625
Epoch 181/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 227671.5156
Epoch 182/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 227458.5469
Epoch 183/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 227415.9531
Epoch 184/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 227323.8906
Epoch 185/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 227281.7344
Epoch 186/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 227083.0938
Epoch 187/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 227099.9688
Epoch 188/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 227023.6250
Epoch 189/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 227013.1094
Epoch 190/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 226962.3594
Epoch 191/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 226829.3438
Epoch 192/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 226771.1250
Epoch 193/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 226671.3125
Epoch 194/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 226626.9375
Epoch 195/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 226344.2344
Epoch 196/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 226250.9375
Epoch 197/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 226054.5156
Epoch 198/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 225995.7969
Epoch 199/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 225823.8281
Epoch 200/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 225725.9062
Epoch 201/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 225705.9688
Epoch 202/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 225595.5000
Epoch 203/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 225641.4062
Epoch 204/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 225475.7969
Epoch 205/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 225523.1406
Epoch 206/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 225350.8125
Epoch 207/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 225240.2344
Epoch 208/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 225250.1406
Epoch 209/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 225032.4375
Epoch 210/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 225099.0312
Epoch 211/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 225029.3906
Epoch 212/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 225071.3594
Epoch 213/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 224833.5000
Epoch 214/1400
1137/1137 [==============================] - 11s 10ms/step - loss: 224928.2500
Epoch 215/1400

KeyboardInterrupt:

In [ ]:
for layer in model.layers:
    print(layer.name)

input_1
dense
reshape
conv2d
conv2d_1
flatten
dense_1
reshape_1
conv2d_transpose
conv2d_transpose_1
dropout
flatten_1
dense_2
dense_3
dense_4

In [ ]:
from tensorflow.keras.models import Model
latent_model = Model(inputs=input_gex, outputs=hidden_layer)

In [ ]:
model.predict( W.iloc[1:2])

1/1 [==============================] - 0s 231ms/step

array([[   0.      ,  282.87418 ,    0.      ,  179.37187 ,    0.      ,
           0.      ,    0.      ,    0.      ,    0.      ,    0.      ,
         226.20221 ,   10.472186,    0.      ,    0.      ,    0.      ,
         451.1031  ,  680.6808  ,  234.66826 ,    0.      ,  265.87424 ,
         255.60876 ,    0.      ,    0.      ,    0.      ,    0.      ,
           0.      ,    0.      ,    0.      , 1066.8148  ,    0.      ,
           0.      ,    0.      ,    0.      ,    0.      ,    0.      ,
         581.25586 ,    0.      ,    0.      ,    0.      ,    0.      ,
           0.      ,  769.2237  ,    0.      ,    0.      ,   16.353132,
           0.      ,    0.      ,   23.847935,    0.      ,    0.      ,
         366.39087 ,  374.7697  ,  323.41495 ,    8.949597,    0.      ,
           0.      ,    0.      ,  644.609   ,  183.93542 ,  257.91528 ,
           0.      ,  416.4306  ,    0.      ,   49.78854 ,  284.2461  ,
           0.      ,    0.      , 3711.6548  ,   83.30325 ,    0.      ,
         251.06102 ,  147.64815 ,    0.      ,    0.      ,    0.      ,
           0.      ,   89.05262 ,  351.3708  ,    0.      ,    0.      ,
         351.19873 ,    0.      ,  602.1452  ,  855.4316  ,    0.      ,
           0.      ,    0.      ,    0.      ,    0.      ,    0.      ,
         145.40552 ,    0.      ,    0.      ,    0.      ,  195.92812 ,
          35.19925 ,  539.0943  ,    0.      ,  107.049835,    0.      ,
           0.      ,  382.98877 ,    0.      ,  100.698235,    0.      ,
         407.89377 ,    0.      ,   19.579807,    0.      ,    0.      ,
           0.      ,  232.94629 ,  425.8892  ,    0.      ,    0.      ,
           0.      ,  486.36154 ,  207.26503 ,  367.6324  ,    0.      ,
           0.      ]], dtype=float32)

In [ ]:
model.predict( W.iloc[4:5])

1/1 [==============================] - 0s 43ms/step

array([[   0.       ,  365.12427  ,    0.       ,    0.       ,
           0.       ,    0.       ,  419.0646   ,    0.       ,
           0.       ,    0.       ,    0.       ,    0.       ,
           0.       ,    0.       ,    0.       ,    0.       ,
         443.47708  ,    0.       ,    0.       ,  510.39874  ,
           0.       ,    0.       ,    0.       ,    0.       ,
           0.       ,    0.       ,    0.       ,  137.07036  ,
         424.77206  ,   21.36535  ,    0.       ,   76.86337  ,
         260.05426  ,    0.       ,  696.32     ,  341.5926   ,
         460.0225   ,  165.50032  ,    0.       ,    0.       ,
        1123.8145   ,  330.2831   ,    3.4851475,   54.808918 ,
           0.       ,    0.       ,  318.08087  ,    0.       ,
          27.86477  ,  546.44714  ,    0.       ,  223.28453  ,
        1512.1534   ,   84.55223  ,  377.29678  ,    0.       ,
           0.       ,  352.13083  ,    0.       ,    0.       ,
           0.       ,    0.       ,    0.       ,    0.       ,
         520.9536   ,    0.       ,    0.       , 2957.6482   ,
           0.       ,    0.       ,  204.92812  ,  320.0667   ,
           0.       ,  324.59802  ,    0.       ,    0.       ,
           0.       ,    0.       ,  236.9016   ,    0.       ,
         435.37067  ,    0.       , 1087.508    ,    0.       ,
           0.       ,    0.       ,    0.       ,  278.90042  ,
           0.       ,  126.44629  ,    0.       ,    0.       ,
           0.       ,   30.181381 ,    0.       ,  249.6838   ,
          11.582206 ,    0.       ,   48.71913  ,    0.       ,
         105.218414 ,    0.       ,    0.       ,  281.63074  ,
           0.       ,    0.       ,   97.673065 ,  490.77225  ,
           0.       ,  183.21419  ,    0.       ,  208.10457  ,
         377.97314  ,  806.0344   ,    0.       ,  380.62744  ,
         470.24335  ,  663.48987  , 1168.296    ,    0.       ,
           0.       ]], dtype=float32)

In [ ]:
integration_pred = latent_model.predict( W)

4547/4547 [==============================] - 14s 3ms/step

In [ ]:
pd.DataFrame(integration_pred[1:50,1:50])

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,0.0,0.000000,0.000000,73.942764,0.0,0.0,0.0,148.284988,0.000000,59.473297,...,0.0,77.397285,0.000000,0.0,133.583817,0.0,0.0,72.280869,0.0,0.0
1,0.0,0.000000,0.000000,83.532921,0.0,0.0,0.0,161.269333,0.000000,219.395828,...,0.0,0.000000,0.000000,0.0,161.774597,0.0,0.0,7.269670,0.0,0.0
2,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.918569,...,0.0,56.906204,0.000000,0.0,407.721161,0.0,0.0,0.000000,0.0,0.0
3,0.0,243.816971,0.000000,197.551590,0.0,0.0,0.0,212.702637,190.704697,325.734161,...,0.0,0.000000,297.092896,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0
4,0.0,220.942734,0.000000,81.349754,0.0,0.0,0.0,65.122330,0.000000,23.175999,...,0.0,0.000000,0.000000,0.0,155.669098,0.0,0.0,0.000000,0.0,0.0
5,0.0,0.000000,0.000000,205.058075,0.0,0.0,0.0,28.442026,0.000000,54.506237,...,0.0,338.641510,0.000000,0.0,354.915253,0.0,0.0,0.000000,0.0,0.0
6,0.0,0.000000,0.000000,64.408531,0.0,0.0,0.0,14.082086,0.000000,197.532669,...,0.0,56.651707,0.000000,0.0,11.822893,0.0,0.0,149.356995,0.0,0.0
7,0.0,189.587250,0.000000,85.999336,0.0,0.0,0.0,78.129402,0.000000,1.852733,...,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0
8,0.0,100.950172,0.000000,85.258110,0.0,0.0,0.0,0.000000,0.000000,366.110138,...,0.0,139.227905,111.221626,0.0,46.511890,0.0,0.0,0.000000,0.0,0.0
9,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,14.327515,0.000000,234.530472,...,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,170.058945,0.0,0.0
10,0.0,0.000000,0.000000,115.165169,0.0,0.0,0.0,147.043152,0.000000,168.193924,...,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,154.062622,0.0,0.0
11,0.0,99.584862,0.000000,0.000000,0.0,0.0,0.0,117.125336,0.000000,187.568146,...,0.0,0.000000,132.654877,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0
12,0.0,102.631248,0.000000,14.147945,0.0,0.0,0.0,148.267517,0.000000,268.317108,...,0.0,0.000000,0.000000,0.0,44.808727,0.0,0.0,0.000000,0.0,0.0
13,0.0,74.005463,0.000000,0.000000,0.0,0.0,0.0,18.352797,0.000000,108.113449,...,0.0,0.000000,0.000000,0.0,156.496658,0.0,0.0,0.000000,0.0,0.0
14,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,81.094475,0.000000,154.608994,...,0.0,80.028732,0.000000,0.0,0.000000,0.0,0.0,88.650291,0.0,0.0
15,0.0,0.000000,0.000000,74.048798,0.0,0.0,0.0,135.268463,0.000000,123.005951,...,0.0,0.000000,0.000000,0.0,131.632309,0.0,0.0,0.000000,0.0,0.0
16,0.0,0.000000,0.000000,96.025940,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.0,250.552963,0.000000,0.0,222.941498,0.0,0.0,0.000000,0.0,0.0
17,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,184.992477,0.000000,86.507568,...,0.0,3.696033,0.000000,0.0,189.714203,0.0,0.0,82.869431,0.0,0.0
18,0.0,0.000000,0.000000,96.206123,0.0,0.0,0.0,78.569862,16.436781,279.398041,...,0.0,85.782501,0.000000,0.0,0.000000,0.0,0.0,208.515289,0.0,0.0
19,0.0,223.472153,0.000000,0.000000,0.0,0.0,0.0,162.717972,0.000000,121.298615,...,0.0,0.000000,244.684097,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0
20,0.0,59.974087,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,153.385437,...,0.0,245.560150,0.000000,0.0,236.527908,0.0,0.0,0.000000,0.0,0.0
21,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,224.753433,0.000000,2.098716,...,0.0,80.589325,0.000000,0.0,97.245995,0.0,0.0,0.000000,0.0,0.0
22,0.0,0.000000,0.000000,118.033813,0.0,0.0,0.0,76.297607,23.911390,204.314835,...,0.0,0.000000,0.000000,0.0,81.319054,0.0,0.0,231.427094,0.0,0.0
23,0.0,24.889183,0.000000,21.960045,0.0,0.0,0.0,97.031418,0.000000,203.172852,...,0.0,0.000000,21.049313,0.0,59.333496,0.0,0.0,0.000000,0.0,0.0
24,0.0,103.780228,0.000000,29.282703,0.0,0.0,0.0,130.606812,0.000000,353.564545,...,0.0,54.754684,0.000000,0.0,203.953903,0.0,0.0,0.000000,0.0,0.0
25,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,66.928322,0.000000,119.698807,...,0.0,0.000000,19.904100,0.0,0.000000,0.0,0.0,106.736923,0.0,0.0
26,0.0,0.000000,0.000000,134.596420,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.0,148.998764,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0
27,0.0,41.381504,0.000000,128.392532,0.0,0.0,0.0,125.908234,0.000000,241.657730,...,0.0,135.347229,0.000000,0.0,0.000000,0.0,0.0,43.250629,0.0,0.0
28,0.0,0.000000,0.000000,320.881165,0.0,0.0,0.0,286.477417,0.000000,71.335373,...,0.0,0.000000,0.000000,0.0,17.914707,0.0,0.0,273.491699,0.0,0.0
29,0.0,0.000000,0.000000,5.424142,0.0,0.0,0.0,180.224258,0.000000,234.594315,...,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,128.539886,0.0,0.0
30,0.0,22.163101,0.000000,234.391724,0.0,0.0,0.0,127.079063,0.000000,187.430542,...,0.0,0.000000,52.842484,0.0,0.000000,0.0,0.0,115.401772,0.0,0.0
31,0.0,0.000000,0.000000,78.530251,0.0,0.0,0.0,0.000000,0.000000,0.000000,...,0.0,289.018585,0.000000,0.0,0.000000,0.0,0.0,38.432777,0.0,0.0
32,0.0,0.000000,0.000000,75.750343,0.0,0.0,0.0,0.000000,0.000000,80.906036,...,0.0,0.000000,67.451683,0.0,0.000000,0.0,0.0,102.488678,0.0,0.0
33,0.0,0.000000,0.000000,121.364815,0.0,0.0,0.0,23.714075,158.364761,150.691177,...,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,181.304245,0.0,0.0
34,0.0,0.000000,0.000000,7.396334,0.0,0.0,0.0,112.629250,0.000000,473.686340,...,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,84.755859,0.0,0.0
35,0.0,34.795658,0.000000,135.883392,0.0,0.0,0.0,66.768730,0.000000,244.631546,...,0.0,47.722965,0.000000,0.0,86.917297,0.0,0.0,55.803154,0.0,0.0
36,0.0,0.000000,0.000000,358.365173,0.0,0.0,0.0,95.685226,0.000000,214.541885,...,0.0,0.000000,0.000000,0.0,202.038971,0.0,0.0,115.804268,0.0,0.0
37,0.0,0.000000,2.301403,57.492088,0.0,0.0,0.0,92.759369,0.000000,161.689423,...,0.0,0.000000,32.086937,0.0,13.780873,0.0,0.0,0.000000,0.0,0.0
38,0.0,0.000000,0.000000,178.293015,0.0,0.0,0.0,85.298904,0.000000,344.673859,...,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.301443,0.0,0.0
39,0.0,384.878113,0.000000,26.821068,0.0,0.0,0.0,340.588196,21.490644,0.000000,...,0.0,0.000000,130.052780,0.0,71.069885,0.0,0.0,0.000000,0.0,0.0
40,0.0,0.000000,0.000000,78.701981,0.0,0.0,0.0,32.762207,0.000000,198.887329,...,0.0,0.000000,0.000000,0.0,24.148190,0.0,0.0,16.440584,0.0,0.0
41,0.0,399.885498,0.000000,76.766838,0.0,0.0,0.0,129.277481,0.000000,0.000000,...,0.0,19.929903,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0
42,0.0,20.846451,0.000000,260.130127,0.0,0.0,0.0,54.123047,0.000000,262.635376,...,0.0,0.000000,0.000000,0.0,38.057156,0.0,0.0,91.012703,0.0,0.0
43,0.0,0.000000,0.000000,85.080238,0.0,0.0,0.0,351.215088,0.000000,93.061829,...,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,254.067352,0.0,0.0
44,0.0,0.000000,0.000000,92.739960,0.0,0.0,0.0,236.923935,0.000000,483.410889,...,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,87.533279,0.0,0.0
45,0.0,73.342010,0.000000,0.000000,0.0,0.0,0.0,192.503067,126.009445,354.805542,...,0.0,0.000000,188.308243,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0
46,0.0,0.000000,0.000000,14.067036,0.0,0.0,0.0,130.253784,0.000000,417.559937,...,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0
47,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,321.547699,0.000000,0.000000,...,0.0,208.404053,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0
48,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,236.900177,...,0.0,226.523743,0.000000,0.0,179.963715,0.0,0.0,94.970238,0.0,0.0

In [ ]:
integration_pred = integration_pred.reshape([integration_pred.shape[0],-1])

In [ ]:
integration_pred.shape

(145479, 225)

In [ ]:
integration_pred = integration_pred.reshape([integration_pred.shape[0],-1])
integration_pred.shape

(145479, 225)

In [ ]:
pd.DataFrame(integration_pred)

,0,1,2,3,4,5,6,7,8,9,...,215,216,217,218,219,220,221,222,223,224
0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,55.963898,59.682621,...,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,279.597900,0.000000
1,0.000000,0.0,0.000000,0.0,73.942764,0.0,0.0,0.0,148.284988,0.000000,...,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
2,93.040886,0.0,0.000000,0.0,83.532921,0.0,0.0,0.0,161.269333,0.000000,...,49.709923,0.0,0.0,0.000000,0.0,0.000000,99.580719,0.0,27.306803,0.000000
3,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.000000,0.0,0.000000,22.845297,0.0,174.727341,0.000000
4,0.000000,0.0,243.816971,0.0,197.551590,0.0,0.0,0.0,212.702637,190.704697,...,97.653908,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,205.183258,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145474,0.000000,0.0,155.781082,0.0,0.000000,0.0,0.0,0.0,256.123993,0.000000,...,95.189293,0.0,0.0,0.000000,0.0,18.165180,0.000000,0.0,0.000000,47.573582
145475,0.000000,0.0,0.000000,0.0,100.995560,0.0,0.0,0.0,0.000000,0.000000,...,128.182999,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
145476,0.000000,0.0,0.000000,0.0,166.593185,0.0,0.0,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.000000,0.0,71.808754,0.000000,0.0,0.000000,49.722225
145477,125.063240,0.0,0.000000,0.0,53.738243,0.0,0.0,0.0,87.231964,0.000000,...,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,66.618019,0.000000
145478,23.785604,0.0,122.751801,0.0,174.557663,0.0,0.0,0.0,119.608955,0.000000,...,90.715744,0.0,0.0,19.236681,0.0,63.686882,0.000000,0.0,0.000000,70.895416

In [ ]:
pd.DataFrame(integration_pred).to_csv("integration_pred_new_method_gex_to_TCR_alpha_chain_10X_all_peptides_225.csv", index=False)