In this work, we use transformer model to integrate gene expression and TCR amino acid sequences

Getting gene data

In [1]:
# %matplotlib inline

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import os 
import numpy as np

import pandas as pd
# import seaborn as sb
import matplotlib.pyplot as pl

import scanpy as sc

import anndata as ad

from scipy.sparse import csr_matrix
from matplotlib import rcParams
from matplotlib import colors

sc.settings.verbosity = 3

In [2]:
gene_TCR = ad.read_h5ad('../10Xdatasets/gex_merge_log1_5000_genes_all_peptides.h5ad')
gene_TCR

c:\Users\phill\anaconda3\envs\tensorflow\lib\site-packages\anndata\_core\anndata.py:1818: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

AnnData object with n_obs × n_vars = 145479 × 5000
    obs: 'v_gene_TRA', 'v_gene_TRB', 'd_gene_TRA', 'd_gene_TRB', 'j_gene_TRA', 'j_gene_TRB', 'c_gene_TRA', 'c_gene_TRB', 'cdr3_TRA', 'cdr3_TRB', 'cdr3_nt_TRA', 'cdr3_nt_TRB', 'umis_TRA', 'umis_TRB', 'donor', 'cell_clono_cdr3_aa', 'cell_clono_cdr3_nt', 'CD3', 'CD19', 'CD45RA', 'CD4', 'CD8a', 'CD14', 'CD45RO', 'CD279_PD-1', 'IgG1', 'IgG2a', 'IgG2b', 'CD127', 'CD197_CCR7', 'HLA-DR', 'A0101_VTEHDTLLY_IE-1_CMV', 'A0201_KTWGQYWQV_gp100_Cancer', 'A0201_ELAGIGILTV_MART-1_Cancer', 'A0201_CLLWSFQTSA_Tyrosinase_Cancer', 'A0201_IMDQVPFSV_gp100_Cancer', 'A0201_SLLMWITQV_NY-ESO-1_Cancer', 'A0201_KVAELVHFL_MAGE-A3_Cancer', 'A0201_KVLEYVIKV_MAGE-A1_Cancer', 'A0201_CLLGTYTQDV_Kanamycin-B-dioxygenase', 'A0201_LLDFVRFMGV_EBNA-3B_EBV', 'A0201_LLMGTLGIVC_HPV-16E7_82-91', 'A0201_CLGGLLTMV_LMP-2A_EBV', 'A0201_YLLEMLWRL_LMP1_EBV', 'A0201_FLYALALLL_LMP2A_EBV', 'A0201_GILGFVFTL_Flu-MP_Influenza', 'A0201_GLCTLVAML_BMLF1_EBV', 'A0201_NLVPMVATV_pp65_CMV', 'A0201_ILKEPVHGV_RT_HIV', 'A0201_FLASKIGRLV_Ca2-indepen-Plip-A2', 'A2402_CYTWNQMNL_WT1-(235-243)236M_Y', 'A0201_RTLNAWVKV_Gag-protein_HIV', 'A0201_KLQCVDLHV_PSA146-154', 'A0201_LLFGYPVYV_HTLV-1', 'A0201_SLFNTVATL_Gag-protein_HIV', 'A0201_SLYNTVATLY_Gag-protein_HIV', 'A0201_SLFNTVATLY_Gag-protein_HIV', 'A0201_RMFPNAPYL_WT-1', 'A0201_YLNDHLEPWI_BCL-X_Cancer', 'A0201_MLDLQPETT_16E7_HPV', 'A0301_KLGGALQAK_IE-1_CMV', 'A0301_RLRAEAQVK_EMNA-3A_EBV', 'A0301_RIAAWMATY_BCL-2L1_Cancer', 'A1101_IVTDFSVIK_EBNA-3B_EBV', 'A1101_AVFDRKSDAK_EBNA-3B_EBV', 'B3501_IPSINVHHY_pp65_CMV', 'A2402_AYAQKIFKI_IE-1_CMV', 'A2402_QYDPVAALF_pp65_CMV', 'B0702_QPRAPIRPI_EBNA-6_EBV', 'B0702_TPRVTGGGAM_pp65_CMV', 'B0702_RPPIFIRRL_EBNA-3A_EBV', 'B0702_RPHERNGFTVL_pp65_CMV', 'B0801_RAKFKQLL_BZLF1_EBV', 'B0801_ELRRKMMYM_IE-1_CMV', 'B0801_FLRGRAYGL_EBNA-3A_EBV', 'A0101_SLEGGGLGY_NC', 'A0101_STEGGGLAY_NC', 'A0201_ALIAPVHAV_NC', 'A2402_AYSSAGASI_NC', 'B0702_GPAESAAGL_NC', 'NR(B0801)_AAKGRGAAL_NC', 'antigen', 'peptide', 'orig_ix', 'n_counts', 'log_counts', 'n_genes', 'mt_fraction'
    var: 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection'
    uns: 'donor_colors', 'hvg', 'log1p'
    layers: 'raw_counts'

In [3]:
gene_TCR = gene_TCR[gene_TCR.obs.donor == 'donor1']
gene_TCR

View of AnnData object with n_obs × n_vars = 35515 × 5000
    obs: 'v_gene_TRA', 'v_gene_TRB', 'd_gene_TRA', 'd_gene_TRB', 'j_gene_TRA', 'j_gene_TRB', 'c_gene_TRA', 'c_gene_TRB', 'cdr3_TRA', 'cdr3_TRB', 'cdr3_nt_TRA', 'cdr3_nt_TRB', 'umis_TRA', 'umis_TRB', 'donor', 'cell_clono_cdr3_aa', 'cell_clono_cdr3_nt', 'CD3', 'CD19', 'CD45RA', 'CD4', 'CD8a', 'CD14', 'CD45RO', 'CD279_PD-1', 'IgG1', 'IgG2a', 'IgG2b', 'CD127', 'CD197_CCR7', 'HLA-DR', 'A0101_VTEHDTLLY_IE-1_CMV', 'A0201_KTWGQYWQV_gp100_Cancer', 'A0201_ELAGIGILTV_MART-1_Cancer', 'A0201_CLLWSFQTSA_Tyrosinase_Cancer', 'A0201_IMDQVPFSV_gp100_Cancer', 'A0201_SLLMWITQV_NY-ESO-1_Cancer', 'A0201_KVAELVHFL_MAGE-A3_Cancer', 'A0201_KVLEYVIKV_MAGE-A1_Cancer', 'A0201_CLLGTYTQDV_Kanamycin-B-dioxygenase', 'A0201_LLDFVRFMGV_EBNA-3B_EBV', 'A0201_LLMGTLGIVC_HPV-16E7_82-91', 'A0201_CLGGLLTMV_LMP-2A_EBV', 'A0201_YLLEMLWRL_LMP1_EBV', 'A0201_FLYALALLL_LMP2A_EBV', 'A0201_GILGFVFTL_Flu-MP_Influenza', 'A0201_GLCTLVAML_BMLF1_EBV', 'A0201_NLVPMVATV_pp65_CMV', 'A0201_ILKEPVHGV_RT_HIV', 'A0201_FLASKIGRLV_Ca2-indepen-Plip-A2', 'A2402_CYTWNQMNL_WT1-(235-243)236M_Y', 'A0201_RTLNAWVKV_Gag-protein_HIV', 'A0201_KLQCVDLHV_PSA146-154', 'A0201_LLFGYPVYV_HTLV-1', 'A0201_SLFNTVATL_Gag-protein_HIV', 'A0201_SLYNTVATLY_Gag-protein_HIV', 'A0201_SLFNTVATLY_Gag-protein_HIV', 'A0201_RMFPNAPYL_WT-1', 'A0201_YLNDHLEPWI_BCL-X_Cancer', 'A0201_MLDLQPETT_16E7_HPV', 'A0301_KLGGALQAK_IE-1_CMV', 'A0301_RLRAEAQVK_EMNA-3A_EBV', 'A0301_RIAAWMATY_BCL-2L1_Cancer', 'A1101_IVTDFSVIK_EBNA-3B_EBV', 'A1101_AVFDRKSDAK_EBNA-3B_EBV', 'B3501_IPSINVHHY_pp65_CMV', 'A2402_AYAQKIFKI_IE-1_CMV', 'A2402_QYDPVAALF_pp65_CMV', 'B0702_QPRAPIRPI_EBNA-6_EBV', 'B0702_TPRVTGGGAM_pp65_CMV', 'B0702_RPPIFIRRL_EBNA-3A_EBV', 'B0702_RPHERNGFTVL_pp65_CMV', 'B0801_RAKFKQLL_BZLF1_EBV', 'B0801_ELRRKMMYM_IE-1_CMV', 'B0801_FLRGRAYGL_EBNA-3A_EBV', 'A0101_SLEGGGLGY_NC', 'A0101_STEGGGLAY_NC', 'A0201_ALIAPVHAV_NC', 'A2402_AYSSAGASI_NC', 'B0702_GPAESAAGL_NC', 'NR(B0801)_AAKGRGAAL_NC', 'antigen', 'peptide', 'orig_ix', 'n_counts', 'log_counts', 'n_genes', 'mt_fraction'
    var: 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection'
    uns: 'donor_colors', 'hvg', 'log1p'
    layers: 'raw_counts'

In [4]:
gene_TCR.obs.donor

barcode
AGGGTGAGTATTACCG-18    donor1
CTTGGCTTCGTTGCCT-25    donor1
ACGATACTCGCAGGCT-40    donor1
ACGCCAGTCATGTCTT-8     donor1
TTCTTAGCAAAGAATC-4     donor1
                        ...
GTGAAGGGTACCGTAT-36    donor1
CTTACCGCAATCAGAA-15    donor1
CGACTTCGTAAGTTCC-24    donor1
GGACAGATCGTGTAGT-7     donor1
TGTTCCGGTTCAGGCC-6     donor1
Name: donor, Length: 35515, dtype: category
Categories (1, object): ['donor1']

In [5]:
gene = pd.DataFrame(gene_TCR.X.todense())
gene

,0,1,2,3,4,5,6,7,8,9,...,4990,4991,4992,4993,4994,4995,4996,4997,4998,4999
0,0.0,0.693147,0.0,0.0,0.0,0.0,0.000000,0.0,0.693147,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,1.791759,0.693147,0.0,0.0
1,0.0,0.000000,0.0,0.0,0.0,0.0,0.693147,0.0,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.693147,0.000000,0.0,0.0
2,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,1.791759,0.000000,0.0,0.0
3,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.693147,0.0,0.0,0.000000,1.609438,0.000000,0.0,0.0
4,0.0,1.386294,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,1.386294,0.693147,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35510,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.693147,0.0,0.000000,0.0,0.0,0.000000,0.693147,1.386294,0.0,0.0
35511,0.0,0.693147,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,1.609438,1.945910,0.0,0.0
35512,0.0,0.000000,0.0,0.0,0.0,0.0,0.693147,0.0,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,0.0,1.609438,0.000000,1.098612,0.0,0.0
35513,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,1.609438,1.098612,0.0,0.0
35514,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.693147,0.0,0.0

In [6]:
tcr_seq = gene_TCR.obs[['cdr3_TRB']]
tcr_seq

                             cdr3_TRB
barcode
AGGGTGAGTATTACCG-18    CSAPSGEGRDTQYF
CTTGGCTTCGTTGCCT-25    CASSLFDSQETQYF
ACGATACTCGCAGGCT-40  CASSLFDSGRLDTQYF
ACGCCAGTCATGTCTT-8       CSASPGDYEQYF
TTCTTAGCAAAGAATC-4     CASSHGKGGNEQFF
...                               ...
GTGAAGGGTACCGTAT-36      CSASPGDYEQYF
CTTACCGCAATCAGAA-15   CASSIGLAGARELFF
CGACTTCGTAAGTTCC-24       CASAGNTEAFF
GGACAGATCGTGTAGT-7     CASLATGLGTEAFF
TGTTCCGGTTCAGGCC-6    CASSPGGGSSFGYTF

[35515 rows x 1 columns]

In [7]:
import tensorflow as tf

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Reshape, Conv2D, Conv2DTranspose, Flatten, Dropout
from tensorflow.keras.initializers import HeNormal
# Define input layer
input_gex = Input(shape=(100,))
gex = Dense(units=64, activation='relu', kernel_initializer=HeNormal())(input_gex)
gex = Reshape(target_shape=(8,8,1))(gex)

# Convolutional layers
gex = Conv2D(filters=64, kernel_size=3, strides=1, activation='relu', padding="same")(gex)
gex = Conv2D(filters=32, kernel_size=3, strides=1, activation='relu', padding="same")(gex)

gex = Flatten()(gex)
hidden_layer = Dense(units=225, activation='relu', kernel_initializer=HeNormal())(gex)

# Transposed Convolutional layers
tcr = Reshape(target_shape=(15,15,1))(hidden_layer)
tcr = Conv2DTranspose(filters=16, kernel_size=3, strides=1, activation='relu', padding="same")(tcr)
tcr = Conv2DTranspose(filters=32, kernel_size=3, strides=1, activation='relu', padding="same")(tcr)
tcr = Dropout(rate=0.2)(tcr)
tcr = Flatten()(tcr)
tcr = Dense(units=150, activation='relu', kernel_initializer=HeNormal())(tcr)
tcr = Dense(units=130, activation='relu')(tcr)  # Ensure proper activation
tcr = Dense(units=121, activation='relu')(tcr)
# Define model
model = Model(inputs=input_gex, outputs=tcr)
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0015),
              loss='mse')

# Check layer names
model.summary()

In [ ]:
# import tensorflow as tf
# from tensorflow.keras.models import Model
# from tensorflow.keras.layers import Input, Dense, Reshape, Conv2D, Conv2DTranspose, Flatten, Dropout
# from tensorflow.keras.initializers import HeNormal

# # Define input layer
# input_gex = Input(shape=(100,))
# gex = Dense(units=64, activation='relu', kernel_initializer=HeNormal())(input_gex)
# gex = Reshape(target_shape=(8,8,1))(gex)

# # Convolutional layers
# gex = Conv2D(filters=64, kernel_size=3, strides=1, activation='relu', padding="same")(gex)
# gex = Conv2D(filters=32, kernel_size=3, strides=1, activation='relu', padding="same")(gex)

# gex = Flatten()(gex)
# hidden_layer = Dense(units=225, activation='relu', kernel_initializer=HeNormal())(gex)

# # Transposed Convolutional layers
# tcr = Reshape(target_shape=(15,15,1))(hidden_layer)
# tcr = Conv2DTranspose(filters=16, kernel_size=3, strides=1, activation='relu', padding="same")(tcr)
# tcr = Conv2DTranspose(filters=32, kernel_size=3, strides=1, activation='relu', padding="same")(tcr)
# tcr = Dropout(rate=0.2)(tcr)
# tcr = Flatten()(tcr)
# tcr = Dense(units=150, activation='relu', kernel_initializer=HeNormal())(tcr)
# tcr = Dense(units=130, activation='relu')(tcr)  # Ensure proper activation
# tcr = Dense(units=121, activation='relu')(tcr)
# # Define model
# model = Model(inputs=input_gex, outputs=tcr)
# model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0015),
#               loss='mse')

# # Check layer names
# model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_1 (InputLayer)        [(None, 100)]             0

 dense (Dense)               (None, 64)                6464

 reshape (Reshape)           (None, 8, 8, 1)           0

 conv2d (Conv2D)             (None, 8, 8, 64)          640

 conv2d_1 (Conv2D)           (None, 8, 8, 32)          18464

 flatten (Flatten)           (None, 2048)              0

 dense_1 (Dense)             (None, 225)               461025

 reshape_1 (Reshape)         (None, 15, 15, 1)         0

 conv2d_transpose (Conv2DTra  (None, 15, 15, 16)       160
 nspose)

 conv2d_transpose_1 (Conv2DT  (None, 15, 15, 32)       4640
 ranspose)

 dropout (Dropout)           (None, 15, 15, 32)        0

 flatten_1 (Flatten)         (None, 7200)              0

 dense_2 (Dense)             (None, 150)               1080150

 dense_3 (Dense)             (None, 130)               19630

 dense_4 (Dense)             (None, 121)               15851

=================================================================
Total params: 1,607,024
Trainable params: 1,607,024
Non-trainable params: 0
_________________________________________________________________

In [9]:
AE_tcr = pd.read_csv("../AE_emb_TRB_all_peptides_10X_donor_1_only.csv")
AE_tcr

,0,1,2,3,4,5,6,7,8,9,...,111,112,113,114,115,116,117,118,119,120
0,-1541.692100,431.963380,-113.487510,363.839600,-617.46550,-576.387700,-152.86124,-985.72640,445.512240,-236.100420,...,28.279720,1018.37134,261.22320,87.342865,-228.999980,146.428400,532.794070,865.979250,-578.558960,855.61690
1,-273.513100,-398.893860,616.804300,-877.823500,-871.22670,375.483060,422.57904,192.50789,-199.132490,-265.096560,...,494.893800,258.40955,-404.77722,-428.136350,-191.204730,-372.523960,203.390100,1186.992800,96.218480,-457.06020
2,380.871000,58.110577,-132.314600,-259.367740,-274.57843,-194.467930,248.31584,265.90674,-60.173637,-98.568726,...,92.126270,29.88193,-891.70480,370.281830,59.372814,-729.678000,902.504940,1161.101400,-700.613340,-425.83978
3,-1229.993200,261.055080,-116.357920,339.648250,-440.47760,65.392690,-221.38164,-939.52580,145.774370,39.421880,...,153.995830,770.41030,-417.14660,194.590100,-287.056100,-4.876206,-74.260704,43.650208,-67.906160,-309.77994
4,-1113.337300,-93.408485,-280.131400,-150.605300,-93.47611,-520.023130,64.99572,-1008.05770,174.263440,-62.470676,...,-56.364480,984.19050,467.82294,247.904310,409.301880,-60.920048,744.377300,1218.065600,-456.735320,617.48610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35510,-1229.993200,261.055080,-116.357920,339.648250,-440.47760,65.392690,-221.38164,-939.52580,145.774370,39.421880,...,153.995830,770.41030,-417.14660,194.590100,-287.056100,-4.876206,-74.260704,43.650208,-67.906160,-309.77994
35511,-24.937555,-610.643400,231.669100,-48.156483,242.74973,-65.198640,-660.69820,-419.44427,-597.105000,92.525670,...,-531.762940,931.85034,-257.47950,351.656740,-311.497500,-156.879900,-360.937260,744.809800,74.583550,567.55290
35512,328.290000,477.070500,35.919773,-269.693700,308.35275,-121.531600,-569.52875,-509.88388,-480.568760,210.404070,...,509.689030,871.91560,447.09885,-565.088870,-756.617900,-695.267200,170.006210,966.821960,51.627117,-1258.25700
35513,66.083610,-979.693660,-210.645480,-364.229980,396.45697,-290.372100,330.68960,-123.65221,-248.489030,-368.855530,...,-150.828810,352.66696,69.07290,-160.042130,-67.788040,111.505005,252.334350,1753.999500,158.474030,-450.08978
35514,-927.102970,-182.108200,-255.466310,321.380400,-128.93257,-41.966324,92.80742,116.49615,763.529900,-340.972000,...,80.417534,534.10800,181.46263,-266.679100,-26.544603,-13.150534,-135.365360,436.155120,-90.709694,-423.67297

In [10]:
import numpy as np
from sklearn.decomposition import NMF

# Generate random non-negative data
data = gene.to_numpy()

# Initialize the NMF model
n_components = 100
model_nmf = NMF(n_components=n_components, init='random', random_state=0)

# Fit the model to the data
W = model_nmf.fit_transform(data)
H = model_nmf.components_

# Display the results
print("Basis matrix (W):\n", W)
print("Coefficients matrix (H):\n", H)

c:\Users\phill\anaconda3\envs\tensorflow\lib\site-packages\sklearn\decomposition\_nmf.py:1710: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(

Basis matrix (W):
 [[2.6972830e-01 2.8575301e-01 3.2349173e-02 ... 1.7849728e-01
  7.2205931e-02 6.3250010e-04]
 [9.4617987e-01 1.7102477e-01 1.6105120e-01 ... 0.0000000e+00
  9.3340710e-02 0.0000000e+00]
 [4.3408936e-01 0.0000000e+00 2.9220533e-01 ... 1.0278109e-02
  4.1093561e-03 0.0000000e+00]
 ...
 [6.3596576e-01 0.0000000e+00 2.9008484e-01 ... 4.7547575e-03
  9.8687559e-02 0.0000000e+00]
 [1.0864531e+00 1.9762394e-01 3.7065756e-01 ... 5.7310890e-03
  2.9213486e-02 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]]
Coefficients matrix (H):
 [[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.10467249 0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.04535175 0.         ... 0.         0.         0.00181273]
 [0.         0.         0.         ... 0.         0.00048535 0.        ]]

In [11]:
W = pd.DataFrame(W)
W

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,0.269728,0.285753,0.032349,0.552654,0.124682,0.019776,0.001904,0.015233,0.165916,0.148393,...,0.000000,0.060630,0.216403,0.021437,0.029728,0.004525,0.020293,0.178497,0.072206,0.000633
1,0.946180,0.171025,0.161051,0.427533,0.243432,0.000000,0.000000,0.007518,0.240688,0.050733,...,0.000596,0.000000,0.067389,0.000000,0.027200,0.010487,0.015699,0.000000,0.093341,0.000000
2,0.434089,0.000000,0.292205,0.623748,0.211550,0.000000,0.000000,0.011240,0.000000,0.128447,...,0.029316,0.035785,0.003594,0.000000,0.000000,0.000070,0.012215,0.010278,0.004109,0.000000
3,0.729335,0.221870,0.000000,0.000000,0.257854,0.019506,0.045102,0.024270,0.000000,0.088816,...,0.043190,0.048438,0.000000,0.016525,0.006915,0.011320,0.012279,0.001098,0.034228,0.000888
4,0.656248,0.668048,0.471090,0.540120,0.022798,0.028723,0.088986,0.011827,0.007517,0.031618,...,0.048764,0.120444,0.298696,0.000000,0.012752,0.013183,0.025803,0.129973,0.047137,0.008924
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35510,0.043546,0.184586,0.000000,0.000000,0.100512,0.005914,0.000000,0.006933,0.330994,0.000000,...,0.029424,0.035614,0.050792,0.000000,0.017568,0.012702,0.007590,0.000000,0.029065,0.001013
35511,0.514584,0.000000,0.167434,0.000000,0.140392,0.000000,0.035951,0.004200,0.150183,0.131524,...,0.028503,0.025795,0.000000,0.000000,0.005178,0.000000,0.022052,0.004517,0.034213,0.000718
35512,0.635966,0.000000,0.290085,0.035056,0.108897,0.000000,0.045690,0.000000,0.000000,0.071139,...,0.029825,0.019364,0.000000,0.025793,0.003166,0.004230,0.000132,0.004755,0.098688,0.000000
35513,1.086453,0.197624,0.370658,0.077014,0.221128,0.002844,0.022769,0.006905,0.114654,0.129683,...,0.000000,0.000000,0.054695,0.000000,0.003671,0.004837,0.012339,0.005731,0.029213,0.000000
35514,0.000000,0.000000,0.000000,0.000000,0.087115,0.001503,0.023000,0.000000,0.257704,0.000000,...,0.000000,0.083529,0.083489,0.000000,0.025402,0.000000,0.000040,0.000000,0.000000,0.000000

In [12]:

# es_callback = EarlyStopping(monitor= 'val_auc', patience=20, restore_best_weights=True)
reduce_learning_rate = tf.keras.callbacks.ReduceLROnPlateau(factor=0.1, patience=50, monitor='loss', min_delta=100)

history = model.fit(W,AE_tcr, 
                epochs=1400, 
                batch_size=128, 
                shuffle = True,
                # callbacks=[es_callback, checkpoint,reduce_learning_rate])
                # callbacks=[reduce_learning_rate]
                )

Epoch 1/1400
278/278 [==============================] - 7s 12ms/step - loss: 333368.5000
Epoch 2/1400
278/278 [==============================] - 3s 11ms/step - loss: 331840.7500
Epoch 3/1400
278/278 [==============================] - 3s 11ms/step - loss: 306339.4688
Epoch 4/1400
278/278 [==============================] - 3s 11ms/step - loss: 234333.7500
Epoch 5/1400
278/278 [==============================] - 3s 11ms/step - loss: 233093.3594
Epoch 6/1400
278/278 [==============================] - 3s 11ms/step - loss: 232244.7969
Epoch 7/1400
278/278 [==============================] - 3s 12ms/step - loss: 231672.8438
Epoch 8/1400
278/278 [==============================] - 3s 12ms/step - loss: 230987.9688
Epoch 9/1400
278/278 [==============================] - 3s 12ms/step - loss: 230183.6875
Epoch 10/1400
278/278 [==============================] - 3s 12ms/step - loss: 229105.6406
Epoch 11/1400
278/278 [==============================] - 3s 12ms/step - loss: 227607.9688
Epoch 12/1400
278/278 [==============================] - 3s 12ms/step - loss: 227087.0469
Epoch 13/1400
278/278 [==============================] - 3s 12ms/step - loss: 226509.9062
Epoch 14/1400
278/278 [==============================] - 3s 12ms/step - loss: 226123.4844
Epoch 15/1400
278/278 [==============================] - 3s 12ms/step - loss: 225717.9375
Epoch 16/1400
278/278 [==============================] - 3s 12ms/step - loss: 225479.9062
Epoch 17/1400
278/278 [==============================] - 3s 12ms/step - loss: 225181.6875
Epoch 18/1400
278/278 [==============================] - 3s 12ms/step - loss: 224939.5781
Epoch 19/1400
278/278 [==============================] - 3s 12ms/step - loss: 224619.7344
Epoch 20/1400
278/278 [==============================] - 3s 12ms/step - loss: 223941.3594
Epoch 21/1400
278/278 [==============================] - 3s 12ms/step - loss: 222696.5938
Epoch 22/1400
278/278 [==============================] - 3s 12ms/step - loss: 222454.2500
Epoch 23/1400
278/278 [==============================] - 3s 12ms/step - loss: 222023.8750
Epoch 24/1400
278/278 [==============================] - 3s 13ms/step - loss: 221665.6250
Epoch 25/1400
278/278 [==============================] - 3s 13ms/step - loss: 221226.7656
Epoch 26/1400
278/278 [==============================] - 4s 13ms/step - loss: 220834.6094
Epoch 27/1400
278/278 [==============================] - 3s 13ms/step - loss: 220676.8281
Epoch 28/1400
278/278 [==============================] - 4s 13ms/step - loss: 220533.5469
Epoch 29/1400
278/278 [==============================] - 4s 13ms/step - loss: 220000.7188
Epoch 30/1400
278/278 [==============================] - 4s 13ms/step - loss: 219832.6094
Epoch 31/1400
278/278 [==============================] - 4s 13ms/step - loss: 219582.5156
Epoch 32/1400
278/278 [==============================] - 4s 13ms/step - loss: 219413.0312
Epoch 33/1400
278/278 [==============================] - 4s 13ms/step - loss: 219194.1406
Epoch 34/1400
278/278 [==============================] - 4s 13ms/step - loss: 218975.5469
Epoch 35/1400
278/278 [==============================] - 4s 13ms/step - loss: 218760.4688
Epoch 36/1400
278/278 [==============================] - 4s 13ms/step - loss: 218588.8594
Epoch 37/1400
278/278 [==============================] - 4s 13ms/step - loss: 218251.4219
Epoch 38/1400
278/278 [==============================] - 4s 13ms/step - loss: 217897.7344
Epoch 39/1400
278/278 [==============================] - 4s 13ms/step - loss: 217517.2031
Epoch 40/1400
278/278 [==============================] - 4s 13ms/step - loss: 217156.0625
Epoch 41/1400
278/278 [==============================] - 5s 19ms/step - loss: 216852.7500
Epoch 42/1400
278/278 [==============================] - 6s 21ms/step - loss: 216661.8438
Epoch 43/1400
278/278 [==============================] - 6s 20ms/step - loss: 216414.4688
Epoch 44/1400
278/278 [==============================] - 6s 20ms/step - loss: 216180.6719
Epoch 45/1400
278/278 [==============================] - 6s 20ms/step - loss: 215869.9688
Epoch 46/1400
278/278 [==============================] - 6s 21ms/step - loss: 215598.1250
Epoch 47/1400
278/278 [==============================] - 6s 20ms/step - loss: 215168.6719
Epoch 48/1400
278/278 [==============================] - 6s 20ms/step - loss: 214824.7969
Epoch 49/1400
278/278 [==============================] - 6s 20ms/step - loss: 214582.4844
Epoch 50/1400
278/278 [==============================] - 6s 20ms/step - loss: 214219.2188
Epoch 51/1400
278/278 [==============================] - 6s 20ms/step - loss: 213921.8281
Epoch 52/1400
278/278 [==============================] - 6s 20ms/step - loss: 213814.7969
Epoch 53/1400
278/278 [==============================] - 6s 21ms/step - loss: 213400.2031
Epoch 54/1400
278/278 [==============================] - 6s 20ms/step - loss: 213146.2344
Epoch 55/1400
278/278 [==============================] - 6s 20ms/step - loss: 212933.2031
Epoch 56/1400
278/278 [==============================] - 6s 20ms/step - loss: 212729.6094
Epoch 57/1400
278/278 [==============================] - 6s 20ms/step - loss: 212198.4531
Epoch 58/1400
278/278 [==============================] - 6s 20ms/step - loss: 211819.2969
Epoch 59/1400
278/278 [==============================] - 6s 21ms/step - loss: 211487.9688
Epoch 60/1400
278/278 [==============================] - 6s 20ms/step - loss: 211307.3438
Epoch 61/1400
278/278 [==============================] - 6s 21ms/step - loss: 210921.9062
Epoch 62/1400
278/278 [==============================] - 6s 20ms/step - loss: 210583.2031
Epoch 63/1400
278/278 [==============================] - 6s 20ms/step - loss: 210331.7969
Epoch 64/1400
278/278 [==============================] - 6s 20ms/step - loss: 210052.4531
Epoch 65/1400
278/278 [==============================] - 6s 20ms/step - loss: 209862.2969
Epoch 66/1400
278/278 [==============================] - 6s 20ms/step - loss: 209600.9844
Epoch 67/1400
278/278 [==============================] - 6s 20ms/step - loss: 209351.2500
Epoch 68/1400
278/278 [==============================] - 6s 20ms/step - loss: 209044.0156
Epoch 69/1400
278/278 [==============================] - 6s 20ms/step - loss: 208742.1094
Epoch 70/1400
278/278 [==============================] - 6s 20ms/step - loss: 208575.7812
Epoch 71/1400
278/278 [==============================] - 6s 20ms/step - loss: 208063.4375
Epoch 72/1400
278/278 [==============================] - 6s 20ms/step - loss: 207832.0156
Epoch 73/1400
278/278 [==============================] - 6s 20ms/step - loss: 207650.0469
Epoch 74/1400
278/278 [==============================] - 6s 21ms/step - loss: 207296.5312
Epoch 75/1400
278/278 [==============================] - 6s 20ms/step - loss: 207112.9531
Epoch 76/1400
278/278 [==============================] - 6s 20ms/step - loss: 206874.9375
Epoch 77/1400
278/278 [==============================] - 6s 21ms/step - loss: 206634.3906
Epoch 78/1400
278/278 [==============================] - 6s 21ms/step - loss: 206401.7188
Epoch 79/1400
278/278 [==============================] - 6s 21ms/step - loss: 206205.0156
Epoch 80/1400
278/278 [==============================] - 6s 21ms/step - loss: 206028.7969
Epoch 81/1400
278/278 [==============================] - 6s 20ms/step - loss: 205760.8594
Epoch 82/1400
278/278 [==============================] - 6s 21ms/step - loss: 205641.7188
Epoch 83/1400
278/278 [==============================] - 6s 20ms/step - loss: 205461.9688
Epoch 84/1400
278/278 [==============================] - 6s 20ms/step - loss: 205198.9062
Epoch 85/1400
278/278 [==============================] - 6s 20ms/step - loss: 205019.7812
Epoch 86/1400
278/278 [==============================] - 6s 20ms/step - loss: 204880.2188
Epoch 87/1400
278/278 [==============================] - 6s 20ms/step - loss: 204707.4219
Epoch 88/1400
278/278 [==============================] - 6s 20ms/step - loss: 204434.2188
Epoch 89/1400
278/278 [==============================] - 6s 20ms/step - loss: 204254.8281
Epoch 90/1400
278/278 [==============================] - 6s 20ms/step - loss: 204119.4219
Epoch 91/1400
278/278 [==============================] - 6s 20ms/step - loss: 203841.1094
Epoch 92/1400
278/278 [==============================] - 6s 21ms/step - loss: 203499.5781
Epoch 93/1400
278/278 [==============================] - 6s 20ms/step - loss: 203409.8438
Epoch 94/1400
278/278 [==============================] - 6s 20ms/step - loss: 203198.1094
Epoch 95/1400
278/278 [==============================] - 6s 20ms/step - loss: 202977.0938
Epoch 96/1400
278/278 [==============================] - 6s 20ms/step - loss: 202853.4688
Epoch 97/1400
278/278 [==============================] - 6s 21ms/step - loss: 202556.9375
Epoch 98/1400
278/278 [==============================] - 6s 21ms/step - loss: 202535.9688
Epoch 99/1400
278/278 [==============================] - 6s 21ms/step - loss: 202325.3906
Epoch 100/1400
278/278 [==============================] - 6s 21ms/step - loss: 202128.8750
Epoch 101/1400
278/278 [==============================] - 6s 21ms/step - loss: 201977.6406
Epoch 102/1400
278/278 [==============================] - 6s 21ms/step - loss: 201761.0781
Epoch 103/1400
278/278 [==============================] - 6s 21ms/step - loss: 201380.2344
Epoch 104/1400
278/278 [==============================] - 6s 21ms/step - loss: 201255.4062
Epoch 105/1400
278/278 [==============================] - 6s 21ms/step - loss: 201053.4531
Epoch 106/1400
278/278 [==============================] - 6s 21ms/step - loss: 200967.0938
Epoch 107/1400
278/278 [==============================] - 6s 21ms/step - loss: 200762.0938
Epoch 108/1400
278/278 [==============================] - 6s 21ms/step - loss: 200638.4062
Epoch 109/1400
278/278 [==============================] - 6s 21ms/step - loss: 200456.5469
Epoch 110/1400
278/278 [==============================] - 6s 21ms/step - loss: 200313.1094
Epoch 111/1400
278/278 [==============================] - 6s 21ms/step - loss: 200196.5781
Epoch 112/1400
278/278 [==============================] - 6s 21ms/step - loss: 200002.9688
Epoch 113/1400
278/278 [==============================] - 6s 21ms/step - loss: 199864.5156
Epoch 114/1400
278/278 [==============================] - 6s 21ms/step - loss: 199716.6250
Epoch 115/1400
278/278 [==============================] - 6s 21ms/step - loss: 199392.1094
Epoch 116/1400
278/278 [==============================] - 6s 21ms/step - loss: 199298.5938
Epoch 117/1400
278/278 [==============================] - 6s 21ms/step - loss: 199325.6562
Epoch 118/1400
278/278 [==============================] - 6s 21ms/step - loss: 199082.5781
Epoch 119/1400
278/278 [==============================] - 6s 21ms/step - loss: 198894.4531
Epoch 120/1400
278/278 [==============================] - 6s 21ms/step - loss: 198556.5625
Epoch 121/1400
278/278 [==============================] - 6s 21ms/step - loss: 198329.1719
Epoch 122/1400
278/278 [==============================] - 6s 21ms/step - loss: 198197.2656
Epoch 123/1400
278/278 [==============================] - 6s 21ms/step - loss: 198096.7500
Epoch 124/1400
278/278 [==============================] - 6s 21ms/step - loss: 197897.1562
Epoch 125/1400
278/278 [==============================] - 6s 21ms/step - loss: 197760.6875
Epoch 126/1400
278/278 [==============================] - 6s 21ms/step - loss: 197684.5469
Epoch 127/1400
278/278 [==============================] - 6s 21ms/step - loss: 197617.0781
Epoch 128/1400
278/278 [==============================] - 6s 21ms/step - loss: 197466.4219
Epoch 129/1400
278/278 [==============================] - 6s 21ms/step - loss: 197323.0781
Epoch 130/1400
278/278 [==============================] - 6s 21ms/step - loss: 197115.7031
Epoch 131/1400
278/278 [==============================] - 6s 21ms/step - loss: 196948.4219
Epoch 132/1400
278/278 [==============================] - 6s 20ms/step - loss: 196960.5000
Epoch 133/1400
278/278 [==============================] - 6s 21ms/step - loss: 196825.0469
Epoch 134/1400
278/278 [==============================] - 6s 21ms/step - loss: 196668.8281
Epoch 135/1400
278/278 [==============================] - 6s 21ms/step - loss: 196623.5625
Epoch 136/1400
278/278 [==============================] - 6s 21ms/step - loss: 196499.8750
Epoch 137/1400
278/278 [==============================] - 6s 21ms/step - loss: 196378.0312
Epoch 138/1400
278/278 [==============================] - 6s 21ms/step - loss: 196136.3906
Epoch 139/1400
278/278 [==============================] - 6s 21ms/step - loss: 196044.3906
Epoch 140/1400
278/278 [==============================] - 6s 21ms/step - loss: 196009.8594
Epoch 141/1400
278/278 [==============================] - 6s 21ms/step - loss: 195744.1406
Epoch 142/1400
278/278 [==============================] - 6s 21ms/step - loss: 195519.6562
Epoch 143/1400
278/278 [==============================] - 6s 20ms/step - loss: 195447.3438
Epoch 144/1400
278/278 [==============================] - 6s 21ms/step - loss: 195405.8750
Epoch 145/1400
278/278 [==============================] - 6s 21ms/step - loss: 195217.4219
Epoch 146/1400
278/278 [==============================] - 6s 21ms/step - loss: 195095.9531
Epoch 147/1400
278/278 [==============================] - 6s 21ms/step - loss: 194988.3594
Epoch 148/1400
278/278 [==============================] - 6s 21ms/step - loss: 195003.7656
Epoch 149/1400
278/278 [==============================] - 6s 21ms/step - loss: 194829.0156
Epoch 150/1400
278/278 [==============================] - 6s 20ms/step - loss: 194384.6875
Epoch 151/1400
278/278 [==============================] - 6s 21ms/step - loss: 194337.0469
Epoch 152/1400
278/278 [==============================] - 6s 21ms/step - loss: 194196.0625
Epoch 153/1400
278/278 [==============================] - 6s 21ms/step - loss: 194104.8281
Epoch 154/1400
278/278 [==============================] - 6s 21ms/step - loss: 193944.4844
Epoch 155/1400
278/278 [==============================] - 6s 21ms/step - loss: 193860.5938
Epoch 156/1400
278/278 [==============================] - 6s 21ms/step - loss: 193644.2656
Epoch 157/1400
278/278 [==============================] - 6s 21ms/step - loss: 193582.4844
Epoch 158/1400
278/278 [==============================] - 6s 21ms/step - loss: 193413.4844
Epoch 159/1400
278/278 [==============================] - 6s 20ms/step - loss: 193323.7812
Epoch 160/1400
278/278 [==============================] - 6s 21ms/step - loss: 193192.5781
Epoch 161/1400
278/278 [==============================] - 6s 21ms/step - loss: 193270.2969
Epoch 162/1400
278/278 [==============================] - 6s 21ms/step - loss: 192990.3438
Epoch 163/1400
278/278 [==============================] - 6s 21ms/step - loss: 192567.7812
Epoch 164/1400
278/278 [==============================] - 6s 21ms/step - loss: 192384.7969
Epoch 165/1400
278/278 [==============================] - 6s 21ms/step - loss: 192240.9375
Epoch 166/1400
278/278 [==============================] - 6s 21ms/step - loss: 192265.1406
Epoch 167/1400
278/278 [==============================] - 6s 20ms/step - loss: 192141.0469
Epoch 168/1400
278/278 [==============================] - 6s 21ms/step - loss: 192138.3906
Epoch 169/1400
278/278 [==============================] - 6s 21ms/step - loss: 191888.4219
Epoch 170/1400
278/278 [==============================] - 6s 21ms/step - loss: 191905.8281
Epoch 171/1400
278/278 [==============================] - 6s 21ms/step - loss: 191782.6250
Epoch 172/1400
278/278 [==============================] - 6s 21ms/step - loss: 191669.2812
Epoch 173/1400
278/278 [==============================] - 6s 21ms/step - loss: 191554.6562
Epoch 174/1400
278/278 [==============================] - 6s 21ms/step - loss: 191484.5781
Epoch 175/1400
278/278 [==============================] - 6s 21ms/step - loss: 191421.8750
Epoch 176/1400
278/278 [==============================] - 6s 21ms/step - loss: 191304.5000
Epoch 177/1400
278/278 [==============================] - 6s 21ms/step - loss: 191336.0625
Epoch 178/1400
278/278 [==============================] - 6s 21ms/step - loss: 191199.2031
Epoch 179/1400
278/278 [==============================] - 6s 21ms/step - loss: 191172.9375
Epoch 180/1400
278/278 [==============================] - 6s 21ms/step - loss: 190983.9844
Epoch 181/1400
278/278 [==============================] - 6s 21ms/step - loss: 190948.1562
Epoch 182/1400
278/278 [==============================] - 6s 21ms/step - loss: 190804.6406
Epoch 183/1400
278/278 [==============================] - 6s 21ms/step - loss: 190706.6250
Epoch 184/1400
278/278 [==============================] - 6s 21ms/step - loss: 190781.7969
Epoch 185/1400
278/278 [==============================] - 6s 20ms/step - loss: 190658.5312
Epoch 186/1400
278/278 [==============================] - 6s 21ms/step - loss: 190653.5000
Epoch 187/1400
278/278 [==============================] - 6s 21ms/step - loss: 190340.3750
Epoch 188/1400
278/278 [==============================] - 6s 21ms/step - loss: 190434.8125
Epoch 189/1400
278/278 [==============================] - 6s 21ms/step - loss: 190243.2500
Epoch 190/1400
278/278 [==============================] - 6s 21ms/step - loss: 190220.5625
Epoch 191/1400
278/278 [==============================] - 6s 21ms/step - loss: 190161.0938
Epoch 192/1400
278/278 [==============================] - 6s 21ms/step - loss: 190052.3750
Epoch 193/1400
278/278 [==============================] - 6s 21ms/step - loss: 190047.3906
Epoch 194/1400
278/278 [==============================] - 6s 21ms/step - loss: 190118.0938
Epoch 195/1400
278/278 [==============================] - 6s 21ms/step - loss: 190010.9844
Epoch 196/1400
278/278 [==============================] - 6s 21ms/step - loss: 189828.1250
Epoch 197/1400
278/278 [==============================] - 6s 21ms/step - loss: 189785.2812
Epoch 198/1400
278/278 [==============================] - 6s 21ms/step - loss: 189782.5938
Epoch 199/1400
278/278 [==============================] - 6s 21ms/step - loss: 189694.5156
Epoch 200/1400
278/278 [==============================] - 6s 21ms/step - loss: 189626.7500
Epoch 201/1400
278/278 [==============================] - 6s 21ms/step - loss: 189482.0000
Epoch 202/1400
278/278 [==============================] - 6s 21ms/step - loss: 189494.7344
Epoch 203/1400
278/278 [==============================] - 6s 21ms/step - loss: 189392.8438
Epoch 204/1400
278/278 [==============================] - 6s 21ms/step - loss: 189271.5625
Epoch 205/1400
278/278 [==============================] - 6s 21ms/step - loss: 189323.7188
Epoch 206/1400
278/278 [==============================] - 6s 21ms/step - loss: 189224.1094
Epoch 207/1400
278/278 [==============================] - 6s 21ms/step - loss: 189099.7969
Epoch 208/1400
278/278 [==============================] - 6s 21ms/step - loss: 189098.5469
Epoch 209/1400
278/278 [==============================] - 6s 21ms/step - loss: 188984.3906
Epoch 210/1400
278/278 [==============================] - 6s 21ms/step - loss: 189041.3438
Epoch 211/1400
278/278 [==============================] - 6s 21ms/step - loss: 188921.4531
Epoch 212/1400
278/278 [==============================] - 6s 21ms/step - loss: 188845.3906
Epoch 213/1400
278/278 [==============================] - 6s 21ms/step - loss: 188685.2969
Epoch 214/1400
278/278 [==============================] - 6s 21ms/step - loss: 188744.0312
Epoch 215/1400
278/278 [==============================] - 6s 20ms/step - loss: 188722.4531
Epoch 216/1400
278/278 [==============================] - 6s 21ms/step - loss: 188637.8750
Epoch 217/1400
278/278 [==============================] - 6s 21ms/step - loss: 188482.5781
Epoch 218/1400
278/278 [==============================] - 6s 21ms/step - loss: 188503.9844
Epoch 219/1400
278/278 [==============================] - 6s 21ms/step - loss: 188360.2812
Epoch 220/1400
278/278 [==============================] - 6s 21ms/step - loss: 188334.7969
Epoch 221/1400

In [13]:
for layer in model.layers:
    print(layer.name)

input_1
dense
reshape
conv2d
conv2d_1
flatten
dense_1
reshape_1
conv2d_transpose
conv2d_transpose_1
dropout
flatten_1
dense_2
dense_3
dense_4

In [23]:
from tensorflow.keras.models import Model
latent_model = Model(inputs=input_gex, outputs=hidden_layer)

In [15]:
model.predict( W.iloc[1:2])

1/1 [==============================] - 0s 284ms/step

array([[1.31264984e+02, 0.00000000e+00, 1.91385635e+02, 0.00000000e+00,
        0.00000000e+00, 3.98622528e+02, 3.70863464e+02, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 5.12155151e+02, 4.74552277e+02, 1.77394989e+02,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 1.25315186e+02, 5.57568321e+01,
        0.00000000e+00, 0.00000000e+00, 3.38392944e+02, 0.00000000e+00,
        0.00000000e+00, 7.22407349e+02, 0.00000000e+00, 1.46514270e+03,
        0.00000000e+00, 2.23223495e+02, 1.43386917e+01, 0.00000000e+00,
        1.40667587e+02, 5.35112976e+02, 4.92976654e+02, 5.39690056e+01,
        6.28855713e+02, 0.00000000e+00, 0.00000000e+00, 6.71266235e+02,
        7.17289062e+02, 1.21579475e+02, 2.59756107e+01, 0.00000000e+00,
        0.00000000e+00, 4.45819778e+01, 0.00000000e+00, 0.00000000e+00,
        4.36872284e+02, 3.59081207e+02, 0.00000000e+00, 5.46613464e+02,
        7.13617554e+01, 0.00000000e+00, 2.34294643e+01, 0.00000000e+00,
        7.06648987e+02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70009912e+03,
        1.73714813e+02, 0.00000000e+00, 3.73499268e+02, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 6.55105347e+02, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 9.18565674e+02, 1.27861343e+02,
        0.00000000e+00, 1.34382010e-01, 3.48821777e+02, 0.00000000e+00,
        0.00000000e+00, 2.11559677e+02, 0.00000000e+00, 1.34518337e+01,
        0.00000000e+00, 4.72026062e+01, 0.00000000e+00, 0.00000000e+00,
        6.17620911e+02, 1.33162231e+01, 8.11528091e+01, 2.51482330e+02,
        8.03706360e+02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 4.36286049e+01, 7.44024887e+01, 1.09557590e+01,
        0.00000000e+00, 1.04474463e+03, 3.39369385e+02, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 4.75135590e+02, 1.81277573e+02,
        4.55689606e+02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 5.31759186e+01, 1.23716382e+03, 0.00000000e+00,
        0.00000000e+00]], dtype=float32)

In [16]:
model.predict( W.iloc[4:5])

1/1 [==============================] - 0s 19ms/step

array([[   0.      ,  241.37297 ,    0.      ,    0.      ,  302.0685  ,
           0.      ,  131.81558 ,    0.      ,    0.      ,    0.      ,
           0.      ,    0.      ,    0.      ,   88.75305 ,    0.      ,
           0.      ,    0.      ,    0.      ,    0.      ,  607.5684  ,
           0.      ,    0.      ,    0.      ,    0.      ,    0.      ,
           0.      ,  424.03433 ,    0.      ,    0.      ,    0.      ,
           0.      ,    0.      ,    0.      ,  357.60678 ,  431.24225 ,
         244.07965 ,   17.801702,    0.      ,    0.      ,    0.      ,
         870.7848  ,    0.      ,  231.49942 ,    0.      ,    0.      ,
           0.      ,  575.5794  ,    0.      ,  126.14164 ,  575.6279  ,
          14.614671,   50.178303,  468.7765  ,  170.71234 ,    0.      ,
           0.      ,    0.      ,  182.7847  ,   33.410492,    0.      ,
           0.      ,    0.      ,    0.      ,    0.      ,    0.      ,
           0.      ,    0.      , 2931.9575  ,    0.      ,    0.      ,
         149.3574  ,    0.      ,    0.      ,  331.54282 ,    0.      ,
         550.53674 ,   85.43632 ,  187.06157 ,  104.34293 ,    0.      ,
         432.60687 ,    0.      ,  503.45422 ,    0.      ,    0.      ,
         410.54218 ,    0.      ,    0.      ,    0.      ,    0.      ,
         242.5134  ,    0.      ,    0.      ,  495.2788  ,  772.2389  ,
         794.17834 ,  908.7517  ,    0.      ,  254.10692 ,    0.      ,
           0.      ,   47.508533,  235.39812 ,  203.45068 ,    0.      ,
         176.82924 ,  574.0079  ,  287.69748 ,    0.      ,  418.4492  ,
         140.18184 ,  291.7898  ,  750.078   ,  387.46698 ,  142.31668 ,
           0.      ,    0.      ,  890.94006 , 1065.129   ,    0.      ,
           0.      ]], dtype=float32)

In [17]:
integration_pred = latent_model.predict( W)

1110/1110 [==============================] - 2s 1ms/step

In [24]:
pd.DataFrame(integration_pred[1:50,1:50])

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,0.0,0.000000,0.0,35.472549,0.0,0.000000,0.0,0.0,0.0,0.798549,...,0.0,105.749825,19.453865,0.0,32.836594,0.0,15.519721,0.000000,0.0,0.0
1,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,64.104187,2.041360,0.0,62.545567,0.0,50.675880,0.000000,0.0,0.0
2,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,23.370670,...,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0
3,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,37.314919,...,0.0,43.495281,71.366272,0.0,0.000000,0.0,75.383720,0.000000,0.0,0.0
4,0.0,0.000000,0.0,6.303603,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,0.000000,72.740868,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0
5,0.0,0.000000,0.0,0.000000,0.0,23.242109,0.0,0.0,0.0,5.023887,...,0.0,11.910394,33.495125,0.0,45.537582,0.0,10.590414,0.000000,0.0,0.0
6,0.0,0.000000,0.0,36.465187,0.0,0.000000,0.0,0.0,0.0,7.256657,...,0.0,41.674850,47.641575,0.0,4.274441,0.0,20.562767,0.000000,0.0,0.0
7,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,47.325619,0.000000,0.0,94.540611,0.0,78.171875,76.400444,0.0,0.0
8,0.0,5.691920,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,49.877533,...,0.0,85.156822,114.295082,0.0,86.029755,0.0,18.975483,0.000000,0.0,0.0
9,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,71.683403,...,0.0,9.890483,65.132507,0.0,64.267532,0.0,39.269470,3.980707,0.0,0.0
10,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,50.941845,...,0.0,0.000000,34.793697,0.0,18.931190,0.0,32.014759,0.000000,0.0,0.0
11,0.0,162.977737,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,49.986523,127.188263,0.0,104.143669,0.0,1.249949,0.000000,0.0,0.0
12,0.0,181.696625,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,77.896065,170.708496,0.0,185.171783,0.0,15.876741,0.000000,0.0,0.0
13,0.0,0.000000,0.0,36.574615,0.0,0.000000,0.0,0.0,0.0,0.176760,...,0.0,7.096427,50.542358,0.0,43.136101,0.0,50.861336,0.000000,0.0,0.0
14,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,49.493595,...,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,8.524132,0.0,0.0
15,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,21.450031,...,0.0,18.200825,65.223618,0.0,26.471434,0.0,22.796665,0.000000,0.0,0.0
16,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,27.753300,...,0.0,15.166364,65.148659,0.0,0.000000,0.0,54.727531,0.000000,0.0,0.0
17,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,47.327091,...,0.0,23.933023,35.642578,0.0,46.007851,0.0,0.000000,41.178154,0.0,0.0
18,0.0,0.000000,0.0,20.416325,0.0,19.153246,0.0,0.0,0.0,14.247674,...,0.0,8.510480,18.801117,0.0,48.195171,0.0,33.736141,0.000000,0.0,0.0
19,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,127.292976,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0
20,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,13.638041,...,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0
21,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,47.535145,...,0.0,0.000000,0.000000,0.0,0.000000,0.0,83.029472,0.000000,0.0,0.0
22,0.0,0.000000,0.0,36.743336,0.0,0.575800,0.0,0.0,0.0,18.059340,...,0.0,0.000000,50.272938,0.0,27.085587,0.0,16.342854,0.000000,0.0,0.0
23,0.0,37.555050,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,4.338235,...,0.0,54.591911,21.686977,0.0,74.138313,0.0,30.380489,23.597097,0.0,0.0
24,0.0,0.000000,0.0,15.544496,0.0,0.000000,0.0,0.0,0.0,7.978765,...,0.0,27.326868,11.984282,0.0,73.712349,0.0,24.746851,0.000000,0.0,0.0
25,0.0,140.039673,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,35.042374,155.553986,0.0,46.248783,0.0,22.747419,0.000000,0.0,0.0
26,0.0,0.000000,0.0,28.661188,0.0,0.000000,0.0,0.0,0.0,34.028011,...,0.0,65.562325,0.000000,0.0,37.064983,0.0,49.960911,60.861385,0.0,0.0
27,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,41.207226,...,0.0,108.702980,55.089073,0.0,56.945705,0.0,40.876583,28.979115,0.0,0.0
28,0.0,0.000000,0.0,39.366440,0.0,0.000000,0.0,0.0,0.0,34.279381,...,0.0,41.845543,96.460960,0.0,23.951185,0.0,26.419834,0.000000,0.0,0.0
29,0.0,0.000000,0.0,26.767582,0.0,0.000000,0.0,0.0,0.0,37.229221,...,0.0,47.038452,34.497208,0.0,24.819445,0.0,26.298145,0.000000,0.0,0.0
30,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,60.995430,53.181564,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0
31,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,6.692225,...,0.0,0.000000,44.697063,0.0,58.811115,0.0,7.727703,0.000000,0.0,0.0
32,0.0,154.255371,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,45.965195,76.472603,0.0,137.400452,0.0,80.471474,0.000000,0.0,0.0
33,0.0,0.000000,0.0,20.993679,0.0,0.000000,0.0,0.0,0.0,6.653016,...,0.0,0.000000,32.894436,0.0,0.000000,0.0,67.293030,0.000000,0.0,0.0
34,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,58.918747,...,0.0,84.315025,73.367966,0.0,34.980213,0.0,87.783333,0.000000,0.0,0.0
35,0.0,0.000000,0.0,17.404364,0.0,0.000000,0.0,0.0,0.0,23.390137,...,0.0,30.449898,0.000000,0.0,52.546841,0.0,14.027351,0.000000,0.0,0.0
36,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,78.828102,117.421761,0.0,42.009563,0.0,64.136963,0.000000,0.0,0.0
37,0.0,140.829025,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,93.209808,75.676353,0.0,28.345358,0.0,0.000000,0.000000,0.0,0.0
38,0.0,0.000000,0.0,13.127886,0.0,0.000000,0.0,0.0,0.0,30.196678,...,0.0,53.090851,44.924191,0.0,0.000000,0.0,72.671021,0.000000,0.0,0.0
39,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,118.149368,108.248604,0.0,63.400818,0.0,61.283722,0.000000,0.0,0.0
40,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,40.546165,...,0.0,69.835075,106.269638,0.0,42.351494,0.0,53.234985,2.393487,0.0,0.0
41,0.0,0.000000,0.0,0.701224,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,44.435387,47.539036,0.0,0.000000,0.0,0.000000,138.326172,0.0,0.0
42,0.0,0.000000,0.0,63.916206,0.0,0.000000,0.0,0.0,0.0,51.949169,...,0.0,9.003922,82.777695,0.0,40.771404,0.0,44.353161,0.000000,0.0,0.0
43,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,22.607273,...,0.0,52.257435,25.612789,0.0,29.751501,0.0,0.000000,2.398489,0.0,0.0
44,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,44.653553,...,0.0,0.000000,45.375397,0.0,34.274727,0.0,32.096203,0.000000,0.0,0.0
45,0.0,145.154907,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.0,143.646896,188.628464,0.0,95.952148,0.0,0.000000,0.000000,0.0,0.0
46,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,28.673187,...,0.0,39.942284,14.384706,0.0,22.516275,0.0,3.362422,0.000000,0.0,0.0
47,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,5.255878,...,0.0,113.314117,65.193184,0.0,83.707840,0.0,32.280609,0.000000,0.0,0.0
48,0.0,21.061516,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,69.569611,...,0.0,11.559454,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0

In [19]:
integration_pred = integration_pred.reshape([integration_pred.shape[0],-1])

In [20]:
integration_pred.shape

(35515, 225)

In [21]:
integration_pred = integration_pred.reshape([integration_pred.shape[0],-1])
integration_pred.shape

(35515, 225)

In [22]:
pd.DataFrame(integration_pred)

,0,1,2,3,4,5,6,7,8,9,...,215,216,217,218,219,220,221,222,223,224
0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,102.337921,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
1,67.945328,0.0,0.000000,0.0,35.472549,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,19.417398,0.000000,0.0
2,25.923313,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
3,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,61.579628,0.0,0.0,0.0,0.0,0.0,0.0,48.461872,0.000000,0.0
4,42.633919,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35510,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,50.004463,0.0,0.0,0.0,0.0,0.0,0.0,48.376793,0.000000,0.0
35511,95.926804,0.0,0.000000,0.0,6.670987,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
35512,15.759350,0.0,0.000000,0.0,24.743168,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
35513,77.846939,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,20.496489,0.0
35514,67.613121,0.0,55.670429,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,35.200516,0.0

In [25]:
pd.DataFrame(integration_pred).to_csv("integration_pred_new_method_gex_to_TCR_beta_chain_10X_donor_1_only.csv", index=False)